### ISSUE TITLE
The "show all versions" link doesn't work with some packages, e.g. Newtonsoft.Json

### ISSUE THREAD

**Issue by leidegre** [NuGetPackageExplorer/NuGetPackageExplorer#1002]
**Type**: Bug

**NPE version**: 5.7.27+7398df9396

**OS version**: Windows 10.0.18362.836

**Installed from**: Microsoft Store

When I use the "Open from Feed" from the File menu and browse for example, `Newtonsoft.Json` and click "show all versions" nothing happens. This isn't limited to the `Newtonsoft.Json` package nor does it fail with every package. As of writing, the "show all versions" link does nothing when browsing the `Newtonsoft.Json` package.

![image](http://g.recordit.co/jJjfmEfMn5.gif)

**Comment by clairernovotny** [comment]
I'm not able to reproduce this:

![image](https://user-images.githubusercontent.com/1427284/83260231-6a0b3e00-a187-11ea-82e6-8c0a309d45ee.png)

@campersau any idea what may be going on?

**Comment by campersau** [comment]
I am only able to reproduce this behaviour when I manually throw an exception in [`LoadPackages`](https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/47c2fc6fd4084fde2fa16d9be5a36fa007936b53/PackageViewModel/PackageChooser/PackageInfoViewModel.cs#L204-L259). Unfortunately the [`ErrorMessage`](https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/47c2fc6fd4084fde2fa16d9be5a36fa007936b53/PackageViewModel/PackageChooser/PackageInfoViewModel.cs#L251) isn't visible in the UI..
Here the `ErrorMessage` property got added in the view model but not in XAML:
https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/commit/ca14f0d18983f18875916cd459c6c96cf6b69d1b#diff-a2b4dd65024eb07c98b61edccd729c82R158

**Comment by leidegre** [comment]
I can test the new release when it becomes available.

**Comment by campersau** [comment]
You can also try out the zip download from here https://dev.azure.com/clairernovotny/GitBuilds/_build/results?buildId=3728&view=artifacts&type=publishedArtifacts

**Comment by leidegre** [comment]
It doesn't reproduce, nor fail with that build.

**Comment by leidegre** [comment]
It also happens with the package `Nunit`.

**Comment by leidegre** [comment]
Got version `5.7.70+7bb55bc2c0` from the store now. Here's the error.

![image](https://user-images.githubusercontent.com/63085/84574633-f16fc880-ada7-11ea-9236-1f1c0b30533f.png)

**Comment by clairernovotny** [comment]
Closing as no reproducible. Please re-open if this is still occurring.
