### ISSUE TITLE
WinGet support

### ISSUE THREAD

**Issue by azchohfi** [NuGetPackageExplorer/NuGetPackageExplorer#1011]
**Type**:
- Feature request

**OS version**: Windows

It would be awesome to be able to install this thru winget (https://github.com/microsoft/winget-pkgs). I'm fine installing it thru chocolatey, but a single tool for this would be best.

**Comment by clairernovotny** [comment]
When WinGet supports installing packages from the Windows Store, then we'll support it. 

Why install it from WinGet over the store as-is? The store version is always up-to-date as it auto updates.

**Comment by azchohfi** [comment]
I believe they will support it on v0.2 (https://github.com/microsoft/winget-cli/issues/117), which should launch by the end of the month, based on their milestone on github.
Its a matter of easiness for setting up an environment. I love the idea of having a script that installs all (or at least most) of the software I use on a day-to-day basis, and NuGet Package Explorer is one of them 😊

**Comment by ridomin** [comment]
> When WinGet supports installing packages from the Windows Store, then we'll support it.

I believe the ask is to avoid dependencies with the Store installation system. 
 
> Why install it from WinGet over the store as-is? The store version is always up-to-date as it auto updates.

Why not include a WinGet package with a vanilla installation? (just EXE without MSIX), as chocolately.

XCopy deployments are much more reliable than APPX based, see #1083

**Comment by clairernovotny** [comment]
This app gets frequent updates and I can see a clear difference between Choco users and MSIX users. MSIX users are always up-to-date.

I do not wish to support another mechanism that doesn't support always-up-to-date.

**Comment by cataggar** [comment]
This works now. It would be good to add this to README.md:
```
winget install "NuGet Package Explorer"
```

Full example:
```
PS C:\Users\cataggar\io\avs> winget install "NuGet Package Explorer"
Found NuGet Package Explorer [9WZDNCRDMDM3] Version Unknown
This package is provided through Microsoft Store. winget may need to acquire the package from Microsoft Store on behalf of the current user.
Version: Unknown
Publisher: Claire Novotny LLC
Publisher Url: https://github.com/NuGetPackageExplorer/NuGetPackageExplorer
Publisher Support Url: https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/issues
Description: IMPORTANT: This app works with Windows 10 Pro and Home.  This app performs with core functionality on Windows 10 S but binary enumeration and plugins do not work.

This app allows browsing NuGet packages from an online feed and viewing contents of the packages. NuGet is a package management tool in Visual Studio. More information on NuGet can be viewed at http://docs.nuget.org.
License: ms-windows-store://pdp/?ProductId=9WZDNCRDMDM3
Privacy Url: https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/main/PrivacyPolicy.md
Agreements:
Category: Developer tools
Pricing: Free
Free Trial: No
Terms of Transaction: https://aka.ms/microsoft-store-terms-of-transaction
Seizure Warning: https://aka.ms/microsoft-store-seizure-warning
Store License Terms: https://aka.ms/microsoft-store-license


The publisher requires that you view the above information and accept the agreements before installing.
Do you agree to the terms?
[Y] Yes  [N] No: y
Verifying/Requesting package acquisition...
Verifying/Requesting package acquisition success
Starting package install...
  ██████████████████████████████  100%
Successfully installed
```

```
PS C:\Users\cataggar\io\avs> winget --version
v1.1.12653
```

It shows up if you search `NuGet`:
```
PS C:\Users\cataggar\io\avs> winget search NuGet
Name                   Id                                        Version  Source
----------------------------------------------------------------------------------
NuGet Package Explorer 9WZDNCRDMDM3                              Unknown  msstore
NuGet Cache Cleaner    9P7MQ2FFX51F                              Unknown  msstore
NPE (Nightly)          NuGetPackageExplorer.NuGetPackageExplorer 5.8.34.0 winget
```

**Comment by clairernovotny** [comment]
@cataggar Awesome! Can you please submit a PR with these details?
