### ISSUE TITLE
net5.0 dependencies throw error.

### ISSUE THREAD

**Issue by eosrios** [NuGetPackageExplorer/NuGetPackageExplorer#1031]
Hi! Thanks for reporting this feature/bug/question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

**Type**: Bug
**NPE version**: NuGet Package Explorer - Nightly - X64 - (5.7.75+eb494b87d6)
**OS version**: Windows 10
**Installed from**: Microsoft Store 

In case of a BUG:
- Steps to recreate:
Edit Metadata -> Edit Dependencies -> add net5.0 group, add any assembly, ok, apply. 
At this point everything looks fine. Then you save or save as and it throws an error, assumably because there is no "version" associated with net5.0 like netcoreapp has.

- What is the current result?
Unable to save package as long as any .net 5 dependencies are present
- What is the expected result?
Able to add .net 5 dependencies and save package.

- Please post full exception details in case of an Exception (message, stacktrace, inner exceptions).
FrameworkName cannot have less than two components or more than three components. 

- Are there any workarounds? yes/no
No, unless you count removing the dependencies and saving without them.
- Is there a version in which it did work?
No
- Is there a package on Nuget.org which shows the bug?
No, unable to save.

**Comment by nkolev92** [comment]
original bug is tracked in https://github.com/NuGet/Home/issues/9682

**Comment by clairernovotny** [comment]
This fixed now in the 5.8.x NPE versions.
