### ISSUE TITLE
AppCrash when opening certain Nugets. ie. notepadplusplus

### ISSUE THREAD

**Issue by trekytech7** [NuGetPackageExplorer/NuGetPackageExplorer#1038]
**Type**: BUG
**NPE version**: 5.7.75.18923
**OS version**: Windows 10 - 1903, Windows Server 2012 R2
**Installed from**: Chocolatey.org via commandline (choco install...)

In case of a BUG:
* What is the current result?
Open a Nuget such as notepadplusplus and NPE crashes. The issue seems to result from something within the iconURL of the .nuspec file.
* What is the expected result?
Obviously the program should open and allow editing, lol.  ;)
* Please post full exception details in case of an Exception (message, stacktrace, inner exceptions).
Faulting application name: NugetPackageExplorer.exe, version: 5.7.75.18923, time stamp: 0x5ecf7511
Faulting module name: KERNELBASE.dll, version: 6.3.9600.19671, time stamp: 0x5e673d0b
Exception code: 0xe0434352
Fault offset: 0x00000000000088dc
Faulting process id: 0xe98
Faulting application start time: 0x01d645a67b51a420
Faulting application path: C:\ProgramData\chocolatey\lib\NugetPackageExplorer\NugetPackageExplorer.exe
Faulting module path: C:\Windows\system32\KERNELBASE.dll
Report Id: b9bcea8a-b199-11ea-813d-8ccde5e873e0
Faulting package full name: 
Faulting package-relative application ID: 

If you'd like WER data then please ask...

* Are there any workarounds? yes/no
I used an older Nuget and copied the Nugets data, and omitted the iconURL. Works.
* Is there a version in which it did work?
This issue was encountered this year, previously no trouble. Sorry, I can't recall exactly which previous version... It's occurred for at least a few versions back.
* Is there a package on Nuget.org which shows the bug?
notepadplusplus, viber, pycharm...

Thx

**Comment by campersau** [comment]
I can't seem find the mentioned packages on nuget.org and the packages I found didn't result into a crash for me: 
- [notepadplusplus](https://www.nuget.org/packages?q=notepadplusplus)
- [viber](https://www.nuget.org/packages?q=viber)
- [pycharm](https://www.nuget.org/packages?q=pycharm)

Can you please share the links to the packages?

**Comment by trekytech7** [comment]
No problem... I just download the Nugets from Chocolatey and edit them...
*https://chocolatey.org/api/v2/package/notepadplusplus & https://chocolatey.org/api/v2/package/notepadplusplus.install
*https://chocolatey.org/api/v2/package/viber
*https://chocolatey.org/api/v2/package/pycharm

Hope this helps. They are consistently crashing NPE on our chocolatey repo server and my workstation at work... (thou I'm mostly working from home these days ;) )

**Comment by svick** [comment]
@trekytech7 I don't get any exception when I open the packages you listed in NPE 5.7.113. Do you still encounter the issue? If you do, can you post the exception information, including the message and stack trace (the Event Viewer information you posted does not say much)?

**Comment by trekytech7** [comment]
@svick Here's the result I'm getting currently...

- Message: NugetPackageExplorer has stopped working. Then it gives choices about looking online for a solution, closing, or trying debugging...
- Log data:`Type :		Error
Date :		2020-07-28
Time :		11:18:46 AM
Event :		1000
Source :		Application Error
Category :	Application Crashing Events
User :		N/A
Computer :	xx
Description:
Faulting application name: NugetPackageExplorer.exe, version: 5.7.113.57457, time stamp: 0x5eda9993
Faulting module name: KERNELBASE.dll, version: 6.3.9600.19724, time stamp: 0x5ec5262a
Exception code: 0xe0434352
Fault offset: 0x0000000000007afc
Faulting process id: 0xd38
Faulting application start time: 0x01d66503232a726b
Faulting application path: C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\NugetPackageExplorer.exe
Faulting module path: C:\Windows\system32\KERNELBASE.dll
Report Id: 64b20c96-d0f6-11ea-813f-c8eb68e53c5b
Faulting package full name: 
Faulting package-relative application ID: 
`
- Appcrash report: `Version=1
EventType=APPCRASH
EventTime=132404303279550618
ReportType=2
Consent=1
ReportIdentifier=64b20c97-d0f6-11ea-813f-c8eb68e53c5b
IntegratorReportIdentifier=64b20c96-d0f6-11ea-813f-c8eb68e53c5b
NsAppName=NugetPackageExplorer.exe
Response.type=4
Sig[0].Name=Application Name
Sig[0].Value=NugetPackageExplorer.exe
Sig[1].Name=Application Version
Sig[1].Value=5.7.113.57457
Sig[2].Name=Application Timestamp
Sig[2].Value=5eda9993
Sig[3].Name=Fault Module Name
Sig[3].Value=KERNELBASE.dll
Sig[4].Name=Fault Module Version
Sig[4].Value=6.3.9600.19724
Sig[5].Name=Fault Module Timestamp
Sig[5].Value=5ec5262a
Sig[6].Name=Exception Code
Sig[6].Value=e0434352
Sig[7].Name=Exception Offset
Sig[7].Value=0000000000007afc
DynamicSig[1].Name=OS Version
DynamicSig[1].Value=6.3.9600.2.0.0.400.8
DynamicSig[2].Name=Locale ID
DynamicSig[2].Value=4105
DynamicSig[22].Name=Additional Information 1
DynamicSig[22].Value=518b
DynamicSig[23].Name=Additional Information 2
DynamicSig[23].Value=518b34581bba4bd63a88a04e2cf0e01b
DynamicSig[24].Name=Additional Information 3
DynamicSig[24].Value=d0d3
DynamicSig[25].Name=Additional Information 4
DynamicSig[25].Value=d0d36a45ec5dae982218f8f6b172b0fb
UI[2]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\NugetPackageExplorer.exe
UI[3]=NuGetPackageExplorer has stopped working
UI[4]=Windows can check online for a solution to the problem.
UI[5]=Check online for a solution and close the program
UI[6]=Check online for a solution later and close the program
UI[7]=Close the program
LoadedModule[0]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\NugetPackageExplorer.exe
LoadedModule[1]=C:\Windows\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\Windows\system32\KERNEL32.DLL
LoadedModule[3]=C:\Windows\system32\KERNELBASE.dll
LoadedModule[4]=C:\Windows\system32\USER32.dll
LoadedModule[5]=C:\Windows\system32\SHELL32.dll
LoadedModule[6]=C:\Windows\system32\ADVAPI32.dll
LoadedModule[7]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\api-ms-win-crt-runtime-l1-1-0.dll
LoadedModule[8]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\api-ms-win-crt-stdio-l1-1-0.dll
LoadedModule[9]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\api-ms-win-crt-heap-l1-1-0.dll
LoadedModule[10]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\api-ms-win-crt-string-l1-1-0.dll
LoadedModule[11]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\api-ms-win-crt-convert-l1-1-0.dll
LoadedModule[12]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\api-ms-win-crt-locale-l1-1-0.dll
LoadedModule[13]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\api-ms-win-crt-math-l1-1-0.dll
LoadedModule[14]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\api-ms-win-crt-time-l1-1-0.dll
LoadedModule[15]=C:\Windows\system32\GDI32.dll
LoadedModule[16]=C:\Windows\system32\msvcrt.dll
LoadedModule[17]=C:\Windows\SYSTEM32\combase.dll
LoadedModule[18]=C:\Windows\system32\SHLWAPI.dll
LoadedModule[19]=C:\Windows\SYSTEM32\sechost.dll
LoadedModule[20]=C:\Windows\system32\RPCRT4.dll
LoadedModule[21]=C:\Windows\system32\SspiCli.dll
LoadedModule[22]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\ucrtbase.DLL
LoadedModule[23]=C:\Windows\system32\IMM32.DLL
LoadedModule[24]=C:\Windows\system32\MSCTF.dll
LoadedModule[25]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\hostfxr.dll
LoadedModule[26]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\api-ms-win-crt-filesystem-l1-1-0.dll
LoadedModule[27]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\hostpolicy.dll
LoadedModule[28]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\coreclr.dll
LoadedModule[29]=C:\Windows\system32\ole32.dll
LoadedModule[30]=C:\Windows\system32\OLEAUT32.dll
LoadedModule[31]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\api-ms-win-crt-utility-l1-1-0.dll
LoadedModule[32]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.Private.CoreLib.dll
LoadedModule[33]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\clrjit.dll
LoadedModule[34]=C:\Windows\SYSTEM32\kernel.appcore.dll
LoadedModule[35]=C:\Windows\SYSTEM32\CRYPTBASE.dll
LoadedModule[36]=C:\Windows\SYSTEM32\bcryptPrimitives.dll
LoadedModule[37]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\NuGetPackageExplorer.dll
LoadedModule[38]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\PresentationFramework.dll
LoadedModule[39]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\WindowsBase.dll
LoadedModule[40]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.Runtime.dll
LoadedModule[41]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.Xaml.dll
LoadedModule[42]=C:\Windows\system32\uxtheme.dll
LoadedModule[43]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.IO.Packaging.dll
LoadedModule[44]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\netstandard.dll
LoadedModule[45]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.Private.Uri.dll
LoadedModule[46]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\PresentationCore.dll
LoadedModule[47]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\mscorlib.dll
LoadedModule[48]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\DirectWriteForwarder.dll
LoadedModule[49]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.Runtime.Extensions.dll
LoadedModule[50]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.Runtime.InteropServices.dll
LoadedModule[51]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.Runtime.CompilerServices.VisualC.dll
LoadedModule[52]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.Diagnostics.Debug.dll
LoadedModule[53]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.Threading.dll
LoadedModule[54]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\Microsoft.Win32.Primitives.dll
LoadedModule[55]=C:\Windows\SYSTEM32\dwrite.dll
LoadedModule[56]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.Collections.NonGeneric.dll
LoadedModule[57]=C:\Windows\SYSTEM32\BCrypt.dll
LoadedModule[58]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.Linq.dll
LoadedModule[59]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.Collections.dll
LoadedModule[60]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\Microsoft.Win32.Registry.dll
LoadedModule[61]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.Collections.Specialized.dll
LoadedModule[62]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.ComponentModel.Primitives.dll
LoadedModule[63]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.Diagnostics.Process.dll
LoadedModule[64]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.Threading.Thread.dll
LoadedModule[65]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\PresentationNative_cor3.dll
LoadedModule[66]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.Configuration.ConfigurationManager.dll
LoadedModule[67]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.Xml.ReaderWriter.dll
LoadedModule[68]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.Private.Xml.dll
LoadedModule[69]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.IO.FileSystem.dll
LoadedModule[70]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.Net.WebClient.dll
LoadedModule[71]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.Memory.dll
LoadedModule[72]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.Security.Cryptography.Algorithms.dll
LoadedModule[73]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.Text.Encoding.Extensions.dll
LoadedModule[74]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.ComponentModel.TypeConverter.dll
LoadedModule[75]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.ObjectModel.dll
LoadedModule[76]=C:\Windows\system32\dwmapi.dll
LoadedModule[77]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\Core.dll
LoadedModule[78]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\Microsoft.ApplicationInsights.dll
LoadedModule[79]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.Diagnostics.DiagnosticSource.dll
LoadedModule[80]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.Xml.XDocument.dll
LoadedModule[81]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.Diagnostics.Tracing.dll
LoadedModule[82]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.Private.Xml.Linq.dll
LoadedModule[83]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\AppInsights.WindowsDesktop.dll
LoadedModule[84]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.Runtime.InteropServices.RuntimeInformation.dll
LoadedModule[85]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.Security.Cryptography.Primitives.dll
LoadedModule[86]=C:\Windows\SYSTEM32\secur32.dll
LoadedModule[87]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.Collections.Concurrent.dll
LoadedModule[88]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.Security.Cryptography.Csp.dll
LoadedModule[89]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.Threading.Tasks.dll
LoadedModule[90]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.Threading.ThreadPool.dll
LoadedModule[91]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.Diagnostics.TraceSource.dll
LoadedModule[92]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.Windows.Extensions.dll
LoadedModule[93]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.ComponentModel.dll
LoadedModule[94]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.Net.Requests.dll
LoadedModule[95]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.Net.Primitives.dll
LoadedModule[96]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.Net.WebHeaderCollection.dll
LoadedModule[97]=C:\Windows\SYSTEM32\shcore.dll
LoadedModule[98]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\PresentationFramework.AeroLite.dll
LoadedModule[99]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.Management.dll
LoadedModule[100]=C:\Windows\SYSTEM32\clbcatq.dll
LoadedModule[101]=C:\Windows\system32\wbem\wmiutils.dll
LoadedModule[102]=C:\Windows\SYSTEM32\wbemcomn.dll
LoadedModule[103]=C:\Windows\system32\WS2_32.dll
LoadedModule[104]=C:\Windows\system32\NSI.dll
LoadedModule[105]=C:\Windows\SYSTEM32\CRYPTSP.dll
LoadedModule[106]=C:\Windows\system32\rsaenh.dll
LoadedModule[107]=C:\Windows\system32\wbem\wbemprox.dll
LoadedModule[108]=C:\Windows\Microsoft.NET\Framework64\v4.0.30319\wminet_utils.dll
LoadedModule[109]=C:\Windows\SYSTEM32\VCRUNTIME140_CLR0400.dll
LoadedModule[110]=C:\Windows\SYSTEM32\ucrtbase_clr0400.dll
LoadedModule[111]=C:\Windows\system32\wbem\wbemsvc.dll
LoadedModule[112]=C:\Windows\system32\wbem\fastprox.dll
LoadedModule[113]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.Net.NetworkInformation.dll
LoadedModule[114]=C:\Windows\SYSTEM32\iphlpapi.dll
LoadedModule[115]=C:\Windows\SYSTEM32\WINNSI.DLL
LoadedModule[116]=C:\Windows\SYSTEM32\DNSAPI.dll
LoadedModule[117]=C:\Windows\SYSTEM32\dhcpcsvc6.DLL
LoadedModule[118]=C:\Windows\SYSTEM32\dhcpcsvc.DLL
LoadedModule[119]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.Net.NameResolution.dll
LoadedModule[120]=C:\Windows\system32\napinsp.dll
LoadedModule[121]=C:\Windows\system32\NLAapi.dll
LoadedModule[122]=C:\Windows\System32\mswsock.dll
LoadedModule[123]=C:\Windows\System32\winrnr.dll
LoadedModule[124]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\PackageViewModel.dll
LoadedModule[125]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.ComponentModel.Composition.dll
LoadedModule[126]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\NuGetPackageExplorer.Types.dll
LoadedModule[127]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\OSVersionHelper.dll
LoadedModule[128]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.Linq.Expressions.dll
LoadedModule[129]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\NuGet.Protocol.dll
LoadedModule[130]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\NuGet.Packaging.dll
LoadedModule[131]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.Net.Http.dll
LoadedModule[132]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\ICSharpCode.AvalonEdit.dll
LoadedModule[133]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\AuthenticodeExaminer.dll
LoadedModule[134]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\NuGet.Credentials.dll
LoadedModule[135]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\NuGet.Configuration.dll
LoadedModule[136]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\NuGet.Versioning.dll
LoadedModule[137]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\NuGet.Frameworks.dll
LoadedModule[138]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\NuGet.Common.dll
LoadedModule[139]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.Text.RegularExpressions.dll
LoadedModule[140]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.dll
LoadedModule[141]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.Runtime.Serialization.Formatters.dll
LoadedModule[142]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.Xml.XmlSerializer.dll
LoadedModule[143]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.Reflection.Emit.ILGeneration.dll
LoadedModule[144]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.Reflection.Emit.dll
LoadedModule[145]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.Reflection.Primitives.dll
LoadedModule[146]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\UIAutomationTypes.dll
LoadedModule[147]=C:\Windows\SYSTEM32\urlmon.dll
LoadedModule[148]=C:\Windows\SYSTEM32\iertutil.dll
LoadedModule[149]=C:\Windows\SYSTEM32\WININET.dll
LoadedModule[150]=C:\Windows\SYSTEM32\USERENV.dll
LoadedModule[151]=C:\Windows\SYSTEM32\profapi.dll
LoadedModule[152]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\wpfgfx_cor3.dll
LoadedModule[153]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\D3DCompiler_47_cor3.dll
LoadedModule[154]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\api-ms-win-crt-private-l1-1-0.dll
LoadedModule[155]=C:\Windows\SYSTEM32\WindowsCodecs.dll
LoadedModule[156]=C:\Windows\SYSTEM32\d3d9.dll
LoadedModule[157]=C:\Windows\SYSTEM32\VERSION.dll
LoadedModule[158]=C:\Windows\SYSTEM32\d3d10warp.dll
LoadedModule[159]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\GrayscaleEffect.dll
LoadedModule[160]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\PresentationFramework.Aero.dll
LoadedModule[161]=C:\Windows\SYSTEM32\wtsapi32.dll
LoadedModule[162]=C:\Windows\SYSTEM32\WINSTA.dll
LoadedModule[163]=C:\Windows\SYSTEM32\powrprof.dll
LoadedModule[164]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\PresentationFramework-SystemXmlLinq.dll
LoadedModule[165]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.Xml.Linq.dll
LoadedModule[166]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\PresentationFramework-SystemXml.dll
LoadedModule[167]=C:\Windows\system32\msctfui.dll
LoadedModule[168]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\UIAutomationProvider.dll
LoadedModule[169]=C:\Windows\SYSTEM32\UIAutomationCore.dll
LoadedModule[170]=C:\Windows\SYSTEM32\ntmarta.dll
LoadedModule[171]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.IO.Compression.dll
LoadedModule[172]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\clrcompression.dll
LoadedModule[173]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.Reflection.Emit.Lightweight.dll
LoadedModule[174]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\WindowsFormsIntegration.dll
LoadedModule[175]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.Windows.Controls.Ribbon.dll
LoadedModule[176]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.Resources.ResourceManager.dll
LoadedModule[177]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.IO.FileSystem.Watcher.dll
LoadedModule[178]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.Threading.Overlapped.dll
LoadedModule[179]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.Net.Security.dll
LoadedModule[180]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.Security.Cryptography.X509Certificates.dll
LoadedModule[181]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.Runtime.Caching.dll
LoadedModule[182]=C:\Windows\SYSTEM32\winhttp.dll
LoadedModule[183]=C:\Windows\SYSTEM32\ondemandconnroutehelper.dll
LoadedModule[184]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.Net.ServicePoint.dll
LoadedModule[185]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.Net.Sockets.dll
LoadedModule[186]=C:\Windows\System32\rasadhlp.dll
LoadedModule[187]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\PresentationFramework-SystemCore.dll
LoadedModule[188]=C:\Windows\SYSTEM32\PROPSYS.dll
LoadedModule[189]=C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.9600.19394_none_62486577ecb635cf\comctl32.dll
LoadedModule[190]=C:\Windows\System32\thumbcache.dll
LoadedModule[191]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.Drawing.Common.dll
LoadedModule[192]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.Drawing.Primitives.dll
LoadedModule[193]=C:\Windows\System32\fwpuclnt.dll
LoadedModule[194]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.Security.Principal.Windows.dll
LoadedModule[195]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.Security.Claims.dll
LoadedModule[196]=C:\Windows\system32\schannel.DLL
LoadedModule[197]=C:\Windows\system32\CRYPT32.dll
LoadedModule[198]=C:\Windows\system32\MSASN1.dll
LoadedModule[199]=C:\Windows\system32\Normaliz.dll
LoadedModule[200]=C:\Windows\SYSTEM32\ncrypt.dll
LoadedModule[201]=C:\Windows\SYSTEM32\NTASN1.dll
LoadedModule[202]=C:\Windows\system32\ncryptsslp.dll
LoadedModule[203]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.Security.Cryptography.Encoding.dll
LoadedModule[204]=C:\Windows\SYSTEM32\gpapi.dll
LoadedModule[205]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.Diagnostics.StackTrace.dll
LoadedModule[206]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\Microsoft.DiaSymReader.Native.amd64.dll
LoadedModule[207]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\api-ms-win-crt-environment-l1-1-0.dll
LoadedModule[208]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\api-ms-win-crt-multibyte-l1-1-0.dll
LoadedModule[209]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.Reflection.Metadata.dll
LoadedModule[210]=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\System.Collections.Immutable.dll
FriendlyEventName=Stopped working
ConsentKey=APPCRASH
AppName=NuGetPackageExplorer
AppPath=C:\ProgramData\chocolatey\lib\NugetPackageExplorer\tools\NugetPackageExplorer.exe
NsPartner=windows
NsGroup=windows8
ApplicationIdentity=960CB2CBE4F050E3C159F01E3E1E0892
`

I hope this is what you need. I'm going to try the 3rd option from error message window...
- Trying debugging: "MSG: An unhandled win32 exception has occurred in NPE.."
- `Unhandled exception at 0x00007FFED1447AFC (KernelBase.dll) in NuGetPackageExplorer.exe: 0xE0434352 (parameters: 0xFFFFFFFF8007000E, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x00007FFEA7970000).`

It's been more of an annoyance then anything else at this time... It would be nice if NPE didn't crash for me. I've simply unzipped them and rebuilt without the icon link, then they work for our repo (& don't crash NPE). From there I can deploy throughout the undergraduate labs, using Puppet to direct Chocolatey to install all our apps :).

Regards

**Comment by svick** [comment]
@trekytech7 Sorry, that still doesn't show the exception message or the stack trace. I'm not sure if this is the easiest way to get the information, but can you open Event Viewer, go to Windows Logs → Application and look for a .NET Runtime error?

**Comment by trekytech7** [comment]
@svick The only thing that shows in the logs is an information line next: (I don't see any .NET runtime error)

Info Log: `Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: NugetPackageExplorer.exe
P2: 5.7.113.57457
P3: 5eda9993
P4: KERNELBASE.dll
P5: 6.3.9600.19724
P6: 5ec5262a
P7: e0434352
P8: 0000000000007afc
P9: 
P10: 

Attached files:

These files may be available here:
C:\Users\eceadmin\AppData\Local\Microsoft\Windows\WER\ReportArchive\AppCrash_NugetPackageExpl_2525b9f4c75f6151342c9fec64d54021e38d73a7_a41abb8d_1d242320

Analysis symbol: 
Rechecking for solution: 0
Report Id: 64b20c96-d0f6-11ea-813f-c8eb68e53c5b
Report Status: 2048
Hashed bucket: 
`
Screenshot of the crash:
<img width="740" alt="NPEcrash-issue 2020-07-29" src="https://user-images.githubusercontent.com/12401756/88825918-5da26200-d185-11ea-8790-5b3d5a4ec6be.png">

**Comment by clairernovotny** [comment]
I wonder if this is #1105. Please try the latest nightly version and reopen if it's still happening.
