### ISSUE TITLE
shim for createdump is created when installed via chocolatey

### ISSUE THREAD

**Issue by batzen** [NuGetPackageExplorer/NuGetPackageExplorer#1039]
**Type** (choose one):

- Bug

**NPE version**: 5.7.75

**OS version**: Windows 10 - 2004

**Installed from**: Chocolatey.org

In case of a BUG:

- What is the current result?
Chocolatey creates a shim for `createdump.exe` because there is no `ignore` file beside that particular exe.

- What is the expected result?
No shim is created by chocolatey as `createdump.exe` belongs to the .NET core runtime.

- Are there any workarounds? 
yes (deleting the shim manually, but it gets added again after an update/upgrade)

- Is there a version in which it did work? 
don't know/didn't check

- Is there a package on Nuget.org which shows the bug? 
no

Having a second look at the package being published to chocolatey i noticed that there is no "tools" directory, but all files are placed at the root of the package instead.
This does not feel right as it clutters the package directory and causes a mixture of chocolatey metadata files and the actual application in the same folder.
Maybe this should also be changed. ;-)

And thanks a lot for creating and maintaining this project. It makes authoring/checking packages, whether it's for nuget or chocolatey, so much easier.

If you agree with my bug report and my suggested changes, but don't want to invest the time to make the changes yourself i would be happy to create one or multiple PRs containing those changes.

**Comment by clairernovotny** [comment]
Happy to accept a PR to clean up the Chocolatey package.
