### ISSUE TITLE
Invalid feeds are remembered

### ISSUE THREAD

**Issue by clairernovotny** [NuGetPackageExplorer/NuGetPackageExplorer#1042]
If someone enters an invalid feed, we remember it in the list anyway. We should also have a way to clear out other feeds from the list.

![image](https://user-images.githubusercontent.com/1427284/85482458-1c6cd000-b591-11ea-8ab9-bb4dc9983712.png)

**Comment by campersau** [comment]
The code [currently expects that an exception is thrown in `LoadPackages` / `LoadMore` when the feed is invalid](https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/432a1a5cc81527d14cc0e9a142d9ace324800eee/PackageViewModel/PackageChooser/PackageChooserViewModel.cs#L385-L386), but exceptions are [currently already handled there](https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/432a1a5cc81527d14cc0e9a142d9ace324800eee/PackageViewModel/PackageChooser/PackageChooserViewModel.cs#L315-L328).

See your commit:  https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/commit/db4f96c061c443107e0e927477a15fb37324ed7b
