### ISSUE TITLE
Problem with automatic account login

### ISSUE THREAD

**Issue by thomasesz** [NuGetPackageExplorer/NuGetPackageExplorer#1045]
Type: Question
NPE version: 5.7.73 
OS version: Windows 10 - 2004
Installed from: Microsoft Store

Hello, I have the following problem:
If I want to open a package from our company from the online feed, I had to log in with my microsoft account.
The problem is that I accidentally entered the account of the previous company (takeover) and activated the "stay logged in" checkbox. Now there is no way to enter another account.

To avoid this, i changed the password of the old account so that i could choose another account again. However, only the message always comes:
> _Unable to load the service index for source ........_

is this a bug or have I not considered something?

Please support, thanks in advance!
Thomas

**Comment by campersau** [comment]
This is currently by design when the "stay logged in" checkbox is checked. You can try to remove the credentials from the Windows Credential Manager: https://support.microsoft.com/en-us/help/4026814/windows-accessing-credential-manager

**Comment by thomasesz** [comment]
Damn, great thanks! I never needed that in 15 years, interesting, learned something again, haha
