### ISSUE TITLE
无法启用应用程序

### ISSUE THREAD

**Issue by ropean** [NuGetPackageExplorer/NuGetPackageExplorer#107]
平台版本信息
	Windows 			: 6.1.7601.65536 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.6.1055.0 built by: NETFXREL2
	clr.dll 			: 4.6.1055.0 built by: NETFXREL2
	dfdll.dll 			: 4.6.1055.0 built by: NETFXREL2
	dfshim.dll 			: 4.0.31106.0 (Main.031106-0000)

源
	部署 URL			: file:///D:/Chrome/NuGetPackageExplorer.application
	部署提供方 URL		: https://npe.codeplex.com/releases/clickonce/NuGetPackageExplorer.application
						服务器		: Microsoft-IIS/8.0,CDS01
						X-Powered-By	: ASP.NET
						X-AspNet-Version: 4.0.30319
	应用程序 URL			: https://npe.codeplex.com/releases/clickonce/Application%20Files/NuGetPackageExplorer_3_16_0_0/NuGetPackageExplorer.exe.manifest
						服务器		: Microsoft-IIS/8.0,CDS01
						X-Powered-By	: ASP.NET
						X-AspNet-Version: 4.0.30319

标识
	部署标识		: NuGetPackageExplorer.application, Version=3.16.0.0, Culture=neutral, PublicKeyToken=0000000000000000, processorArchitecture=x86
	应用程序标识		: NuGetPackageExplorer.exe, Version=3.16.0.0, Culture=neutral, PublicKeyToken=0000000000000000, processorArchitecture=x86, type=win32

应用程序摘要
	* 可安装的应用程序。
	* 设置信任 URL 参数。
错误摘要
	以下是错误摘要，这些错误的详细信息列在该日志的后面。
	* 激活 D:\Chrome\NuGetPackageExplorer.application 导致异常。 检测到下列失败消息:
		+ 下载 https://npe.codeplex.com/releases/clickonce/Application Files/NuGetPackageExplorer_3_16_0_0/NuGetPackageExplorer.exe.config.deploy 未成功。
		+ 远程服务器返回错误: (500) 内部服务器错误。

组件存储事务失败摘要
	未检测到任何事务错误。

警告
	* 此应用程序清单无签名。签名验证将被忽略。
	* 此应用程序清单无签名。签名验证将被忽略。
	* 此应用程序清单无签名。签名验证将被忽略。

操作进度状态
	* [2016-05-31 15:29:10] : 已启动 D:\Chrome\NuGetPackageExplorer.application 的激活过程。
	* [2016-05-31 15:29:10] : 部署清单处理已成功完成。
	* [2016-05-31 15:29:10] : 已启动应用程序的安装过程。
	* [2016-05-31 15:29:11] : 应用程序清单处理已成功完成。
	* [2016-05-31 15:29:15] : 已找到兼容运行时版本 4.0.30319。
	* [2016-05-31 15:29:15] : 信任请求和平台检测已完成。

错误详细信息
	执行此操作期间检测到下列错误。
	* [2016-05-31 15:29:47] System.Deployment.Application.DeploymentDownloadException (未知子类型)
		- 下载 https://npe.codeplex.com/releases/clickonce/Application Files/NuGetPackageExplorer_3_16_0_0/NuGetPackageExplorer.exe.config.deploy 未成功。
		- 源: System.Deployment
		- 堆栈跟踪:
			在 System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
			在 System.Deployment.Application.SystemNetDownloader.DownloadAllFiles()
			在 System.Deployment.Application.FileDownloader.Download(SubscriptionState subState)
			在 System.Deployment.Application.DownloadManager.DownloadDependencies(SubscriptionState subState, AssemblyManifest deployManifest, AssemblyManifest appManifest, Uri sourceUriBase, String targetDirectory, String group, IDownloadNotification notification, DownloadOptions options)
			在 System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
			在 System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			在 System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			在 System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- 内部异常 ---
		System.Net.WebException
		- 远程服务器返回错误: (500) 内部服务器错误。
		- 源: System
		- 堆栈跟踪:
			在 System.Net.HttpWebRequest.GetResponse()
			在 System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)

组件存储事务详细信息
	没有可用的事务信息。

**Comment by 304NotModified** [comment]
title: Unable to start the application

Version Information
Windows : 6.1.7601.65536 (Win32NT)
Common Language Runtime : 4.0.30319.42000
System.Deployment.dll : 4.6.1055.0 built by: NETFXREL2
clr.dll : 4.6.1055.0 built by: NETFXREL2
dfdll.dll : 4.6.1055.0 built by: NETFXREL2
dfshim.dll : 4.0.31106.0 (Main.031106-0000)
source

**Comment by 304NotModified** [comment]
If you take the effort to translate this for us, I will check this issue
