### ISSUE TITLE
Question - Getting multiple errors while creating a Nuget Package from the most basic 'Hello World' Console app

### ISSUE THREAD

**Issue by clauderoy790** [NuGetPackageExplorer/NuGetPackageExplorer#1076]
Question - Getting multiple errors while creating a Nuget Package from the most basic 'Hello World' Console app

OS Version: Windows 10 Home
NPE Version: 5.7.113
Downloaded from: Microsoft Store (Same date as this post)

I created a super basic "Hello World" console app to test Squirrel and I'm having trouble. I get an error in the Package Explorer that says: Missing Source Link for: lib\net45\NuGet.Squirell.dll, Splat, etc.(See screenshot blow) It also says Missing Symbols. I can still create the setup with the command properly but when I click the Installer, it starts but exits immediately.

I'm running on VS Community 2019, not sure if that changes anything.

**So far I've tried:** 
- Setting the -deterministic flag in the build section of the project settings
- Making sure that my project target is actually set to 4.5
- Making sure that the AssemblyVersion is the same as the package version
Going in Tools - Options - Debugging ->
- disabling/enabling Just my code. 
- Enabling source server support. 
- Enabling source link support
- Checking/Unchecking Auto-Generate binding redirects in the project properties.
- Creating the most possible basic console app, with only one exe, one exe.config and one .pdb
- Adding/Removing .pdb files from my package

I'm looking into it, I'll get it fixed for sure and put the solution here, I'm sure I'm not the only one with the issue. 

Thanks for your help and have an outstanding day!

**Comment by clairernovotny** [comment]
Hi @clauderoy790 - the health checks are meant to validate "normal" NuGet packages: libraries and .NET Core CLI tools. It won't be able to validate packages that have other assets in it unless debug symbols are available.
