### ISSUE TITLE
Can't install from Windows Store

### ISSUE THREAD

**Issue by ridomin** [NuGetPackageExplorer/NuGetPackageExplorer#1083]
**OS version**: Microsoft Windows [Version 10.0.19041.388]
**Not  Installed from**: Microsoft Store 

I tried to install from the store and got `Code: 0x80070005`

![image](https://user-images.githubusercontent.com/1918324/89201992-29ed8080-d567-11ea-8d87-6af96806d722.png)

Other applications install fine, I've installed all updates, reboot, take latest updates.. same error.

**Comment by clairernovotny** [comment]
You need to take this up with the Store team; there is nothing we can do here.
