### ISSUE TITLE
Unlist previous versions checkbox at publish

### ISSUE THREAD

**Issue by birbilis** [NuGetPackageExplorer/NuGetPackageExplorer#109]
Hi! Thanks for reporting this feature/bug/question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

**Type** (choose one):
Feature request

**NPE version**:
3.16

**Installed from**:
ClickOnce 

in case of a FEATURE REQUEST:
- Why do we need it?

everytime I push a new version for a package that I want to have only one version listed, I have to log in and unlist older versions
- Please provide an use case.

at Trafilm.Metadata package (built from http://github.com/zoomicon/Trafilm.Metadata), I want only the latest one to be listed since it reflects the latest version of metadata that are visualized at http://gallery.trafilm.net

**Comment by 304NotModified** [comment]
I like this feature, but more bugs/features has more prio (like proper NuGet 3 support). 

PR on this is accepted

**Comment by legnars** [comment]
I would love to help with this issue.

I imagine it is as simple as adding a new checkbox to PublishPackageWindow.xml with proper bindings and then, if checked, use the same DELETE method as the "PublishAsUnlisted" while looping through all previous versions (I would need to build a GET method in the GalleryServer class? Maybe there is already one available) of the package (or maybe I can even send one big API request for DELETE, if that is possible).

This would be my first public contribution to an open-source package, any insights to spare?

**Comment by 304NotModified** [comment]
This issue is open for a while and we think that this feature isn't really a feature an improvement. 

After new insights, this feature is more an anti-pattern IMO. Maybe there are cases where this really needed, but still we don't think we should make this pattern easy or "recommend"
