### ISSUE TITLE
3.17 unable to publish package.

### ISSUE THREAD

**Issue by kevinhardytopssoft** [NuGetPackageExplorer/NuGetPackageExplorer#112]
Hi! Thanks for reporting this feature/bug/question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

**Type** (choose one):

**- Bug**

NPE version: **3.17**

Installed from: **ClickOnce** / chocolatey.org / Zip on CodePlex 

In case of a BUG:

- What is the current result?
- **after installing version 3.17, i opened an older package (using v3.14) and after making changes, attempted to publish to our internal Nuget server. the publish failed.  also of note: when another developer using v3.14 attempted to open the package, they recieved an exception - we didnt capture the details, but it was in reference to an XML node (problem reading / didn not exist / unexpected value / etc)**
- What is the expected result?
- **the publish should succeed**
- Please post full exception details in case of an Exception (message, stacktrace, inner exceptions)
- **Internal Server Error**
- Are there any work arrounds? yes/no
- **have another developer on v3.14 do the publish**
- Is there a version in which it did worked? 
- **v3.14**
- Is there a package on Nuget.org which shows the bug?
- **no**

in case of a FEATURE REQUEST:
 
 - Why do we need it?
 - **ensure backwards compatibility**
 - Please provide an use case.

**Comment by 304NotModified** [comment]
Please capture the exception.

**Comment by kevinhardytopssoft** [comment]
I have included a screenshot with 2 images – one of the error when attempting to publish the v3.17 package, and the other of another user attempting to open the v3.17 package with v.314 of Nuget Package Explorer

-Kevin

**Comment by 304NotModified** [comment]
Maybe because I'm on mobile, but i don't see the attachments. 

Is is possible to test with 3.16?

**Comment by kevinhardytopssoft** [comment]
Hey Julian,

I can five that a try tomorrow - maybe the attachment got stripped ?

If you'd like to send me another email o could try the attachment again

Kevin

Sent from my iPhone

On Jun 13, 2016, at 5:34 PM, Julian Verdurmen <notifications@github.com<mailto:notifications@github.com>> wrote:


Maybe because I'm on mobile, but i don't see the attachments.

Is is possible to test with 3.16?

-

**Comment by 304NotModified** [comment]
See #114

**Comment by 304NotModified** [comment]
This should be fixed in 3.18. If not, please let me know.
