### ISSUE TITLE
$configuration$ token not supported

### ISSUE THREAD

**Issue by ravensorb** [NuGetPackageExplorer/NuGetPackageExplorer#113]
Hi! Thanks for reporting this feature/bug/question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

**Type** (choose one):
- Feature request/Bug

**NPE version**: 3.17

**Installed from**: chocolatey.org 

In case of a BUG:
- What is the current result?
  Cannot open nuspec file that uses tokens in paths (ex: $configuration$)
- What is the expected result?
  nuspec file should open correctly and ideally prompt for token values
- Please post full exception details in case of an Exception (message, stacktrace, inner exceptions)
- Are there any work arrounds? yes - edit nuspec file and remove token (not ideal)
- Is there a version in which it did worked? no 
- Is there a package on Nuget.org which shows the bug?

in case of a FEATURE REQUEST:
- Why do we need it?
  nuspec files are being used for more and more applications and frameworks.  As they become part of the standard deployment process it is necessary to support the ability to leverage most of the features supplied by nuget -- in this case the ability to use a single nuspec file to generate a package with either release or debug assemblies

**Comment by 304NotModified** [comment]
Do you have an example nuspec or package?

There is a change this has been fixed in 3.20

**Comment by onovotny** [comment]
Closing as this issue is old. If this is still an issue, please re-open.
