### ISSUE TITLE
metadata element has invalid child serviceable?

### ISSUE THREAD

**Issue by yuominae** [NuGetPackageExplorer/NuGetPackageExplorer#114]
![nuget error](https://cloud.githubusercontent.com/assets/13581691/16201927/d4e7f2fa-3713-11e6-8337-dfbcfafd66ca.PNG)

Hi,

I just had an update of my NuGet Package Explorer.
Now I get an error when I try to publish, saying:

The element 'metadata' in namespace 'http://schemas,microsoft.com/packaging/2011/08/nuspec.xsd' has invalid child element 'serviceable' in namespace 'http://schemas.microsoft.com/packaging/2011/08/nuspec.xsd'. List of possible elements expected. etc...

I didn't have this problem when I used the package explorer this morning.

I have tried removing the serviceable tag in Edit Metadata Source mode, but it gets added back in automatically and I can't publish.

I had a look at Google for a fix, but couldn't find anything. What am I doing wrong?

Thanks,

David

**Comment by yuominae** [comment]
Tried uninstalling and reinstalling, but no change.

**Comment by 304NotModified** [comment]
Hi, this bug has been introduced in the latest version. On holiday now but will fix this after it.

**Comment by elutsky** [comment]
Same happens to me for several days - I am uploading the package manually to internal nuget server (via UI page).
It was work (and seems to keep working) for packages built on version 3.16.
After update to version 3.17, even with just-version-changed change I cannot upload the package. It failed with "Failed to read the package file." error
It's too critical for us, some devs are not able to upload package.
Where can we take the prev version to verify?
Thanks!

**Comment by 304NotModified** [comment]
For the clickonce it isn't possible to downgrade AFAIK.  

The bug is probably introduced with https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/pull/111

**Comment by nbhuy89** [comment]
I've just backed to previous stable version, from Add/Remove Programs, 3.15.0.0, and it works fine
This is work-arround for those who got this issue.

**Comment by yuominae** [comment]
304NotModiied thank for confirming. I'll be waiting for the update, since after the reinstall I don't have the option to downgrade anymore.

**Comment by elutsky** [comment]
As @nbhuy89 suggested, Did perform rollback from Add/REmove programs:

- Right Click on nuget explorer
- Click Uninstall/Change menu
- Choose "Restore the app to latest stable version".

This did rollback to version 3.15, and I was able to upload the package.

**Comment by 304NotModified** [comment]
Thanks for the confirmation! Next week I'm  back from holiday and have then more than a mobile :)

**Comment by yuominae** [comment]
Thanks for that!
Since I foolishly uninstalled version 3.17 and then reinstalled to see if that might fix the issue, I am now unable to rollback to a previous version. Until this is fixed, is there somewhere I can download the installer for version 3.16?

**Comment by 304NotModified** [comment]
Only on chocolatey (but it's living aside of the clickonce), with clickonce you can't revert AFAIK

**Comment by 304NotModified** [comment]
This should be fixed in 3.18. If not, please let me know.

**Comment by nbhuy89** [comment]
@304NotModified I tried, it works, thanks

**Comment by 304NotModified** [comment]
Thanks for the confirmation!
