### ISSUE TITLE
Failed to read the package file. Ensure it is a valid NuGet package with a valid manifest.

### ISSUE THREAD

**Issue by nbhuy89** [NuGetPackageExplorer/NuGetPackageExplorer#115]
Hi,
I have just updated latest version,
I got this problem when upload package to nuget server

"Failed to read the package file. Ensure it is a valid NuGet package with a valid manifest."

My nuget server version: 3.0

When i back to previous version (3.15.0.0) and open created package by version (3.17.0.0) then got below error:
![image](https://cloud.githubusercontent.com/assets/1560067/16218090/07f03a64-37a4-11e6-9d52-beecd38d0404.png)

Thanks,

**Comment by 304NotModified** [comment]
See #114

**Comment by 304NotModified** [comment]
This should be fixed in 3.18. If not, please let me know.
