### ISSUE TITLE
Question: Caching/remembering PAT

### ISSUE THREAD

**Issue by vatsan-madhavan** [NuGetPackageExplorer/NuGetPackageExplorer#1158]
### Question
<<*I'm not sure whether this is a question or a feature request, so I'll start this out as a question.*>>

**NPE version**:  X64 - (5.8.17+d79daf6700)
**OS version**: Windows 10 2004 Windows Insider Build 20246.1
**Installed from**: Chocolatey.org

I access an Azure DevOps feed that requires PAT based authentication, and NPE suggests helpfully brings up Windows Security dialog and asks for the PAT. 

![image](https://user-images.githubusercontent.com/20246435/98284929-ad4bb300-1f56-11eb-976f-66937b2f9a1d.png)

This happens every time I want to access this feed, and I end up having to either look-up PAT from a key-vault, or create a short-term-use PAT, every time I launch NPE (for use against this feed).

Is there a smarter way to handle this situation that would allow me to cache my credentials on a trusted machine (for e.g., on my home or work PC) that's always in a secure location (and has encrypted drives etc.) so that I needn't bother with the whole 1.5 minutes of rituals that go with PAT-acquisition/retrieval each time I run into this scenario ?

**Comment by campersau** [comment]
Does "Remember me" not work?
You can put the PAT as `packageSourceCredentials` in the `%APPDATA%\NuGet\NuGet.Config` file.
See https://docs.microsoft.com/azure/devops/artifacts/nuget/nuget-exe?view=azure-devops#add-a-feed-to-nuget-482-or-later
https://docs.microsoft.com/nuget/reference/nuget-config-file#packagesourcecredentials

**Comment by vatsan-madhavan** [comment]
That worked nicely - thank you!
