### ISSUE TITLE
Unable to push .snupkg package

### ISSUE THREAD

**Issue by aybe** [NuGetPackageExplorer/NuGetPackageExplorer#1177]
**Type** (choose one):

- Bug

**NPE version**: (e.g. 5.x) (see Help -> about)
![NuGetPackageExplorer_2020-11-19_22-14-54](https://user-images.githubusercontent.com/1537591/99724948-aecbbe00-2ab4-11eb-90d0-d421487a5c38.png)

**Installed from**: Microsoft Store

**OS version**: (Windows 7, 10 - 1803/17134, etc)
![winver_2020-11-19_22-15-20](https://user-images.githubusercontent.com/1537591/99724981-bbe8ad00-2ab4-11eb-8503-ddafea4b8cf9.png)

I am unable to push a .snupkg package, this is the error:

![NuGetPackageExplorer_2020-11-19_22-16-26](https://user-images.githubusercontent.com/1537591/99725126-ed617880-2ab4-11eb-977b-7ecc5ed64f7c.png)

Thanks !!!

**Comment by Zastai** [comment]
A .snupkg is normally pushed automatically along with the .nupkg _when using a v3 feed_.

Here, you are explicitly using a v2 feed, which only handles `.symbols.nupkg`. If you set the Publish Url to `https://api.nuget.org/v3/index.json` it should work.

Note that the error explicitly says you need V3 and provides a link to the documentation specifying the same.

**Comment by aybe** [comment]
Thank you!

**Comment by GF-Huang** [comment]
How can I confirm that the `.snupkg` really pushed with `.nupkg` together?

**Comment by Zastai** [comment]
On nuget.org, packages with symbols offer a download link for them:

![image](https://user-images.githubusercontent.com/13708975/107409229-3b15dc00-6b0c-11eb-85b1-508bb09e735a.png)

**Comment by GF-Huang** [comment]
![image](https://user-images.githubusercontent.com/4510984/107409696-679b1980-6b47-11eb-9bb7-159b75b9acfd.png)

So this is failed?

**Comment by GF-Huang** [comment]
> On nuget.org, packages with symbols offer a download link for them:
> 
> ![image](https://user-images.githubusercontent.com/13708975/107409229-3b15dc00-6b0c-11eb-85b1-508bb09e735a.png)

Which page?

**Comment by GF-Huang** [comment]
So I'm facing same issue. The `.nupkg` published success, but `.snupkg` not.

![image](https://user-images.githubusercontent.com/4510984/107410037-bf398500-6b47-11eb-9d08-04eb13ef734c.png)

**Comment by GF-Huang** [comment]
This issue should reopen.

**Comment by GF-Huang** [comment]
Any news?
