### ISSUE TITLE
Folder runtimes not shown in Package contents for runtime.ubuntu.14.04-x64.Microsoft.NETCore.TestHost

### ISSUE THREAD

**Issue by svick** [NuGetPackageExplorer/NuGetPackageExplorer#119]
**Type**: Bug

**NPE version**: 3.18.0.0

**Installed from**: ClickOnce

When you open the `runtime.ubuntu.14.04-x64.Microsoft.NETCore.TestHost` (version 1.0.0) package from NuGet, Package contents show files from the package root, but they do not show the `runtimes\ubuntu.14.04-x64\native\corerun` file, or any of its parent folders.

For the very similar package `runtime.win7-x64.Microsoft.NETCore.TestHost`, the file `runtimes\win7-x64\native\CoreRun.exe` is shown correctly.

**Comment by svick** [comment]
This happens because the `[Content_Files].xml` file for that package does not contain an element for the `corerun` file, which it has for all files without extensions.

**Comment by 304NotModified** [comment]
Thanks for the info.  Support for the runtimes isn't build yet.

**Comment by svick** [comment]
Turns out this was already reported in https://github.com/NuGet/Home/issues/2936 and fixed in https://github.com/NuGet/NuGet.Client/pull/666 (though the fix is not on NuGet yet).

**Comment by 304NotModified** [comment]
Thanks for the links!
