### ISSUE TITLE
Source Link mappings with `*` in the middle are not interpreted correctly

### ISSUE THREAD

**Issue by tmat** [NuGetPackageExplorer/NuGetPackageExplorer#1201]
**Type** (choose one):

- Bug

In case of a BUG:

See https://github.com/dotnet/sourcelink/issues/581 for details.

**Comment by tmat** [comment]
@clairernovotny FYI

**Comment by clairernovotny** [comment]
Is there a repro package I can try?

**Comment by mjirhage** [comment]
I have updated NuGet Package Explorer to the latest version (5.10.43) and this issue has now been resolved. I don't know if that is enough for you, but it works on my machine. 😄
