### ISSUE TITLE
[Feature] Commandline report on package health and analyze results

### ISSUE THREAD

**Issue by quasarea** [NuGetPackageExplorer/NuGetPackageExplorer#1207]
- Feature request
Be able to get results of health check and package analyse via commandline 

- Why do we need it?
To provide means for showing package quality in devops pipelines

- Please provide an use case.
So I can automatically add pull request comment that package assemblies are non deterministic and located outside known folders

**Comment by clairernovotny** [comment]
@0xced seems to be working on it https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/pull/1010 but I'm not sure what the status is?

I would like this as well.

**Comment by 0xced** [comment]
I still have a lot of duplicated code that I want to deduplicate before turning the draft pull request into a final pull request. Not sure when I'll get there though…

**Comment by clairernovotny** [comment]
Is this something someone else could finish up? What code is duplicated and what still needs to be done?

**Comment by quasarea** [comment]
could output report in a sarif (json) format, so it stays inline with other tools like devskim, binskim, etc.
