### ISSUE TITLE
Trying to open a .nupkg from a readonly-share gives the error Access to the path '...' is denied.

### ISSUE THREAD

**Issue by sea1jxr** [NuGetPackageExplorer/NuGetPackageExplorer#121]
- Bug
  NPE version**: 3.18

Installed from**: ClickOnce

Trying to open a .nupkg from a readonly-share gives the error

---
## OK   

version 3.13 on another machine is able to open the same package.

The workaround is copy the file locally, and it will open.

**Comment by 304NotModified** [comment]
Thanks for the report. This is also with readonly files.

This bug has been fixed and will be published with 3.21
