### ISSUE TITLE
ESET virus warning on latest Windows Store install

### ISSUE THREAD

**Issue by zpqrtbnk** [NuGetPackageExplorer/NuGetPackageExplorer#1218]
**Type** (choose one): BUG

**NPE version**: 5.9.6.0

**OS version**: Win 10 PRO

**Installed from**: Microsoft Store

Expected result: installs

Result: 

![image](https://user-images.githubusercontent.com/2846429/105850158-a6768e80-5fe1-11eb-96ed-cb2a415dbe5c.png)

File flagged threat and removed by Nod32. Not sure whether it's a Nod32, Windows Store or NuGet Explorer issue... but it does not work :(

**Comment by Achilles1515** [comment]
Also ran into this.

**Comment by dcasbonne** [comment]
I also have that warning but have installed this version last week... I'm a little nervous about what could have been stolen on my computer... Hope you could gives us a quick answer and a patch !

**Comment by clairernovotny** [comment]
This is a false warning, there are no known issues with the build. You should take this up with ESET.

It was built off of a clean Azure Pipelines image and you can see the full build logs here: https://dev.azure.com/clairernovotny/GitBuilds/_build/results?buildId=4627&view=logs&j=7f26e242-37dd-54e5-0a5f-18e48675e086, and you can download the artifacts that include the full binlog.

**Comment by clairernovotny** [comment]
This is likely a false warning, there are no known issues with the build. 

It was built off of a clean Azure Pipelines image and you can see the full build logs here: https://dev.azure.com/clairernovotny/GitBuilds/_build/results?buildId=4627&view=logs&j=7f26e242-37dd-54e5-0a5f-18e48675e086, and you can download the artifacts that include the full binlog.

**Comment by rmc47** [comment]
We've seen similar, more broadly affecting .NET 5.0 apphost-generated files.

It looks like the latest set of ESET definitions fixes it.

**Comment by zpqrtbnk** [comment]
Just to confirm that with latest ESET definitions, then un-installing and re-installing via Windows Store, the warning is done and everything works. Closing the issue.
