### ISSUE TITLE
Add support to load VSTS packages

### ISSUE THREAD

**Issue by GutierrezDev** [NuGetPackageExplorer/NuGetPackageExplorer#122]
Hi! Thanks for reporting this feature/bug/question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

**Type** (choose one):
- Feature request

**NPE version**: (e.g. 3.18) 

**Installed from**: ClickOnce

in case of a FEATURE REQUEST:
- Why do we need it?
  Visual Studio Team Services  (VSTS) offers a new way to manage private packages. Right now our only way to push package is command line. NPE is super nice with Private Server (at least what I tested) and API Key, but when I use VSTS package management NPE says: An error ocurred while processing this request. The remote server returned status code 401.

**Comment by Allann** [comment]
We are also using VSTS to host our private packages, so would appreciate this feature.

**Comment by Adiel-Sharabi** [comment]
1+

**Comment by 304NotModified** [comment]
Isn't the issue here that basic authentication is needed? See #48

**Comment by 304NotModified** [comment]
We need more info before implenting this

**Comment by Allann** [comment]
Instead of Push, the recommended way from NuGet is Add.  see https://docs.nuget.org/ndocs/tools/nuget.exe-cli-reference#add

I have created a powershell script that performs this action now for us, so not a big deal, but since there is a publish which hardcodes the action, should there be an Add as well?  Or should the action be set via a option on the existing task?

**Comment by dragon788** [comment]
It appears Microsoft were going to update the documentation on VSTS to show that you need to use a Personal Token rather than basic authentication. This should work for a push according to https://www.visualstudio.com/en-us/docs/build/steps/package/nuget-packager#publish-to-visual-studio-team-services .

**Comment by oberdannunes** [comment]
+1 :)

**Comment by pierrejochem** [comment]
👍

**Comment by BerendWouters** [comment]
We'd love to see this implementation too.

**Comment by dvernole** [comment]
+1

**Comment by ynijs** [comment]
Struggling here as well.
We were able to add basic authentication in the code, as a test, but the way the packages are exposed in VSTS seems not to be compatible with how the queries are written.
If you look in fiddler, you'll get the following result (which, after authentication, returns a 404)
{"count":1,"value":{"Message":"No HTTP resource was found that matches the request URI 'https://xxxx.pkgs.visualstudio.com/_packaging/test/nuget/v3/Packages()?$skip=0&$top=15&$select=Id,Version,Authors,DownloadCount,VersionDownloadCount,PackageHash,PackageSize,Published'."}}

Problem is those () at the end of Packages. It breaks into a 404. I dug into the code to see if there's an easy way to fix that, but I was unable to find a fix ...

**Comment by 304NotModified** [comment]
> Problem is those () at the end of Packages. It breaks into a 404. I dug into the code to see if there's an easy way to fix that, but I was unable to find a fix ...

So in summary, the `()` needs to be removed from the URL in NPE?

**Comment by ynijs** [comment]
That's what I think. Haven't been able to get any further. Also went down the route to see if I could use the REST api by creating a class that implements IPackageRepository, and using the Linq2Rest package but it yields an invalid argument count exception. Would want to rule out the std solution of removing the () before I go down the route of linq2rest again...

**Comment by 304NotModified** [comment]
What was the action you were doing ? (reading packages, publish?)

**Comment by ynijs** [comment]
Reading, was trying to configure a vsts package feed in NPE to list the published packages

**Comment by 304NotModified** [comment]
OK, will try to look at it this weekend.

**Comment by SotiriosMitsis** [comment]
We need that as well, so yet another +1 :) 

Any progress or ETA on this?

**Comment by 304NotModified** [comment]
Unfortunately I'm too busy the next weeks

**Comment by ironicnet** [comment]
Added the PR #256  for publishing using authentication. 
Maybe we could have some kind of configuration per Feed? That way we could centralize that configuration there.

**Comment by siblight** [comment]
Being able to connect to a VSTS feed would be very useful 👍 .

Is there any progress on being able to achieve this?

**Comment by 304NotModified** [comment]
> Maybe we could have some kind of configuration per Feed? That way we could centralize that configuration there.

Do you mean to store config persistent in NPE? Maybe we should create a new github issue for that. 

> Is there any progress on being able to achieve this?

PR has been reviewed. I think it could be in the next release (6.0)

**Comment by ironicnet** [comment]
@304NotModified I just created an issue for the configuration per feed (#259 )

**Comment by onovotny** [comment]
https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/pull/256 added the ability to use a PAT for VSTS. The latest CI builds have this merged in and it'll be in the next release.
