### ISSUE TITLE
Warning about not reproducible Compiler Flags

### ISSUE THREAD

**Issue by axunonb** [NuGetPackageExplorer/NuGetPackageExplorer#1257]
**Type** (choose one):

- Question

**NPE version**:
NuGet Package Explorer - Store - X64 - (5.9.90+7df8b05402)

**OS version**: (Windows 7, 10 - 1803/17134, etc)
10.0.19042 Build 19042

**Installed from**: 
Microsoft Store

**Question**:

When opening a package I get the warning about Compiler Flags:
Present, not reproducible
Ensure you're at least using the 5.0.200 SDK or MSBuild 16.9

Both are in use:

Build engine:
```
dotnet pack -c RELEASE
Microsoft (R)-Build-Engine, Version 16.9.0+57a23d249 für .NET
```
SDK version:
```
C:\Program Files\dotnet\sdk\5.0.200\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(221,5): 
...
```
Why does the warning show up then?

**Comment by clairernovotny** [comment]
Might be a bug in the logic, will take a look.

**Comment by qbit86** [comment]
@clairernovotny 
The same question.
