### ISSUE TITLE
NGPE and deterministic builds are not showing properly?

### ISSUE THREAD

**Issue by dominikjeske** [NuGetPackageExplorer/NuGetPackageExplorer#1271]
**Type**: Bug
**NPE version**: 5.10.4+4ab9498d27
**OS version**: Windows 10 19042.804
**Installed from**: GitHub
**.NET SDK**: 5.0.201

I'm having a problem with deterministic builds and I'm not sure where is a problem - my config, SDK or NGPE.

According to this issue https://github.com/dotnet/sdk/issues/16325 even when package is build using ContinuousIntegrationBuild and IL Spy says: "This assembly was compiled using the /deterministic option." I still see

![image](https://user-images.githubusercontent.com/3872348/114698484-6fca2d80-9d1f-11eb-97b4-213acc9197d4.png)

I'm using flag ContinuousIntegrationBuild https://devblogs.microsoft.com/dotnet/producing-packages-with-source-link/#deterministic-builds

`dotnet pack /p:ContinuousIntegrationBuild=true`

**Comment by clairernovotny** [comment]
Is your library using any sort of IL rewriter, linker, or trimmer during the build?

**Comment by dominikjeske** [comment]
I don't think so. I have done some test - create new empty library and use my nuget settings and result is the same. Maybe I'm doing something wrong - below is my config. ps. Funny thing is that when I'm opening snupkg in NGPE this package is marked as deterministic. I'm not sure where is the problem :(

`  <PropertyGroup>
    <PackageId>$(AssemblyName)</PackageId>
    <MaintainerEmail>my@company.pl</MaintainerEmail>
    <RepoRoot>$(MSBuildThisFileDirectory)</RepoRoot>
    <RepositoryUrl>https://repoaddress</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageProjectUrl>https://servicedocs</PackageProjectUrl>
    
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
  </PropertyGroup>

  
  <PropertyGroup>
    
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    
    <EmbedAllSources>true</EmbedAllSources>
    
    <DebugType>portable</DebugType>
    
    <DebugSymbols>true</DebugSymbols>
    
    <IncludeSymbols>true</IncludeSymbols>
    
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>`

**Comment by clairernovotny** [comment]
If you hover over the red icon, what does it say? Is there a repro package you can post?

**Comment by dominikjeske** [comment]
I can share this sample https://github.com/dominikjeske/Samples/tree/main/Nuget - it has nothing more than pure .net app and settings above. I have pack it with this command

`dotnet pack /p:ContinuousIntegrationBuild=true`

When I hover over red icon I can see this:

![image](https://user-images.githubusercontent.com/3872348/114760848-146c5f80-9d60-11eb-9348-57890e6d5aba.png)

@clairernovotny Thanks for you support.

**Comment by clairernovotny** [comment]
Closing due to age. Please re-open if still an issue.

**Comment by dominikjeske** [comment]
@clairernovotny  Hmm I'm confused - it is old because there was no answer. I gave example how to reproduce the problem on clean solution. Maybe I'm doing something wrong but I can’t really say – I was waiting for some feedback. I have checked on current version and have same result with “Non deterministic”. If tool is working good please look at the sample app and explain what is not set right.

**Comment by veikkoeeva** [comment]
I can have a package at https://github.com/veikkoeeva/DotDecentralized/ that also produces packages to https://github.com/veikkoeeva/DotDecentralized/packages/. It exhibits this case too.

It may be interesting to note that local builds are flagged as deterministic. That is, adding

```
<PropertyGroup>
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  </PropertyGroup>
```

and doing a local package like `dotnet pack --configuration release --no-restore --include-symbols --include-source -property:PackageVersion=1 --output ./nupkg/dotssi src/DotSsi/DotSsi.csproj` from the project root and NPE shows the build is deterministic. This is not the case for the builds from the aforementioned Nuget feed (when anyone reading this, it may not be available in that repo anymore as it's a temporary one). I tried both with `snupkg` and `embedded` format.

I have not checked the source code. Maybe there is logic that is affected if the symbols are either local or remote or in `snupkg` or embedded format.

**Comment by DamianEdwards** [comment]
This is happening to me too.

**Comment by qlikTERror** [comment]
Me too equal
