### ISSUE TITLE
Assembly strong name information is misleading

### ISSUE THREAD

**Issue by quasarea** [NuGetPackageExplorer/NuGetPackageExplorer#1272]
Bug

NuGet Package Explorer - Zip - X64 - (5.9.48+f28f3b874b)
Windows 10 - 1903
**Installed from**: Zip on GitHub

Using sn tool I get below information:
```
sn -vf Common.1.1.1.dll

Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Assembly 'Common.1.1.1.dll is a delay-signed or test-signed assembly
```
and
```
C:\git\temp\sn>sn -vf Common.1.1.4.dll

Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Assembly 'Common.1.1.4.dll' is valid
```

Using package explorer in both cases I get :
```
Strong Name: Yes, version 1.0.0.0
```
- What is the expected result?
 - in first case: `Strong Name: Nope, but delay-signed or test-signed assembly, version 1.0.0.0`
 - in second case `Strong Name: Yes, version 1.0.0.0`

**Comment by clairernovotny** [comment]
NPE checks to see if there is a strong name but does not validate it. Strong names are not validated by .NET Core, .NET 5, Mono. In .NET Framework, they're only validated when using app domains or the GAC.

**Comment by quasarea** [comment]
@clairernovotny I failed to find any articles about strong naming being left behind. Could you point me to one?
