### ISSUE TITLE
Update private build of NuGet.* packages for GetReadme

### ISSUE THREAD

**Issue by joelverhagen** [NuGetPackageExplorer/NuGetPackageExplorer#1274]
**Type** (choose one): feature request
**NPE version**: NuGetPackageExplorer.Core 5.10.8
**Installed from**: https://pkgs.dev.azure.com/dotnet/NuGetPackageExplorer/_packaging/BuildPackages/nuget/v3/index.json

The build of NuGet.Packaging used for `netcoreapp3.1` seems to be an older source version than other targets:

**OLD:**
https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/92f485d2842794f45f2dcb90984bab138410b1e7/Directory.Build.targets#L8-L10

**NEW:**
https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/92f485d2842794f45f2dcb90984bab138410b1e7/Directory.Build.props#L44

This is evidenced by ILSpy on NuGet.Packaging.dll not having `NuspecReader.GetReadme()`. 

This update would also make the `#if !NETCOREAPP3_1` stuff unnecessary:
https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/92f485d2842794f45f2dcb90984bab138410b1e7/Core/Packages/SimplePackage.cs#L30-L32

**WORKAROUND:**
I worked around this by merging the `5.10.0-preview.2.7169` tag into the commit that produced `5.10.0-xprivate.60024` (https://github.com/NuGet/NuGet.Client/tree/dev-jver-npe), built it locally, and checked the .nupkg files into my repo with a local file source, but ideally, the main version would be up to date: [packages](https://github.com/joelverhagen/ExplorePackages/tree/main/packages), [NPE source](https://github.com/joelverhagen/NuGetPackageExplorer/tree/jver-newget).

**Comment by clairernovotny** [comment]
Done in #1279
