### ISSUE TITLE
Software crashes any attempt to publish via file->publish

### ISSUE THREAD

**Issue by IObsequious** [NuGetPackageExplorer/NuGetPackageExplorer#129]
Hi! Thanks for reporting this feature/bug/question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

**Type** (choose one):

- Bug

**NPE version**: (e.g. 3.12) (see Help -> about)
   v3.18

**Installed from**: 

ClickOnce

In case of a BUG:

- What is the current result? 
    The software crashes
- What is the expected result? 
    The software to continue in functional state
- Please post full exception details in case of an Exception (message, stacktrace, inner exceptions)

System.Security.Cryptography.CryptographicException was unhandled
Message: An unhandled exception of type 'System.Security.Cryptography.CryptographicException' occurred in System.Security.dll
Additional information: Key not valid for use in specified state.

- Are there any work arrounds? 
 no. 

- Is there a version in which it did worked?
 I used this tool two months ago on a machine with near similar configurations without trouble. Uninstalling/Reinstalling does not refresh or amend the problem. 

- Is there a package on Nuget.org which shows the bug? I suspect all of them, but the one I wanted to look at the time of the crash was package id: Microsoft.VisualStudio.SDK.VsixSuppression

**Comment by IObsequious** [comment]
edited misspelling in title

**Comment by 304NotModified** [comment]
Did you have upgraded your Windows?

**Comment by IObsequious** [comment]
This must have been my machine's fault. We had a power blackout yesterday, after which I had to manually service the image with new updates using the "DISM.EXE". Once finished, I tried package explorer and It was working fine.

I would like to thank you for what you do and for this project. Take care!

**Comment by 304NotModified** [comment]
Thanks for the feedback!
