### ISSUE TITLE
Import package dependencies from package.config

### ISSUE THREAD

**Issue by marcosikkens** [NuGetPackageExplorer/NuGetPackageExplorer#130]
I'm currently releasing a lot of different nuget packages but they all share some common packages. Currently i have to define the required dependencies that the nuget package has in the nuspec manually. These dependencies are already shown in the package.config  file.

For me it would save me a lot of time/erros that there is an option that allows the reading of the packages config to automaticly create the dependencies so i don't have to define them manually.

**Comment by 304NotModified** [comment]
Agree, but that's is already in the new project system of Visual Studio (project.json thing)

**Comment by marcosikkens** [comment]
Hello,

I was googling about this but then i found the following article
https://www.infoq.com/news/2016/05/project-json.

This states that Microsoft is moving Back again.

Op wo 14 sep. 2016 22:26 schreef Julian Verdurmen <notifications@github.com

**Comment by 304NotModified** [comment]
PR will be accepted, it has low prio for us

**Comment by Eonasdan** [comment]
I wanted to contribute this feature to this project as I thought it might be something I could tackle to give back to this awesome tool quite a bit. However, I don't do much on the windows app side of things and thus don't know much about XAML. I did create a gist of what it would take to parse a packages.config file and add it to the dependencies set:

https://gist.github.com/Eonasdan/095c33bf0b0f27b0a73ab0d05e17b2f6

wish I could help more

**Comment by onovotny** [comment]
Closing this out as this is best done with the SDK style projects. Directory.build.props can add the same PackageReference to multiple projects at once and the pack tasks generate the correct dependencies.
