### ISSUE TITLE
New Project: .NET Single-file Explorer

### ISSUE THREAD

**Issue by bricelam** [NuGetPackageExplorer/NuGetPackageExplorer#1318]
I've been working with [single-file applications](https://docs.microsoft.com/dotnet/core/deploying/single-file) lately, and I find myself wanting a tool like NuGet Package Explorer to inspect the bundled contents.

[Version 1 of the bundle format](https://github.com/dotnet/designs/blob/main/accepted/2020/single-file/design_3_0.md#the-bundler) is documented here, and [version 2](https://github.com/dotnet/designs/blob/main/accepted/2020/single-file/bundler.md#bundle-layout) is here.

Like a .nupkg, it's essentially just some metadata and a bunch of .NET files. The layout and View Content (including Plugins) of NuGet Package Explorer could all be reused to create a consistent experience between the two apps.

The code for writing bundles is contained in the [Microsoft.NET.HostModel](https://github.com/dotnet/runtime/blob/main/src/installer/managed/Microsoft.NET.HostModel/Bundle/Bundler.cs) package. Understandably, the code for reading bundles is currently [all native](https://github.com/dotnet/runtime/tree/main/src/native/corehost/bundle).

**Comment by clairernovotny** [comment]
I'm not opposed to possibly supporting this, but I think it'd be a very large lift as NPE today is tight with the NuGet object model. Happy to discuss a solution if someone wants to jump in and take a look.

**Comment by bricelam** [comment]
Looks like [ILSpy](https://ilspy.net/) implement this.
