### ISSUE TITLE
Some fonts are blurry

### ISSUE THREAD

**Issue by terrajobst** [NuGetPackageExplorer/NuGetPackageExplorer#1319]
In my browser (see version below) it [looks like](https://www.nuget.info/packages/nquery) some fonts, such as the group headers, are blurry. Is this related to #1308?

![MicrosoftTeams-image](https://user-images.githubusercontent.com/5169960/125150959-88689a80-e0f8-11eb-9bf6-6bb9ff495d19.png)

Item | Version
-- | --
Microsoft Edge | 91.0.864.64 (Official build) (64-bit)
Revision | 3bb5c9989b78b4fcfd356345ac1b4c0d626baefa
Operating system | Windows 10 OS Version 2009 (Build 19043.1083)

**Comment by jeromelaban** [comment]
Fixed in latest!
