### ISSUE TITLE
How to using this tool in command line

### ISSUE THREAD

**Issue by hupo376787** [NuGetPackageExplorer/NuGetPackageExplorer#1333]
Hi! Thanks for reporting this feature/bug/question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

**Type** (choose one):

- Question

**NPE version**: 5.10.43+ce9a70d0c5

**OS version**: win10 19041

**Installed from**: Zip on GitHub

I have an obfuscated dll, and want to pack to nuget. So how to use it in the command line. 
I just wrote the obfuscate bat, and do all in a bat file.
Thx.

**Comment by clairernovotny** [comment]
Not sure what the question is here? NPE can create packages using the UI or you can use the regular NuGet commands via `nuget.exe` or `dotnet pack` to create packages on the CLI.

https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package

**Comment by hupo376787** [comment]
Hi, @clairernovotny . I'm using third-party obfuscate software, it generates an obfuscated dll. While dotnet pack can only pack the dlls generated by vs. So I want to use this tool to pack the obfuscated dll.

But, now I found a solution. Put the obfuscated code into post-build event, and use `dotnet pack -no-build` to pack the obfuscated dll.

Thanks for your time.
