### ISSUE TITLE
Assemblies using EmbedAllSources instead of SourceLink are shown as non-deterministic

### ISSUE THREAD

**Issue by jnm2** [NuGetPackageExplorer/NuGetPackageExplorer#1349]
**Type** (choose one): Bug

**NPE version**: 5.10.43+ce9a70d0c5

**OS version**: Windows 10 21H1

**Installed from**: Microsoft Store (I think... it doesn't appear as installed within the Store app though, so how do I find out how I installed it? Not via Chocolatey or manually. Maybe ClickOnce?)

NuGet Package Explorer does not treat EmbedAllSources as deterministic. I'm not aware of any reason why it is less of a valid option than SourceLink in terms of determinism. 

For libraries both produced on GitHub and in private non-GitHub repositories,  I like EmbedAllSources because you don't have the on-demand network download per file or any prompts in the IDE to download. A lot more could go wrong with URL downloads compared to embedded source, whereas things just work even without an internet connection. (GitHub just had an outage a few minutes ago.) And there's the headache of private repositories that require authentication.

- What is the current result?
  ![image](https://user-images.githubusercontent.com/8040367/129923569-213f7a44-2507-4d67-82ab-0f46637570f8.png)

- What is the expected result?
  All assemblies are shown to be deterministic when not using SourceLink but embedding all source.

- Are there any workarounds?
  Yes, for GitHub repos, add https://www.nuget.org/packages/Microsoft.SourceLink.GitHub in addition to EmbedAllSources. I have not tested whether this causes IDEs to start downloads on demand rather than using the embedded source.

- Is there a version in which it did work?
  I don't know.

- Is there a package on Nuget.org which shows the bug?
  MyGet: https://www.myget.org/feed/techsola/package/nuget/Techsola.InstantReplay/1.0.0-ci.97

**Comment by clairernovotny** [comment]
What are the file paths, deterministic sets a virtual path to the file, it's not about source link vs embedded.

**Comment by jnm2** [comment]
Aha! Without the SourceLink package reference:

![image](https://user-images.githubusercontent.com/8040367/129943723-e947078a-d2de-4ee5-b247-c6e5c714e648.png)

With it:
![image](https://user-images.githubusercontent.com/8040367/129943798-945f6165-f181-479a-b0a2-af3e9bd7c85d.png)

So the SourceLink package is setting a property that perhaps I could set directly.

**Comment by jnm2** [comment]
Wait a minute. I've been here before. https://github.com/dotnet/sdk/issues/15321

**Comment by jnm2** [comment]
Not a NuGet Package Explorer bug then.

**Comment by jnm2** [comment]
When it's not working, PathMap = `C:\Users\Joseph\.nuget\packages\=/_/,C:\Program Files (x86)\Microsoft Visual Studio\Shared\NuGetPackages\=/_1/,C:\Program Files (x86)\Microsoft\Xamarin\NuGet\=/_2/,C:\Program Files\dotnet\sdk\NuGetFallbackFolder\=/_3/,`

When it's working, PathMap = `C:\Users\Joseph\.nuget\packages\=/_1/,C:\Program Files (x86)\Microsoft Visual Studio\Shared\NuGetPackages\=/_2/,C:\Program Files (x86)\Microsoft\Xamarin\NuGet\=/_3/,C:\Program Files\dotnet\sdk\NuGetFallbackFolder\=/_4/,C:\Users\Joseph\Source\Repos\Techsola.InstantReplay\=/_/,`

**Comment by jnm2** [comment]
Here's where the solution directory starts being added as a SourceRoot item which the SDK then builds PathMap from: https://github.com/dotnet/sourcelink/blob/1.0.0/src/Microsoft.Build.Tasks.Git/build/Microsoft.Build.Tasks.Git.targets#L31

**Comment by jnm2** [comment]
The easy thing is probably to just add the extra package reference in addition to EmbedAllSources if you can. Otherwise, this is sufficient to get the approval of NuGet Package Explorer:

```
<ItemGroup>
  <SourceRoot Include="$(SolutionDir)" />
</ItemGroup>
```

**Comment by jnm2** [comment]
I filed an issue at https://github.com/dotnet/sdk/issues/19881 because I think it's an SDK bug that there is this nondeterminism by default even with ContinuousIntegrationBuild=true unless you reference one of the specific SourceLink providers. 

In the meantime, the easy thing is probably to just add that extra package reference in addition to EmbedAllSources if you can. Otherwise, this is sufficient to get the approval of NuGet Package Explorer:

```xml
<ItemGroup>
  <SourceRoot Include="$(SolutionDir)" />
</ItemGroup>
```

See also https://github.com/dotnet/roslyn/issues/37379#issuecomment-513371985.
