### ISSUE TITLE
Ctrl+Shift+S keybinding for "Save As"

### ISSUE THREAD

**Issue by TKharaishvili** [NuGetPackageExplorer/NuGetPackageExplorer#135]
**Type**:

- Feature request

**NPE version**: 3.18

**Installed from**: ClickOnce

"Save As" is quite a frequently used command and I think it would benefit from having a key combination attached to it. I also think that Ctrl+Shift+S is a reasonable candidate for it.

I can offer a pull request myself if you decide to add this feature. I actually have already implemented it in my clone of the repo...

**Comment by 304NotModified** [comment]
PR please :)

**Comment by TKharaishvili** [comment]
Here you have it:
https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/pull/136

**Comment by 304NotModified** [comment]
Released!

**Comment by TKharaishvili** [comment]
Wonderful! Thanks for making it this quick. :)
