### ISSUE TITLE
NetStandard1.6 target?

### ISSUE THREAD

**Issue by Allann** [NuGetPackageExplorer/NuGetPackageExplorer#141]
Hi! Thanks for reporting this feature/bug/question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

**Type** (choose one):
- Question

**NPE version**: (e.g. 3.12) (see Help -> about)
3.19.0.0

**Installed from**: ClickOnce 

In case of a BUG:

- What is the current result? Unsupported version being reported in dependencies 
- What is the expected result? .NETStanard, Version=v1.6
- Please post full exception details in case of an Exception (message, stacktrace, inner exceptions)
- Are there any work arrounds? no
- Is there a version in which it did worked? no 
- Is there a package on Nuget.org which shows the bug? not to my knowledge

in case of a FEATURE REQUEST:
 
 - Why do we need it?
 - Please provide an use case.

**Comment by 304NotModified** [comment]
it's there?

![image](https://cloud.githubusercontent.com/assets/5808377/20748261/c2d71794-b6ed-11e6-92bc-38f06d7e628f.png)

**Comment by Allann** [comment]
yes it is.  now create a package using that.  also add the targetframework .NETStandard1.6.  then open the package in NPE and see that it reports them as unsupported.

**Comment by 304NotModified** [comment]
I think this is a Nuget client issue? The screenshot is not from NPE?

**Comment by Allann** [comment]
![image](https://cloud.githubusercontent.com/assets/2005474/20751459/979ad17e-b747-11e6-8227-be546a3720c3.png)

this one is and is reporting the same.

**Comment by 304NotModified** [comment]
Strange, as there is not specific code for NETSTANDARD versions, only NETSTANDARD or not. 

Do you have an example package on nuget.org? 1.3 and 1.5 works at least (this is the NLog package)

![image](https://cloud.githubusercontent.com/assets/5808377/20751610/f491c090-b6fc-11e6-9f88-417353eb3be9.png)

**Comment by Allann** [comment]
Afraid not.  Our components can't be shared publicly. Maybe I should stop doing bleeding edge development :(  Looking forward to going back to .csproj files again though instead of these project.json files.  They have caused nothing but problems.

**Comment by Allann** [comment]
Just had a look at the code for NLog, noticed you were the author of the nuspec files in coreCLR.  But there are no entries for groups in the dependencies.  So I'm confused how you get the details shown in the image provided.

**Comment by 304NotModified** [comment]
it's the latest NLog beta


> Afraid not. Our components can't be shared publicly.

Well search for a nuget package on nuget.org which lists netstandard 1.6 ;)

**Comment by 304NotModified** [comment]
Found one: https://www.nuget.org/packages/Serilog.Settings.Configuration/2.2.0

and works for me?

![image](https://cloud.githubusercontent.com/assets/5808377/20754607/087099ce-b70c-11e6-9923-a2a0cedaf858.png)

nuspec:


```xml
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2012/06/nuspec.xsd">
    <metadata>
        <id>Serilog.Settings.Configuration</id>
        <version>2.2.0</version>
        <authors>Serilog Contributors</authors>
        <owners>Serilog Contributors</owners>
        <licenseUrl>http://www.apache.org/licenses/LICENSE-2.0</licenseUrl>
        <projectUrl>http://serilog.net/</projectUrl>
        <iconUrl>http://serilog.net/images/serilog-configuration-nuget.png</iconUrl>
        <requireLicenseAcceptance>false</requireLicenseAcceptance>
        <description>Microsoft.Extensions.Configuration (appsettings.json) support for Serilog.</description>
        <tags>serilog,json</tags>
        <dependencies>
            <group targetFramework=".NETFramework4.5.1">
                <dependency id="System.Runtime" version="4.0.10" />
                <dependency id="Microsoft.Extensions.Configuration.Abstractions" version="1.0.0" />
                <dependency id="Microsoft.Extensions.DependencyModel" version="1.0.0" />
                <dependency id="Serilog" version="2.0.0" />
            </group>
            <group targetFramework=".NETStandard1.6">
                <dependency id="Microsoft.Extensions.Configuration.Abstractions" version="1.0.0" />
                <dependency id="Microsoft.Extensions.DependencyModel" version="1.0.0" />
                <dependency id="Serilog" version="2.0.0" />
            </group>
        </dependencies>
    </metadata>
</package>
```

**Comment by Allann** [comment]
Ok,  Very interesting.  Compared my nuspec file dependency group to that and it's exactly the same, so what I am doing must be right.  No idea then why it's reporting as unsupported in NPE.  I'll check my NPM in the morning.  Thanks for the help.

**Comment by Allann** [comment]
Updated Nuget.exe to 3.5.0.1829 but issue persists.  Happy for you to close this as I don't think it's directly associated with NPE any more.  Just not sure what to check next.

**Comment by 304NotModified** [comment]
Let me know if you need some more info from us!
