### ISSUE TITLE
Cannot open Packages that Use SemVer 2.0

### ISSUE THREAD

**Issue by onovotny** [NuGetPackageExplorer/NuGetPackageExplorer#143]
Hi! Thanks for reporting this feature/bug/question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

**Type** (choose one):

- Bug

**NPE version**: (e.g. 3.12) (see Help -> about)
3.19

**Installed from**: ClickOnce / chocolatey.org / Zip on CodePlex 
ClickOnce

In case of a BUG:
NPE should read/understand the package

- What is the current result?
Error opening a NuPkg: `2.8.1-vs2017.1` is not a valid version string. Parameter name: version

- What is the expected result? 
Package should open

- Please post full exception details in case of an Exception (message, stacktrace, inner exceptions)
- Are there any work arrounds? no
- Is there a version in which it did worked? no
- Is there a package on Nuget.org which shows the bug? no. NuGet.org doesn't currently allow SemVer 2.0 packages. MyGet does.

in case of a FEATURE REQUEST:
 
 - Why do we need it? SemVer 2.0 is popular and is now supported in the latest NuGet clients.
 - Please provide an use case. CI builds

[Zeroconf.2.8.1-vs2017.1.nupkg.zip](https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/files/656245/Zeroconf.2.8.1-vs2017.1.nupkg.zip)

**Comment by 304NotModified** [comment]
thanks for the report! Will try to look at this soon!

**Comment by 304NotModified** [comment]
Working on this

**Comment by 304NotModified** [comment]
Is fixed in 3.20, thanks to @BreeeZe (with https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/pull/147)

publishing now!

**Comment by 304NotModified** [comment]
pbulishing is broken on Codeplex :(

![image](https://cloud.githubusercontent.com/assets/5808377/21526225/dd183002-cd22-11e6-826c-43355d11a2e6.png)

**Comment by 304NotModified** [comment]
saved by a textdiff!  Merge corrupted some config settings.

Fixed and live!
