### ISSUE TITLE
Ask for updating the package on Winget

### ISSUE THREAD

**Issue by ali50m** [NuGetPackageExplorer/NuGetPackageExplorer#1436]
```Powershell
winget show NuGetPackageExplorer.NuGetPackageExplorer
```

output:
已找到 NPE (Nightly) [NuGetPackageExplorer.NuGetPackageExplorer]
版本: 5.8.34.0
发布者: NuGet Package Explorer (.NET Foundation)
作者: NuGetPackageExplorer
绰号： nuget-package-explorer
描述: Create, update and deploy Nuget Packages with a GUI.
主页: https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/
许可证: Copyright (c) .NET Foundation and Contributors
许可证 URL: https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/main/LICENSE.txt
安装：
  类型: Msix
  下载 URL： https://npenightly.blob.core.windows.net/nightly/PackageExplorer.Package_5.8.34.0_Test/PackageExplorer.Package_5.8.34.0_x64_x86.appxbundle
  SHA256: b39e6f5b1df34393966a755c9fc5ee8e63c10d097936ea8662170ea607a3ed8b

**Comment by clairernovotny** [comment]
Not sure what this is about. The main package is published through the store.

**Comment by campersau** [comment]
Someone has published the NuGetPackageExplorer to [winget](https://docs.microsoft.com/windows/package-manager/winget/) which is now outdated: https://github.com/microsoft/winget-pkgs/tree/master/manifests/n/NuGetPackageExplorer

**Comment by clairernovotny** [comment]
I'll file an issue there. It should not point to the CI feed, it should pull from the store or be removed.

**Comment by clairernovotny** [comment]
Closing as external: https://github.com/microsoft/winget-pkgs/issues/39431
