### ISSUE TITLE
[Bug] When Publishing to private feed I get The <licenseUrl> element is deprecated. 

### ISSUE THREAD

**Issue by davidbuckleyni** [NuGetPackageExplorer/NuGetPackageExplorer#1439]
There seems to be  some braking changes in version 6.0.27

When I publish to nuget private feed I get the following error.

 We found the following issue(s):
The <licenseUrl> element is deprecated. Consider using the <license> element instead. Learn more.
We recommend that you fix these issues and upload a new package. To learn more about authoring great packages, view our Best Practices page.

**Comment by clairernovotny** [comment]
The warning from the server is accurate; you can update your NuGet metadata to include a license element instead of a licenseUrl. NPE lets you view either.
