### ISSUE TITLE
Holds onto file handle on file close

### ISSUE THREAD

**Issue by wonea** [NuGetPackageExplorer/NuGetPackageExplorer#145]
- Bug
- 3.19
- ClickOnce

In case of a BUG:

- What is the current result?
Close file, still keeps the file handle open on the file. Jump into the command prompt and try to delete or move the file.

del : Cannot remove item C:\Development\Logging.1.0.0.nupkg: The process cannot access the file 'C:\Development\Logging.1.0.0.nupkg'
because it is being used by another process.

- What is the expected result?
Close file closes the file handler.

- Are there any work arrounds?
Close NuGet Package Explorer

- Is there a version in which it did worked? 
Not sure

- Is there a package on Nuget.org which shows the bug?
Any

**Comment by 304NotModified** [comment]
Thanks for reporting!

Bug confirmed. 

No sure how to fix. Bug is probable in not closing stream (which caused other problems before). Related code is in ZipPackage / File.Open

**Comment by paulomorgado** [comment]
It also happens when installed from the Windows Store.

**Comment by 304NotModified** [comment]
> It also happens when installed from the Windows Store.

Yes it hasn't been fixed yet, and the Windows Store version is the same as the ClickOnce.

This bug has been introduced in https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/pull/87 

I reviewed and tested it, but didn't noticed the lock before.
