### ISSUE TITLE
Switch from ClickOnce to Squirrel for installer

### ISSUE THREAD

**Issue by caioproiete** [NuGetPackageExplorer/NuGetPackageExplorer#15]
([originally created](https://github.com/dsplaisted/NuGetPackageExplorer/issues/2) by @dsplaisted)

[Squirrel](https://github.com/Squirrel/Squirrel.Windows)

**Comment by 304NotModified** [comment]
@dsplaisted van you tell something about Squirrel?

**Comment by 304NotModified** [comment]
https://github.com/Squirrel/Squirrel.Windows

**Comment by dsplaisted** [comment]
I'm not super familiar with either Squirrel or ClickOnce.  I know that Squirrel is supposed to be like ClickOnce but better.

Squirrel installs apps to your user folder so you don't need elevation to install them.  It can automatically keep them up to date.  (As far as I know ClickOnce also does these things).

One cool thing about Squirrel is that it handles updates by creating packages that are binary diffs between different versions.  So when upgrading from one version to the another, only what's changed needs to be downloaded instead of the whole app.

**Comment by 304NotModified** [comment]
> Squirrel installs apps to your user folder so you don't need elevation to install them. It can automatically keep them up to date. (As far as I know ClickOnce also does these things).

Yes, that's indeed possible with ClickOnce 

I'm curious if we can host the Squirrel version in Github (pages). I tried with ClickOnce, but failed (the install step always failed, dunno why)

**Comment by onovotny** [comment]
One extra benefit is that is that it can easily be pushed to any blob storage...probably with less hassle than ClickOnce.

**Comment by NanaLich** [comment]
could you show me the details where you failed to host the ClickOnce deployment?

**Comment by 304NotModified** [comment]
@Licshee do you mean failing to publish on github or what is described in #27?

**Comment by Licshee** [comment]
@304NotModified on github.io

**Comment by 304NotModified** [comment]
Clickonce won't install from Github, because Github won't send the correct headers. You get a fatal error when installing.

**Comment by Licshee** [comment]
related to Content-Type?

**Comment by 304NotModified** [comment]
Have to check that. Could be possible.

**Comment by 304NotModified** [comment]
The required clickonce headers:

![headers-clickonce](https://cloud.githubusercontent.com/assets/5808377/13338576/9a9c1460-dc22-11e5-8c21-928c0689f3e0.png)

https://msdn.microsoft.com/en-us/library/ms228998.aspx#Anchor_5

**Comment by MaitreDede** [comment]
Hi, the help about mime types for github pages : https://help.github.com/articles/mime-types-on-github-pages/

Mime types supported : .application, .deploy (from apache definition)
Missing defined mime types for .manifest, .msu, .msp

I don't know what is the github pages behavior for undefined mime types.

**Comment by 304NotModified** [comment]
Thanks, but it think there is no problem to keep it on CodePlex for now.

**Comment by 304NotModified** [comment]
label "install error", as this could fix the install error

**Comment by 304NotModified** [comment]
Helper tool
https://github.com/flagbug/ClickOnceToSquirrelMigrator

**Comment by onovotny** [comment]
Nevermind squirrel, how about using a Centennial app in the Windows Store for those of us on Win10? :)

**Comment by 304NotModified** [comment]
Sounds great!

Any idea if this will support everything we use now? (e.g. file extension registration etc)

**Comment by onovotny** [comment]
It should support anything a user process can do.

What I'll do is the following:
- Create the packaging project or whatever is needed to support this.
- Create a store submission
- Figure out how to do a CI build to package and publish to the store (if possible)

I'll submit the changes as a PR initially. Depending if we can get CI/CD going, I may just need a head's up on when it's time to create a new release to the store. How's that sound?

**Comment by 304NotModified** [comment]
Sounds very good! Thanks in advance! !

**Comment by onovotny** [comment]
@304NotModified happy to help. can you pls drop me an email - I don't think I have yours. Mine is first at last dot org.

**Comment by onovotny** [comment]
The app is now in the Windows store for Windows 10 Anniversary Update and later users: https://www.microsoft.com/store/apps/9wzdncrdmdm3

I recommend switching to that version as it does not have any installer issues and auto-updates.
