### ISSUE TITLE
Support for .NET Framework 4.8.1 & .NET 7

### ISSUE THREAD

**Issue by Wagnerp** [NuGetPackageExplorer/NuGetPackageExplorer#1555]
Hi! Thanks for reporting this feature/bug/question!

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

Type (choose one):
[x] Feature request

NPE version:
6.0.64

Installed from:
Windows Store

in case of a FEATURE REQUEST:

Why do we need it?
Currently, NPE does not provide options for adding binaries for `net481` or `net7.0`, unless they're built in Visual Studio.

Please provide an use case.

N/A

**Comment by Wagnerp** [comment]
Implementation is in the works! :)

**Comment by pantonis** [comment]
Trying to add a .NET 7 folder and it is not there... Is this because there is no support for .NET 7 yet?

**Comment by Wagnerp** [comment]
> Trying to add a .NET 7 folder and it is not there... Is this because there is no support for .NET 7 yet?

Hi @pantonis 

I have implanted it, but the PR hasn't been merged yet.

cc. @clairernovotny

**Comment by pantonis** [comment]
I renamed existing .NET 6 in an existing nupkg file and it seems to
be working. Will this cause a problem?

**Comment by Wagnerp** [comment]
> I renamed existing .NET 6 in an existing nupkg file and it seems to be working. Will this cause a problem?

@pantonis No, shouldn't be an issue, but if you want, you can build it from my [branch](https://github.com/Wagnerp/NuGetPackageExplorer/tree/net481net7support)

**Comment by Wagnerp** [comment]
Added .NET 8 too

**Comment by Wagnerp** [comment]
This has now been merged.
