### ISSUE TITLE
Bug: ClickOnce installation doesn't finish

### ISSUE THREAD

**Issue by SuperJMN** [NuGetPackageExplorer/NuGetPackageExplorer#156]
It's a bug. 

Version: latest (tried today)

![captura](https://cloud.githubusercontent.com/assets/3109851/21558164/da7269ee-ce35-11e6-8759-64ec7536a51d.PNG)

The installation doesn't finish. It remains like the screenshot indefinitely.

What can I try to unblock the installation? 
Thanks in advance

**Comment by 304NotModified** [comment]
Do you have an install log ?

Please fill in the template

**Comment by 304NotModified** [comment]
maybe related: https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/issues/157

**Comment by onovotny** [comment]
ClickOnce is unstable. Recommendation is to use the Windows Store app (same as the desktop) if you have Windows 10 Anniversary Update or later: https://www.microsoft.com/store/apps/9wzdncrdmdm3
