### ISSUE TITLE
Can't create package for net6.0-windows

### ISSUE THREAD

**Issue by MatthewSteeples** [NuGetPackageExplorer/NuGetPackageExplorer#1566]
**Type** (choose one):

- Bug

**NPE version**: 6.0.64+c118e46e01 (Installed via Store)

**OS version**: Windows 10 - 22H2 (19045.2311)

**Installed from**: Microsoft Store

In case of a BUG:

- What is the current result?

Create a new package
Add a `lib` folder
Add a `net6.0-windows` folder under lib
Add any valid dll to the net6.0-windows folder
Try and save the package

The following error appears and the package is not saved

`Some included files are included under TFMs which are missing a platform version: net6.0-windows`

- What is the expected result?

Package created

Possibly related: https://github.com/NuGet/Home/issues/10845

**Comment by MatthewSteeples** [comment]
As a workaround, renaming the folder to `net6.0-windows7.0` works for creating the package

**Comment by Wagnerp** [comment]
Hi @MatthewSteeples 

Does it occur when using net5.0-windows too?

**Comment by Wagnerp** [comment]
Fixed in my [branch](https://github.com/Wagnerp/NuGetPackageExplorer/tree/net481net7support)
