### ISSUE TITLE
 Failed to start NPE 3.21 on both my machines

### ISSUE THREAD

**Issue by leozhou-sh** [NuGetPackageExplorer/NuGetPackageExplorer#157]
Hi! Thanks for reporting this feature/bug/question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

**Type** (choose one):

- Bug

**NPE version**: (e.g. 3.12) (see Help -> about) 3.12

**Installed from**: ClickOnce 

In case of a BUG:

- What is the current result? FAILED TO START!
- What is the expected result? START!
- Please post full exception details in case of an Exception (message, stacktrace, inner exceptions)
- Are there any work arrounds? yes/no
- Is there a version in which it did worked? 
- Is there a package on Nuget.org which shows the bug?

in case of a FEATURE REQUEST:
 
 - Why do we need it?
 - Please provide an use case.

**Comment by leozhou-sh** [comment]
Here's the details:
PLATFORM VERSION INFO
	Windows 			: 10.0.14986.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.6.2012.0 built by: NETFXREL1LAST
	clr.dll 			: 4.6.2012.0 built by: NETFXREL1LAST
	dfdll.dll 			: 4.6.2012.0 built by: NETFXREL1LAST
	dfshim.dll 			: 10.0.14986.1000 (WinBuild.160101.0800)

SOURCES
	Deployment url			: file:///G:/Temp/NuGetPackageExplorer.application
	Deployment Provider url		: https://npe.codeplex.com/releases/clickonce/NuGetPackageExplorer.application
						Server		: Microsoft-IIS/7.5,CDS02
						X-Powered-By	: ASP.NET
						X-AspNet-Version: 4.0.30319
	Application url			: https://npe.codeplex.com/releases/clickonce/Application%20Files/NuGetPackageExplorer_3_21_0_0/NuGetPackageExplorer.exe.manifest
						Server		: Microsoft-IIS/7.5,CDS02
						X-Powered-By	: ASP.NET
						X-AspNet-Version: 4.0.30319

IDENTITIES
	Deployment Identity		: NuGetPackageExplorer.application, Version=3.21.0.0, Culture=neutral, PublicKeyToken=0000000000000000, processorArchitecture=x86
	Application Identity		: NuGetPackageExplorer.exe, Version=3.21.0.0, Culture=neutral, PublicKeyToken=0000000000000000, processorArchitecture=x86, type=win32

APPLICATION SUMMARY
	* Installable application.
	* Trust url parameter is set.
ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of G:\Temp\NuGetPackageExplorer.application resulted in exception. Following failure messages were detected:
		+ A device attached to the system is not functioning. (Exception from HRESULT: 0x8007001F)

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	* Transaction at [12/29/2016 11:13:32 PM]
		- Staging of a component file (NuGetPackageExplorer.exe) did not succeed.
		- Staging of a component (ICSharpCode.AvalonEdit.dll.genman) did not succeed.
		- Staging of a component file (ICSharpCode.AvalonEdit.dll) did not succeed.
		- Staging of a component (Humanizer.resources.dll.genman) did not succeed.
		- Staging of a component file (Humanizer.resources.dll) did not succeed.
		- Staging of a component (Microsoft.Web.XmlTransform.dll.genman) did not succeed.
		- Staging of a component file (Microsoft.Web.XmlTransform.dll) did not succeed.
		- Staging of a component (PackageViewModel.dll.genman) did not succeed.
		- Staging of a component file (PackageViewModel.dll) did not succeed.
		- Staging of a component (NuGet.Core.dll.genman) did not succeed.
		- Staging of a component file (NuGet.Core.dll) did not succeed.
		- Staging of a component (GrayscaleEffect.dll.genman) did not succeed.
		- Staging of a component file (GrayscaleEffect.dll) did not succeed.
		- Installation of deployment (https://npe.codeplex.com/releases/clickonce/NuGetPackageExplorer.application#NuGetPackageExplorer.application, Version=3.21.0.0, Culture=neutral, PublicKeyToken=0000000000000000, processorArchitecture=x86) did not succeed.
		- Setting one or more of the deployment metadata did not succeed.

WARNINGS
	* The manifest for this application does not have a signature. Signature validation will be ignored.
	* The manifest for this application does not have a signature. Signature validation will be ignored.
	* The manifest for this application does not have a signature. Signature validation will be ignored.

OPERATION PROGRESS STATUS
	* [12/29/2016 11:13:19 PM] : Activation of G:\Temp\NuGetPackageExplorer.application has started.
	* [12/29/2016 11:13:19 PM] : Processing of deployment manifest has successfully completed.
	* [12/29/2016 11:13:19 PM] : Installation of the application has started.
	* [12/29/2016 11:13:19 PM] : Processing of application manifest has successfully completed.
	* [12/29/2016 11:13:30 PM] : Found compatible runtime version 4.0.30319.
	* [12/29/2016 11:13:30 PM] : Request of trust and detection of platform is complete.
	* [12/29/2016 11:13:32 PM] : Downloading of subscription dependencies is complete.
	* [12/29/2016 11:13:32 PM] : Commit of the downloaded application has started.

ERROR DETAILS
	Following errors were detected during this operation.
	* [12/29/2016 11:13:32 PM] System.Runtime.InteropServices.COMException
		- A device attached to the system is not functioning. (Exception from HRESULT: 0x8007001F)
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Internal.Isolation.IStore.Transact(IntPtr cOperation, StoreTransactionOperation[] rgOperations, UInt32[] rgDispositions, Int32[] rgResults)
			at System.Deployment.Internal.Isolation.Store.Transact(StoreTransactionOperation[] operations, UInt32[] rgDispositions, Int32[] rgResults)
			at System.Deployment.Application.ComponentStore.SubmitStoreTransaction(StoreTransactionContext storeTxn, SubscriptionState subState)
			at System.Deployment.Application.ComponentStore.SubmitStoreTransactionCheckQuota(StoreTransactionContext storeTxn, SubscriptionState subState)
			at System.Deployment.Application.ComponentStore.CommitApplication(SubscriptionState subState, CommitApplicationParams commitParams)
			at System.Deployment.Application.SubscriptionStore.CommitApplication(SubscriptionState& subState, CommitApplicationParams commitParams)
			at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- End of stack trace from previous location where exception was thrown ---
			at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)

COMPONENT STORE TRANSACTION DETAILS
	* Transaction at [12/29/2016 11:13:32 PM]
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Installed
			- HRESULT: 0x0
			- Manifest: T40MVLG3.DAY.application
		+ System.Deployment.Internal.Isolation.StoreOperationSetDeploymentMetadata
			- Status: Set
			- HRESULT: 0x0
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Installed
			- HRESULT: 0x0
			- Manifest: NuGetPackageExplorer.exe.manifest
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Installed
			- HRESULT: 0x0
			- File: Resources\fxAssemblies.txt
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Installed
			- HRESULT: 0x0
			- File: NuGetPackageExplorer.exe.config
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Installed
			- HRESULT: 0x0
			- File: nuspec.ico
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Installed
			- HRESULT: 0x0
			- File: nupack.ico
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Installed
			- HRESULT: 0x0
			- Manifest: Humanizer.dll.genman
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Installed
			- HRESULT: 0x0
			- File: Humanizer.dll
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Installed
			- HRESULT: 0x0
			- Manifest: CodeExecutor.dll.genman
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Installed
			- HRESULT: 0x0
			- File: CodeExecutor.dll
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Installed
			- HRESULT: 0x0
			- Manifest: Ookii.Dialogs.Wpf.dll.genman
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Installed
			- HRESULT: 0x0
			- File: Ookii.Dialogs.Wpf.dll
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Installed
			- HRESULT: 0x0
			- Manifest: Core.dll.genman
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Installed
			- HRESULT: 0x0
			- File: Core.dll
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Installed
			- HRESULT: 0x0
			- Manifest: NuGetPackageExplorer.Types.dll.genman
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Installed
			- HRESULT: 0x0
			- File: NuGetPackageExplorer.Types.dll
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Installed
			- HRESULT: 0x0
			- Manifest: NuGetPackageExplorer.exe.genman
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Failed
			- HRESULT: 0x8007001f
			- File: NuGetPackageExplorer.exe
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Failed
			- HRESULT: 0x1
			- Manifest: ICSharpCode.AvalonEdit.dll.genman
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Failed
			- HRESULT: 0x1
			- File: ICSharpCode.AvalonEdit.dll
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Failed
			- HRESULT: 0x1
			- Manifest: Humanizer.resources.dll.genman
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Failed
			- HRESULT: 0x1
			- File: Humanizer.resources.dll
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Failed
			- HRESULT: 0x1
			- Manifest: Microsoft.Web.XmlTransform.dll.genman
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Failed
			- HRESULT: 0x1
			- File: Microsoft.Web.XmlTransform.dll
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Failed
			- HRESULT: 0x1
			- Manifest: PackageViewModel.dll.genman
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Failed
			- HRESULT: 0x1
			- File: PackageViewModel.dll
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Failed
			- HRESULT: 0x1
			- Manifest: NuGet.Core.dll.genman
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Failed
			- HRESULT: 0x1
			- File: NuGet.Core.dll
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Failed
			- HRESULT: 0x1
			- Manifest: GrayscaleEffect.dll.genman
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Failed
			- HRESULT: 0x1
			- File: GrayscaleEffect.dll
		+ System.Deployment.Internal.Isolation.StoreOperationInstallDeployment
			- Status: Failed
			- HRESULT: 0x1
			- AppId: https://npe.codeplex.com/releases/clickonce/NuGetPackageExplorer.application#NuGetPackageExplorer.application, Version=3.21.0.0, Culture=neutral, PublicKeyToken=0000000000000000, processorArchitecture=x86
		+ System.Deployment.Internal.Isolation.StoreOperationSetDeploymentMetadata
			- Status: Failed
			- HRESULT: 0x1
		+ System.Deployment.Internal.Isolation.StoreTransactionOperationType (27)
			- HRESULT: 0x1

**Comment by tiesont** [comment]
> Why this upgrade?

3.2.1 is supposed to add support for .NET Core packages, among other things.

**Comment by 304NotModified** [comment]
Is this an upgrade or clean install? Could you try r
reinstalling?

This release does work on my machine. 


Maybe related https://blogs.msdn.microsoft.com/smondal/2013/12/02/a-device-attached-to-the-system-is-not-functioning/

**Comment by tiesont** [comment]
I can confirm that there seems to be an issue - I get the same error on both an update and a clean install.

![error-on-clean-install](https://cloud.githubusercontent.com/assets/420293/21573258/58e8eb98-ceb0-11e6-8a7a-9f8ac50c1258.png)

It might be the way the executable is compiled. Both the Smart Screen filter and my antivirus flagged the nugetpackageexplorer.exe as a threat. If I restore the .exe, the application launches as expected. Did something change between 3.19 and 3.21? The former didn't trigger any warnings when installing.

**Comment by 304NotModified** [comment]
Could you post the antivirus scan results ?

Since 3.20 a new assembly has been added. Will give more details soon.

**Comment by tiesont** [comment]
I will try a clean install again sometime tonight and add the requested results - not at my PC at the moment.

It seemed mostly like it simply didn't trust the exe - I can tell you the flag was WS.Reputation.1, which is Norton's way of saying it doesn't trust what it has no history for.

**Comment by 304NotModified** [comment]
Just did a clean install it on machine without problems. Horrible Clickonce applications are unstable as hell.

**Comment by 304NotModified** [comment]
The change which causes problems is from https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/pull/147

There we're some mistakes there, which we're fixed before release. Probably there are some more

**Comment by leozhou-sh** [comment]
From what I can tell, it is very likely due to DPI issue described in:
https://blogs.msdn.microsoft.com/smondal/2013/12/02/a-device-attached-to-the-system-is-not-functioning/

It failed to start on my Surface with a clean install, which has main display DPI set to 175%, second display 100%. As I connected to the second machine on same Surface where it was upgrade, it failed as expected.

BTW, in the previous release, I did not hit this issue on this Surface. There must be some regression changes.

At last, I had to build from source (fortunately we have the source code in github), and I used the compiled one, saved my day.

**Comment by 304NotModified** [comment]
Too bad the issue discibed at https://blogs.msdn.microsoft.com/smondal/2013/12/02/a-device-attached-to-the-system-is-not-functioning/ seems not the case. [app.manifest hasn't changed since nov 2015](https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/master/PackageExplorer/Properties/app.manifest)

**Comment by 304NotModified** [comment]
Comparision of both versions (3.19 - 3.21) https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/compare/v3.19...v3.21

**Comment by 304NotModified** [comment]
Don't see the issue in the comparision yet. 

Which virusscanners give problems?

**Comment by 304NotModified** [comment]
> can confirm that there seems to be an issue - I get the same error on both an update and a clean install.

@tiesont looks like an other error?

**Comment by 304NotModified** [comment]
Compared also deploy settings. Can't find any difference. Stuck for now.

**Comment by tiesont** [comment]
It's probably a combination of this issue and the issue claiming the application contains a virus. The install appears to complete, but launching the app yields the error I posted above, which seems be a complicated way of saying that nugetpackageexplorer.exe is missing. In my case, it's missing because Norton quarantined it. This happens both when upgrading from 3.19 and doing a fresh install of 3.21.

Have you tried an install on a computer that isn't the dev machine?

**Comment by 304NotModified** [comment]
Currently if have only one machine (holiday)

**Comment by tiesont** [comment]
Okay. If no one figures something out before then, I'll try and install on one of our spare office machines, on Monday. They use a different antivirus, which might help figure out if this just a problem caused by a false-positive threat detection. Can't do anything before then.

**Comment by 304NotModified** [comment]
Thx. I'm using only Microsoft's default stuff (windows 10]

**Comment by 304NotModified** [comment]
There is one virus scan result, new since 3.21. 

![image](https://cloud.githubusercontent.com/assets/5808377/21574764/4afafee2-cef9-11e6-941d-44ca79c470fb.png)


https://www.virustotal.com/en/file/1af341eb35ce5cb5c74f60f3a0bfc53f33d5c50c95cab2a447a5916fe4e105c2/analysis/

**Comment by tiesont** [comment]
Yeah, and Qihoo 360 isn't exactly known for being a top-self vendor. Perhaps that's somehow being shared with other scanners, heuristically?

**Comment by 304NotModified** [comment]
yeah maybe. Also, The chocolatey build is from another machine (AppVeyor), so probably the clickonce hasn't the same hash

**Comment by 304NotModified** [comment]
As workaround, you could try installing with Chocolatey. https://chocolatey.org/packages/NugetPackageExplorer

**Comment by tiesont** [comment]
I will try that, and let you know what happens. I'm also attempting to upload the clickonce-installed files to Norton's false-detection form.

**Comment by 304NotModified** [comment]
cool thanks!

I'm now uploading to virustotal.com.

Also related

> Nevertheless, the "HEUR/QVM03.0.0000.Malware.Gen" of the Qihoo-360 antivirus remains warning.

https://social.msdn.microsoft.com/Forums/vstudio/en-US/081020e7-77cf-46f1-aa4a-fdc00804ee4e/my-vs2015-builds-virus-infected-exe-files?forum=visualstudiogeneral

update: all ok according to virustotal.com

![image](https://cloud.githubusercontent.com/assets/5808377/21574931/080fb3da-cefd-11e6-8589-59c34e6d6397.png)


and OK:

> SHA256:	eb03b356c8d5a15f68ea090e76452f34f416980a47b7f5e411c5f85cdd2e196a
> File name:	NuGetPackageExplorer.exe

https://www.virustotal.com/en/file/eb03b356c8d5a15f68ea090e76452f34f416980a47b7f5e411c5f85cdd2e196a/analysis/

**Comment by 304NotModified** [comment]
Guess https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/issues/46 or #15 is more needed then ever

**Comment by tiesont** [comment]
Chocolatey install seems to work just fine, with errors or A/V warnings. NPE runs just fine as well from that install.

**Comment by 304NotModified** [comment]
Installed on a machine which never compiled NPE. 

Works without any problems. 

(Windows Server 2012 R2, x86, **no** 3rd party A/V)

**Comment by 304NotModified** [comment]
could some check the content of the installation folder? Should be 42 items

The find the folder, see http://stackoverflow.com/a/9403378/201303

**Comment by onovotny** [comment]
This is coming....#15 is almost done. In the store now awaiting certification.

**Comment by onovotny** [comment]
ClickOnce is unstable. Recommendation is to use the Windows Store app (same as the desktop) if you have Windows 10 Anniversary Update or later: https://www.microsoft.com/store/apps/9wzdncrdmdm3
