### ISSUE TITLE
Bug: Loading plugin fails

### ISSUE THREAD

**Issue by Sam13** [NuGetPackageExplorer/NuGetPackageExplorer#160]
**Type** (choose one):
- Bug

**NPE version**:  3.21.0.0

**Installed from**: ClickOnce

In case of a BUG:
Loading a plugin fails. Works with 3.19.0.0.
Error: Could not load file or assembly 'NuGetPackageExplorer.Types, Version=3.0.0.0, ...'
![untitled](https://cloud.githubusercontent.com/assets/2196081/21644666/d3c378d8-d28e-11e6-89f9-1b4669913b5e.png)
To reproduce just open the plugin dialog and try to add a feed plugin.
No workaround possible.

**Comment by 304NotModified** [comment]
could you check which dlls are present in the installation directory/

**Comment by 304NotModified** [comment]
Can confirm this one. 

![image](https://cloud.githubusercontent.com/assets/5808377/21649777/2064636e-d2a3-11e6-9000-c9b888b6bc26.png)

**Comment by 304NotModified** [comment]
@Sam13 could you test it by changing

in NuGetPackageExplorer.exe.config

change 3.10 -> 3.12 (twice) in `<bindingRedirect >`

from:

So

```xml
           <dependentAssembly>
                <assemblyIdentity name="NuGetPackageExplorer.Types" publicKeyToken="b33e3c54f0b885e9" culture="neutral"/>
                <bindingRedirect oldVersion="1.0.0.0-3.10.0.0" newVersion="3.10.0.0"/>
            </dependentAssembly>

```
to: 

```xml
           <dependentAssembly>
                <assemblyIdentity name="NuGetPackageExplorer.Types" publicKeyToken="b33e3c54f0b885e9" culture="neutral"/>
                <bindingRedirect oldVersion="1.0.0.0-3.12.0.0" newVersion="3.12.0.0"/>
            </dependentAssembly>

```

**Comment by Sam13** [comment]
@304NotModified Not able to load any plugin, different errors for each plugin. Also unable to load my own plugin which worked with 3.19 (loading all plugins worked there)...

**Comment by onovotny** [comment]
@Sam13 The Plugin system needs to be revamped & fixed up, especially since in v4 the main dependencies shifted significantly (towards using NuGet's libraries).

Is your plugin open-source? If so, can you point me to it? I'd like to ensure we get it working when we solve this.

**Comment by onovotny** [comment]
I'll close this one then for now, but aside from getting ILSpy to work, we ought to think of what the plugin model should be going forward. Maybe what we have is fine, maybe it needs work.
