### ISSUE TITLE
Error while publish package to internal nuget server

### ISSUE THREAD

**Issue by mayureshs** [NuGetPackageExplorer/NuGetPackageExplorer#161]
Hi! Thanks for reporting this feature/bug/question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

**Type** (choose one): Question

- Bug
- Feature request
- Question

**NPE version**: 3.21.0.0

**Installed from**: GitHub

Question : Trying to publish to an internal server with the API key. But I get an error  - "Failed to process request : Not Found"

![capture](https://cloud.githubusercontent.com/assets/1014702/21686725/fe0f3b02-d32b-11e6-8725-7c12443d8df2.JPG)

**Comment by 304NotModified** [comment]
Well it looks like the URI is wrong?

**Comment by mayureshs** [comment]
It did work with the certain version of NPM hosted on my machine. I had to downgrade nuget package manager.

**Comment by 304NotModified** [comment]
The older version have the append checkbox enabled. Probably that's the issue

**Comment by mayureshs** [comment]
Thanks for your reply. You can close the issue for now. Will let you know if this happens again.

**Comment by 304NotModified** [comment]
OK thx!
