### ISSUE TITLE
Open multiple packages at once

### ISSUE THREAD

**Issue by thomaslevesque** [NuGetPackageExplorer/NuGetPackageExplorer#162]
Feature request

It would be nice to be able to open multiple packages at once, each in its own tab. I often need to compare the content of several packages, and having multiple instances of NPE isn't very convenient.

**Comment by onovotny** [comment]
Can you just open multiple instances of NPE? I don't think it's likely we'll be adding tabs to the existing UI.

**Comment by thomaslevesque** [comment]
That's what I do. It's less comfortable than tabs, but I can live with it.
