### ISSUE TITLE
Include an assembly browser/decompiler

### ISSUE THREAD

**Issue by thomaslevesque** [NuGetPackageExplorer/NuGetPackageExplorer#163]
Feature request

The current view for assemblies in packages is useful, but limited (it only shows the assembly version, description, etc). One of the most common things I need to do when I open a package is to examine what's in the assemblies, and for that I have to use an external tool like dotPeek, JustDecompile, Reflector or ILSpy. It would be convenient if a decompiler (or at least an assembly browser) was included directly in NPE. It would probably be possible to use the [ILSpy engine](https://www.nuget.org/packages/ICSharpCode.Decompiler/) and/or Mono.Cecil for that.

As a simpler alternative, providing context menu entries to open the assemblies with common decompilers would be nice (for some reason, the "Open with..." command takes a very long time before it shows the Windows "open with" dialog)

**Comment by svick** [comment]
> As a simpler alternative, providing context menu entries to open the assemblies with common decompilers would be nice (for some reason, the "Open with..." command takes a very long time before it shows the Windows "open with" dialog)

I have associated the .dll extension with my decompiler of choice (dotPeek) and then I can use the "Open in Windows Shell" option. Is there a reason why you can't do that?

**Comment by thomaslevesque** [comment]
@svick I could do that, associating .dll files with dotPeek also associates them with the dotPeek icon, which I don't want... I could probably tweak that in the registry, but it's annoying.

**Comment by onovotny** [comment]
I'm closing this out as decompiling assemblies is beyond the scope of NPE. There are numerous other tools that can do that very well today.
