### ISSUE TITLE
Default to opened package Location for 'Save As'

### ISSUE THREAD

**Issue by EddyCwdry** [NuGetPackageExplorer/NuGetPackageExplorer#164]
**Type** : Feature Request

**NPE version**: Any

**Installed from**: ClickOnce

FEATURE REQUEST:
 
Currently when you open an existing package to update it, if you open/navigate to any other folder (eg using 'replace with'), then the 'Save As' prompt will then open in the last folder accessed, rather than the folder that the package was opened from.

Often I will open an old package, replace various files, then go save as, and currently I then have to navigate back to the base repo folder for our office. It's just a little convenience thing that would save quite a few clicks throughout my day; and to me, it seems to be what would be considered 'expected behavior' for a Save prompt.

**Comment by 304NotModified** [comment]
closed by #187 

thanks!
