### ISSUE TITLE
Bug: list of dependencies is not correctly ordered

### ISSUE THREAD

**Issue by lucaritossa** [NuGetPackageExplorer/NuGetPackageExplorer#166]
**Type**: Bug (very very small)
**NPE version**: 3.21.0.0
**Installed from**:  ClickOnce  

- The list of dependencies is not correctly ordered. See this example:  

![image](https://cloud.githubusercontent.com/assets/12578097/22153348/42f4e210-df27-11e6-9e51-14c814342e2d.png)

- IMO the best result should be an alphabetically order like this:  

![image](https://cloud.githubusercontent.com/assets/12578097/22153321/29668042-df27-11e6-951a-5f2447d47fb3.png)

- I have already a fix. Can I do a PR?  
- I didn't try with another version of this tool.  
- To repeat the same behaviour you can use [Automapper](http://automapper.org) v5.2.0

**Comment by 304NotModified** [comment]
Is the same ordering as nuget.org ;)

https://www.nuget.org/packages/AutoMapper/5.2.0

**Comment by lucaritossa** [comment]
You are right :)  
But it doesn't mean that this is the best UX ;)  

I will open this same issue to nuget project...

**Comment by 304NotModified** [comment]
Isn't it the order in the package?

**Comment by lucaritossa** [comment]
This is true (or it seems so) for AutoMapper.  

In my Visual Studio Project I have a classic .nuspec file generated with "nuget spec" command, without any customization (files or dependencies). All it is retrieved from project...

This is the order of the dependencies:  

<img width="346" alt="screen shot 2017-01-21 at 11 21 29" src="https://cloud.githubusercontent.com/assets/12578097/22173736/f44423ec-dfcb-11e6-8f5b-a2b71604cc9e.png">

**Comment by 304NotModified** [comment]
Closing this for now. Willing to reopen when it has been changed on nuget.org
