### ISSUE TITLE
NPE locks NuGet packages too agressively

### ISSUE THREAD

**Issue by fourpastmidnight** [NuGetPackageExplorer/NuGetPackageExplorer#167]
**NPE version** (e.g. 3.12) (see Help -> about)
3.21.0.0

**Installed from**
- [x] ClickOnce
- [ ] chocolatey.org
- [ ] Zip on CodePlex 

**Type**
- [x] Bug  
- [ ] Feature request  
- [ ] Question  

**What is the current result?**
When a NuGet package is open in NPE, and there are no unsaved changes, NPE holds a file lock on the NuGet package.

Also, simply closing the NuGet package within NPE does not result in the file lock being released. You have to completely exit NPE or open a different NuGet package to release the previous file lock. (This was apparently also reported on #145 as of version 3.19.0.0.)

**What is the expected result?**
When NPE opens a NuGet package, a file lock is not placed on the package. When a change is made to a NuGet package through NPE, when the user saves their changes, then NPE acquires a lock during NuGet modification operations, but releases the file lock once all modifications have been completed. Also, certain "browsing" operations of a NuGet package require unzipping the package--it's therefore, appropriate to acquire a file lock while "inspecting" or reading data from the package. But once that read operation is completed, the file lock should be released.

**Please post full exception details in case of an Exception (message, stacktrace, inner exceptions)**
No exceptions are thrown from NPE.

**Are there any work arounds?**
- [x] Yes
- [ ] No

The workaround is to either close NPE or open a different NuGet package in NPE (simply closing the NuGet package in NPE is not enough, as currently, NPE still holds a file lock on the "closed" package.

- Is there a version in which it did worked? 
   I don't know. This is the first time I'm using NPE in 3 years.

- Is there a package on Nuget.org which shows the bug?
  No. But this seems to apply to any NuGet package.

**Comment by 304NotModified** [comment]
Agree, this is an issue. Any help on this would be great!

**Comment by 304NotModified** [comment]
related or the same https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/issues/145

**Comment by paulomorgado** [comment]
It also happens when installed from the Windows Store.

**Comment by paulomorgado** [comment]
It happens even without any change to the loaded package and remains locked even after loading another package,

**Comment by 304NotModified** [comment]
Closing this because it's a duplicate. Please continue discussion in #145, thanks!
