### ISSUE TITLE
[NETSDKE2E][Regression]With net9 preview7 sdk installed, no any response when running the published NuGetPackageExplorer.exe for 8.0 NPE solution. 

### ISSUE THREAD

**Issue by vdanche** [NuGetPackageExplorer/NuGetPackageExplorer#1673]
ffected Branch: main
Affected Build: 17.12 preview 1 [35122.218.main] + NET 9 SDK: 9.0.100-preview.7.24372.13
Affected Product Language:

Steps to reproduce:
NugetPackageExplorer [Windows] [Framework Dependent]

Clone NuGetPackageExplorer Repo Fot .net 8: git clone [https://github.com/NuGetPackageExplorer/NuGetPackageExplorer](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNuGetPackageExplorer%2FNuGetPackageExplorer&data=01%7C01%7CSwaroop.Sridhar%40microsoft.com%7C9a0b7ed9426d4c12d37308d6ca0c5762%7C72f988bf86f141af91ab2d7cd011db47%7C1&sdata=NQrif7UUQvVqrZQgE2t3d3xiSLaEWaHvJFQHGH0oVVc%3D&reserved=0)
Build the solution in CLI. We are using below steps to build the solution although they will publish also.

     Go to the \NuGetPackageExplorer\PackageExplorer directory
dotnet publish -c Release -r win-x64 /p:PublishReadyToRun=true /p:SelfContained=true NuGetPackageExplorer.csproj
Launch bin\Release\net8.0-windows10.0.19041\win-x64\publish\NuGetPackageExplorer.exe, go to “Open a package from online feed.” There shouldn’t be any errors.

Expected Result:

Run NuGetPackageExplorer.exe succeed without any issue.

Actual Result:

no any response when running the published NuGetPackageExplorer.exe for 8.0 NPE solution.

![image](https://github.com/user-attachments/assets/e48a9cff-cf12-437e-8e1e-72ad0c613490)

Note:

In VS, the same issue happen when publish succeed.

Open NuGetPackageExplorer.sln in VS 2022
Open Configuration manager and set:

Configuration to Release
Set Platform to x86 (add the configuration).

.Publish the NuGetPackageExplorer.csproj project as a framework-dependent app
Create a new FolderProfile
Edit the settings to the following (if not chosen by default)
Configuration = Release|X86
Target Framework = net8.0
Deploy mode = Framework Dependent
Target Runtime = Portable
Publish
Run the published NuGetPackageExplorer.exe(Do this under the specific published folder) and try out a few options.

dotnet --info

.NET SDK:
 Version:           9.0.100-preview.7.24372.13
 Commit:            7061397320
 Workload version:  9.0.100-manifests.54e3c8aa
 MSBuild version:   17.12.0-preview-24368-09+fb48b92ae

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\9.0.100-preview.7.24372.13\

.NET workloads installed:
Configured to use loose manifests when installing new manifests.
 [maui-windows]
   Installation Source: VS 17.12.35122.218
   Manifest Version:    9.0.0-preview.6.24327.7/9.0.100-preview.6
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100-preview.6\microsoft.net.sdk.maui\9.0.0-preview.6.24327.7\WorkloadManifest.json
   Install Type:              Msi

 [maccatalyst]
   Installation Source: VS 17.12.35122.218
   Manifest Version:    17.2.9714-net9-p6/9.0.100-preview.6
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100-preview.6\microsoft.net.sdk.maccatalyst\17.2.9714-net9-p6\WorkloadManifest.json
   Install Type:              Msi

 [ios]
   Installation Source: VS 17.12.35122.218
   Manifest Version:    17.2.9714-net9-p6/9.0.100-preview.6
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100-preview.6\microsoft.net.sdk.ios\17.2.9714-net9-p6\WorkloadManifest.json
   Install Type:              Msi

 [android]
   Installation Source: VS 17.12.35122.218
   Manifest Version:    34.99.0-preview.6.340/9.0.100-preview.6
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100-preview.6\microsoft.net.sdk.android\34.99.0-preview.6.340\WorkloadManifest.json
   Install Type:              Msi

 [aspire]
   Installation Source: VS 17.12.35122.218
   Manifest Version:    8.0.1/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.0.1\WorkloadManifest.json
   Install Type:        FileBased

Host:
  Version:      9.0.0-preview.7.24366.18
  Architecture: x64
  Commit:       static

.NET SDKs installed:
  8.0.400-preview.0.24324.5 [C:\Program Files\dotnet\sdk]
  9.0.100-preview.7.24372.13 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0-preview.7.24369.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0-preview.7.24366.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.30 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.19 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 9.0.0-preview.7.24372.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by v-ainigao** [comment]
This issue also repro's on ARM64OS.

**Comment by vdanche** [comment]
it not repro on last Friday's build 17.12.0 preview 1.0 [35201.184.main] with 9.0.100-preview.7.24380.7 (runtime-9.0.0-preview.7.24376.15) sdk, but It repro on 17.12 preview 1 [35203.38.d17.12] with 9.0.100-preview.7.24402.8 (runtime-9.0.0-preview.7.24401.8) SDK again

**Comment by vdanche** [comment]
This issue not repro on 17.12 preview 2 [35207.203.main] + 9.0.100-rc.1.24407.28 (runtime-9.0.0-rc.1.24406.14)
![image](https://github.com/user-attachments/assets/bde8ff04-bae0-48a9-b725-a2e9d96e426f)

**Comment by vdanche** [comment]
This issue not repro on 17.12.0 preview 2.0 [35226.271.main] with 9.0.100-rc.1.24422.10 (9.0.0-rc.1.24421.1) SDK inserted
![image](https://github.com/user-attachments/assets/c10ef6d2-dbe9-4266-9ce4-a1786f1b2d40)
