### ISSUE TITLE
Fails to start

### ISSUE THREAD

**Issue by jamesej** [NuGetPackageExplorer/NuGetPackageExplorer#170]
Hi! Thanks for reporting this feature/bug/question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

**Type** (choose one):

- Bug
PLATFORM VERSION INFO
	Windows 			: 6.2.9200.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.6.1087.0 built by: NETFXREL4STAGE
	clr.dll 			: 4.6.1087.0 built by: NETFXREL4STAGE
	dfdll.dll 			: 4.6.1087.0 built by: NETFXREL4STAGE
	dfshim.dll 			: 6.3.9600.16384 (winblue_rtm.130821-1623)

SOURCES
	Deployment url			: file:///C:/Users/James/Downloads/NuGetPackageExplorer.application
	Deployment Provider url		: https://npe.codeplex.com/releases/clickonce/NuGetPackageExplorer.application
						Server		: Microsoft-IIS/7.5,CDS04
						X-Powered-By	: ASP.NET
						X-AspNet-Version: 4.0.30319
	Application url			: https://npe.codeplex.com/releases/clickonce/Application%20Files/NuGetPackageExplorer_3_21_0_0/NuGetPackageExplorer.exe.manifest
						Server		: Microsoft-IIS/7.5,CDS04
						X-Powered-By	: ASP.NET
						X-AspNet-Version: 4.0.30319

IDENTITIES
	Deployment Identity		: NuGetPackageExplorer.application, Version=3.21.0.0, Culture=neutral, PublicKeyToken=0000000000000000, processorArchitecture=x86
	Application Identity		: NuGetPackageExplorer.exe, Version=3.21.0.0, Culture=neutral, PublicKeyToken=0000000000000000, processorArchitecture=x86, type=win32

APPLICATION SUMMARY
	* Installable application.
	* Trust url parameter is set.
ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of C:\Users\James\Downloads\NuGetPackageExplorer.application resulted in exception. Following failure messages were detected:
		+ Value does not fall within the expected range.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	* The manifest for this application does not have a signature. Signature validation will be ignored.
	* The manifest for this application does not have a signature. Signature validation will be ignored.
	* The manifest for this application does not have a signature. Signature validation will be ignored.

OPERATION PROGRESS STATUS
	* [06/02/2017 11:20:55] : Activation of C:\Users\James\Downloads\NuGetPackageExplorer.application has started.
	* [06/02/2017 11:20:56] : Processing of deployment manifest has successfully completed.
	* [06/02/2017 11:20:56] : Installation of the application has started.
	* [06/02/2017 11:20:57] : Processing of application manifest has successfully completed.
	* [06/02/2017 11:20:57] : Found compatible runtime version 4.0.30319.
	* [06/02/2017 11:20:57] : Request of trust and detection of platform is complete.
	* [06/02/2017 11:20:57] : Commit of the downloaded application has started.
	* [06/02/2017 11:20:58] : Installation of application has successfully completed.

ERROR DETAILS
	Following errors were detected during this operation.
	* [06/02/2017 11:20:58] System.ArgumentException
		- Value does not fall within the expected range.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.NativeMethods.CorLaunchApplication(UInt32 hostType, String applicationFullName, Int32 manifestPathsCount, String[] manifestPaths, Int32 activationDataCount, String[] activationData, PROCESS_INFORMATION processInformation)
			at System.Deployment.Application.ComponentStore.ActivateApplication(DefinitionAppId appId, String activationParameter, Boolean useActivationParameter)
			at System.Deployment.Application.SubscriptionStore.ActivateApplication(DefinitionAppId appId, String activationParameter, Boolean useActivationParameter)
			at System.Deployment.Application.ApplicationActivator.Activate(DefinitionAppId appId, AssemblyManifest appManifest, String activationParameter, Boolean useActivationParameter)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)

COMPONENT STORE TRANSACTION DETAILS
	* Transaction at [06/02/2017 11:20:58]
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Installed
			- HRESULT: 0x0
			- Manifest: 3KROTT2C.T6P.application
		+ System.Deployment.Internal.Isolation.StoreOperationSetDeploymentMetadata
			- Status: Set
			- HRESULT: 0x0
		+ System.Deployment.Internal.Isolation.StoreOperationSetDeploymentMetadata
			- Status: Set
			- HRESULT: 0x0
		+ System.Deployment.Internal.Isolation.StoreTransactionOperationType (27)
			- HRESULT: 0x0

**Comment by onovotny** [comment]
ClickOnce is unstable. Recommendation is to use the Windows Store app (same as the desktop) if you have Windows 10 Anniversary Update or later: https://www.microsoft.com/store/apps/9wzdncrdmdm3
