### ISSUE TITLE
Crash while/after ClickOnce update

### ISSUE THREAD

**Issue by Sventric** [NuGetPackageExplorer/NuGetPackageExplorer#172]
Hi! Thanks for reporting this feature/bug/question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

**Type** (choose one):

- Bug

**NPE version**: (e.g. 3.12) (see Help -> about)

??

**Installed from**: ClickOnce

In case of a BUG:

- What is the current result?

INFO PLATFORMVERSIE
	Windows 			: 6.1.7601.65536 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.6.1590.0 built by: NETFXREL2
	clr.dll 			: 4.6.1590.0 built by: NETFXREL2
	dfdll.dll 			: 4.6.1590.0 built by: NETFXREL2
	dfshim.dll 			: 4.0.31106.0 (Main.031106-0000)

BRONNEN
	Implementatie-url			: file:///C:/deploy/Movares.Toolbox.Core.0.1.1.4-beta.nupkg
						Server		: Microsoft-IIS/8.0,CDS01
						X-Powered-By	: ASP.NET
						X-AspNet-versie: 4.0.30319
	Url implementatieprovider		: https://npe.codeplex.com/releases/clickonce/NuGetPackageExplorer.application
	Toepassing-url			: https://npe.codeplex.com/releases/clickonce/Application%20Files/NuGetPackageExplorer_3_21_0_0/NuGetPackageExplorer.exe.manifest
						Server		: Microsoft-IIS/8.0,CDS01
						X-Powered-By	: ASP.NET
						X-AspNet-versie: 4.0.30319

IDENTITEITEN
	Toepassingsidentiteit		: NuGetPackageExplorer.exe, Version=3.21.0.0, Culture=neutral, PublicKeyToken=0000000000000000, processorArchitecture=x86, type=win32

FOUTSAMENVATTING
	Hieronder ziet u een overzicht van de fouten. Verderop in het logboek vindt u nadere details over deze fouten.
	* Activering van C:\deploy\Movares.Toolbox.Core.0.1.1.4-beta.nupkg heeft tot een uitzondering geleid. De volgende berichten voor mislukte acties zijn aangetroffen:
		+ Een apparaat dat op het systeem is aangesloten, werkt niet. (Uitzondering van HRESULT: 0x8007001F)

SAMENVATTING MISLUKTE TRANSACTIES ONDERDELENARCHIEF
	Er zijn geen transactiefouten aangetroffen.

WAARSCHUWINGEN
	* Het manifest voor deze toepassing heeft geen handtekening. Handtekeningcontrole wordt genegeerd.
	* Het manifest voor deze toepassing heeft geen handtekening. Handtekeningcontrole wordt genegeerd.

VOORTGANGSSTATUS BEWERKING
	* [13-02-2017 11:31:06] : De activering van C:\deploy\Movares.Toolbox.Core.0.1.1.4-beta.nupkg is gestart.
	* [13-02-2017 11:31:06] : Bezig met uitvoeren van vereiste updatecontrole, zoals is aangegeven in de implementatie.
	* [13-02-2017 11:31:08] : Verbruiken van nieuwe update.
	* [13-02-2017 11:31:12] : De installatie van de toepassing is gestart.
	* [13-02-2017 11:31:13] : Verwerking van het toepassingsmanifest is voltooid.
	* [13-02-2017 11:31:15] : Compatibele runtimeversie 4.0.30319 gevonden.
	* [13-02-2017 11:31:15] : Aanvragen van vertrouwen en detectie van platform zijn voltooid.
	* [13-02-2017 11:31:37] : Downloaden van abonnementsafhankelijkheden is voltooid.
	* [13-02-2017 11:31:37] : Toewijzing van de gedownloade toepassing is gestart.

FOUTDETAILS
	De volgende fouten zijn aangetroffen bij deze bewerking.
	* [13-02-2017 11:31:38] System.Runtime.InteropServices.COMException
		- Een apparaat dat op het systeem is aangesloten, werkt niet. (Uitzondering van HRESULT: 0x8007001F)
		- Bron: System.Deployment
		- Stack-tracering:
			bij System.Deployment.Internal.Isolation.IStateManager.Scavenge(UInt32 Flags, UInt32& Disposition)
			bij System.Deployment.Application.ComponentStore.SubmitStoreTransaction(StoreTransactionContext storeTxn, SubscriptionState subState)
			bij System.Deployment.Application.ComponentStore.SubmitStoreTransactionCheckQuota(StoreTransactionContext storeTxn, SubscriptionState subState)
			bij System.Deployment.Application.ComponentStore.RemoveSubscription(SubscriptionState subState)
			bij System.Deployment.Application.SubscriptionStore.UninstallSubscription(SubscriptionState subState)
			bij System.Deployment.Application.SubscriptionStore.CommitApplication(SubscriptionState& subState, CommitApplicationParams commitParams)
			bij System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			bij System.Deployment.Application.ApplicationActivator.ConsumeUpdatedDeployment(SubscriptionState& subState, ActivationDescription actDesc)
			bij System.Deployment.Application.ApplicationActivator.PerformDeploymentUpdate(SubscriptionState& subState, String& errorPageUrl)
			bij System.Deployment.Application.ApplicationActivator.ProcessOrFollowExtension(Uri associatedFile, String textualSubId, String deploymentProviderUrlFromExtension, String& errorPageUrl, TempFile& deployFile)
			bij System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			bij System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)

TRANSACTIEDETAILS ONDERDELENARCHIEF
	* Transactie bij [13-02-2017 11:31:38]
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Installed
			- HRESULT: 0x0
			- Manifest: 7RVDL2PY.04R.application
		+ System.Deployment.Internal.Isolation.StoreOperationSetDeploymentMetadata
			- Status: Set
			- HRESULT: 0x0
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Installed
			- HRESULT: 0x0
			- Manifest: NuGetPackageExplorer.exe.manifest
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Installed
			- HRESULT: 0x0
			- Bestand: Resources\fxAssemblies.txt
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Installed
			- HRESULT: 0x0
			- Bestand: NuGetPackageExplorer.exe.config
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Installed
			- HRESULT: 0x0
			- Bestand: nuspec.ico
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Installed
			- HRESULT: 0x0
			- Bestand: nupack.ico
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Installed
			- HRESULT: 0x0
			- Manifest: Humanizer.dll.genman
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Installed
			- HRESULT: 0x0
			- Bestand: Humanizer.dll
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Installed
			- HRESULT: 0x0
			- Manifest: CodeExecutor.dll.genman
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Installed
			- HRESULT: 0x0
			- Bestand: CodeExecutor.dll
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Installed
			- HRESULT: 0x0
			- Manifest: Ookii.Dialogs.Wpf.dll.genman
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Installed
			- HRESULT: 0x0
			- Bestand: Ookii.Dialogs.Wpf.dll
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Installed
			- HRESULT: 0x0
			- Manifest: Core.dll.genman
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Installed
			- HRESULT: 0x0
			- Bestand: Core.dll
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Installed
			- HRESULT: 0x0
			- Manifest: NuGetPackageExplorer.Types.dll.genman
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Installed
			- HRESULT: 0x0
			- Bestand: NuGetPackageExplorer.Types.dll
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Installed
			- HRESULT: 0x0
			- Manifest: NuGetPackageExplorer.exe.genman
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Installed
			- HRESULT: 0x0
			- Bestand: NuGetPackageExplorer.exe
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Installed
			- HRESULT: 0x0
			- Manifest: ICSharpCode.AvalonEdit.dll.genman
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Installed
			- HRESULT: 0x0
			- Bestand: ICSharpCode.AvalonEdit.dll
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Installed
			- HRESULT: 0x0
			- Manifest: Humanizer.resources.dll.genman
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Installed
			- HRESULT: 0x0
			- Bestand: Humanizer.resources.dll
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Installed
			- HRESULT: 0x0
			- Manifest: Microsoft.Web.XmlTransform.dll.genman
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Installed
			- HRESULT: 0x0
			- Bestand: Microsoft.Web.XmlTransform.dll
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Installed
			- HRESULT: 0x0
			- Manifest: PackageViewModel.dll.genman
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Installed
			- HRESULT: 0x0
			- Bestand: PackageViewModel.dll
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Installed
			- HRESULT: 0x0
			- Manifest: NuGet.Core.dll.genman
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Installed
			- HRESULT: 0x0
			- Bestand: NuGet.Core.dll
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Installed
			- HRESULT: 0x0
			- Manifest: GrayscaleEffect.dll.genman
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Installed
			- HRESULT: 0x0
			- Bestand: GrayscaleEffect.dll
		+ System.Deployment.Internal.Isolation.StoreOperationInstallDeployment
			- Status: Installed
			- HRESULT: 0x0
			- Toep.-id: https://npe.codeplex.com/releases/clickonce/NuGetPackageExplorer.application#NuGetPackageExplorer.application, Version=3.21.0.0, Culture=neutral, PublicKeyToken=0000000000000000, processorArchitecture=x86
		+ System.Deployment.Internal.Isolation.StoreOperationSetDeploymentMetadata
			- Status: Set
			- HRESULT: 0x0
		+ System.Deployment.Internal.Isolation.StoreTransactionOperationType (27)
			- HRESULT: 0x0
	* Transactie bij [13-02-2017 11:31:38]
		+ System.Deployment.Internal.Isolation.StoreOperationSetDeploymentMetadata
			- Status: Set
			- HRESULT: 0x0
		+ System.Deployment.Internal.Isolation.StoreOperationUninstallDeployment
			- Status: Uninstalled
			- HRESULT: 0x0
			- Toep.-id: https://npe.codeplex.com/releases/clickonce/NuGetPackageExplorer.application#NuGetPackageExplorer.application, Version=3.9.0.0, Culture=neutral, PublicKeyToken=0b2031bd070eaaee, processorArchitecture=x86
		+ System.Deployment.Internal.Isolation.StoreOperationSetDeploymentMetadata
			- Status: Set
			- HRESULT: 0x0
		+ System.Deployment.Internal.Isolation.StoreTransactionOperationType (27)
			- HRESULT: 0x0

**Comment by 304NotModified** [comment]
Unfortunately Clickonce is very unstable and we get these problems regular.  I don't think we could fix this

**Comment by onovotny** [comment]
ClickOnce is unstable. Recommendation is to use the Windows Store app (same as the desktop) if you have Windows 10 Anniversary Update or later: https://www.microsoft.com/store/apps/9wzdncrdmdm3
