### ISSUE TITLE
Character encoding error in the Owners property (package metadata)

### ISSUE THREAD

**Issue by totht91** [NuGetPackageExplorer/NuGetPackageExplorer#177]
**Type** (choose one):

- Bug

**NPE version**: (e.g. 3.21.0.0) (see Help -> about)

**Installed from**: Windows Store

In case of a BUG:

- What is the current result?
![image](https://cloud.githubusercontent.com/assets/8333960/24362909/85aa1920-130e-11e7-93d6-4af3398bce2b.png)

- What is the expected result?
'ó' character like above

- Is there a package on Nuget.org which shows the bug?
https://www.nuget.org/packages/TextTemplating/

**Comment by 304NotModified** [comment]
Thanks for reporting!

**Comment by 304NotModified** [comment]
Looking at this now

**Comment by 304NotModified** [comment]
Checked this, the .nuspec is wrong.

(unzip file and check .nuspec file in texteditor)
![image](https://cloud.githubusercontent.com/assets/5808377/24472196/227bb210-14c5-11e7-8841-6fbeb2ddb9c1.png)


Dunno how you created the package, but if I edit it NPE, it works:

![image](https://cloud.githubusercontent.com/assets/5808377/24472188/182e28b0-14c5-11e7-8f91-9f874c00ed37.png)

**Comment by 304NotModified** [comment]
Or is this a bug of nuget.org?

PS: @totht91 nice package. You are aware that dnx and dnxcore50 is legacy? (replace it with netstandard)

**Comment by totht91** [comment]
Thanks, Yes I know I just don't have time to port to .NET Core RTM.
I did not create nuspec file, this is generated I think. And in nuget.org the owner of this packege is "Tibcsi" which is my nick but I don't know where am I submitted this or how can I change this.

**Comment by totht91** [comment]
I will give a try to port to the latest .NET CLI. I will investigate on this bug again.

**Comment by 304NotModified** [comment]
You could update the `<owner>` tag with NPE, in the nuspec and also (I think) in project.json,

Dunno if nuget.org accepts it.
