### ISSUE TITLE
Centennial version crashes on "Open a local package (Ctrl+O)"

### ISSUE THREAD

**Issue by dpodder** [NuGetPackageExplorer/NuGetPackageExplorer#179]
**Type**: Bug
**NPE version**: 3.21.0.0
**Installed from**: Windows Store

**OS Version**: Win10 Anniversary Update (14393.953)

- What is the current result?
  * Application crashes (consistent repro, severe blocking issue)
![nugetpackagemanager_issue](https://cloud.githubusercontent.com/assets/2354388/24377190/58d06bf4-12f3-11e7-8f8d-8a1abec0ae55.PNG)

- What is the expected result?
  * No crash
- Please post full exception details in case of an Exception (message, stacktrace, inner exceptions)
```
    Faulting application name: NuGetPackageExplorer.exe, version: 3.21.0.0, time stamp: 0x58d585a2
    Faulting module name: GROOVEEX.DLL, version: 16.0.7927.1009, time stamp: 0x58cbe268
    Exception code: 0xc0000005
    Fault offset: 0x0004a215
    Faulting process id: 0x39ac
    Faulting application start time: 0x01d2a738f91b78a1
    Faulting application path: C:\Program Files\WindowsApps\50582LuanNguyen.NuGetPackageExplorer_3.21.6.0_neutral__w6y2tyx5bpzwa\win32\NuGetPackageExplorer.exe
    Faulting module path: C:\Program Files (x86)\Microsoft Office\root\Office16\GROOVEEX.DLL
    Report Id: 750849a3-15b5-4b0d-a09e-0dc04d9700e8
    Faulting package full name: 50582LuanNguyen.NuGetPackageExplorer_3.21.6.0_neutral__w6y2tyx5bpzwa
    Faulting package-relative application ID: NuGetPackageExplorer
```
- Are there any work arrounds? yes/no
    Use ClickOnce instead
- Is there a version in which it did worked? 
    No for Centennial; works fine when installed via ClickOnce
- Is there a package on Nuget.org which shows the bug?
    N/A, just install from the store

**Comment by onovotny** [comment]
Is there a package that fails for you? the version in the store is the same as the ClickOnce version. The file with the error looks like Groove (OneDrive for Business)'s shell extension. Not sure what we can do about that.

**Comment by dpodder** [comment]
I get the crash right as soon as the file open dialog pops up; there's no chance for me to even select a package. ☹️ If the packages are truly identical then this may be a bug in OneDrive for Business, or maybe with centennial... I'll see if I can dig deeper.

**Comment by onovotny** [comment]
Technically the binaries were rebuilt for publish, but they're from the same source and built with VS 2015 Update 3. I'd love to know what the difference is but there's nothing we did differently.

**Comment by rido-min** [comment]
This is a known Office Insiders bug. It has been already fixed and will be deployed shortly. In the meantime you can avoid it renaming the Grooveex.dll.

```
for /r "%ProgramFiles(x86)%\Microsoft Office\root" %i in (GROOVEEX.*) do ren "%i" *.bad
for /r "%ProgramFiles%\Microsoft Office\root" %i in (GROOVEEX.*) do ren "%i" *.bad
```

**Comment by dpodder** [comment]
Thanks @rido-min! I can confirm that the workaround resolves the issue.
@onovotny feel free to close the issue if/as deemed appropriate. Cheers!

**Comment by 304NotModified** [comment]
thanks @rido-min 

I have added a FAQ to the wiki: https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/wiki
