### ISSUE TITLE
Main page as GitHub page?

### ISSUE THREAD

**Issue by caioproiete** [NuGetPackageExplorer/NuGetPackageExplorer#18]
([originally created](https://github.com/dsplaisted/NuGetPackageExplorer/issues/8) by @304NotModified)

Main site as GitHub page instead of Codeplex.

**Comment by dsplaisted** [comment]
You mean like nugetpackageexplorer.github.io (or possibly just npe.github.io)?  Sounds good to me!  Who wants to create the page? :-)

**Comment by 304NotModified** [comment]
We have already http://nugetpackageexplorer.github.io/NuGetPackageExplorer.

Will try to move it to http://nugetpackageexplorer.github.io/

npe.github.io isn't possible, as the npe name is already claimed

**Comment by 304NotModified** [comment]
Re-henerated a simple template to http://nugetpackageexplorer.github.io/

This the repository https://github.com/NuGetPackageExplorer/NuGetPackageExplorer.github.io (no other name or branch is possible).

Now we have to move the content and maybe style the stuff a bit.

**Comment by caioproiete** [comment]
I'd be happy to help. Are you open to using Jekyll (and leverage gh-pages all in one repo) or something else?

**Comment by 304NotModified** [comment]
> 'd be happy to help. 

Thanks in advance!

> Are you open to using Jekyll (and leverage gh-pages all in one repo) or something else?

I'm not sure what you mean. Do you mean moving the site to this repo (https://github.com/NuGetPackageExplorer/NuGetPackageExplorer) as "gh-pages" branch? I don't think that's possible with the URL  http://nugetpackageexplorer.github.io/? (tried it, but didn't work).

Jekyll is fine to me :)

**Comment by caioproiete** [comment]
> I'm not sure what you mean

I meant storing a Jekyll site in the `master` branch of the new repo you've created (https://github.com/NuGetPackageExplorer/NuGetPackageExplorer.github.io) and let GitHub pages generate the site and continue to make it available via http://nugetpackageexplorer.github.io as it happens now.

Like this repo here: https://github.com/sandboxorg/sandboxorg.github.io which has a Jekyll site that is automatically built by GitHub pages on every push, and served via http://sandboxorg.github.io

Jekyll would be my first choice, but wanted to check if you guys were thinking about sticking with HTML files written by hand, or perhaps use some [other static site generator](http://www.staticgen.com) and then store it in a different repo and manually built/publish to http://nugetpackageexplorer.github.io (or build via AppVeyor or similar).

---

> Jekyll is fine to me :)

Great. I'll send a PR in the next few days.
