### ISSUE TITLE
Clickonce installer broken

### ISSUE THREAD

**Issue by Alexx999** [NuGetPackageExplorer/NuGetPackageExplorer#183]
When trying to update I've got following error:

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of C:\Users\alexx\Desktop\NuGet Package Explorer.appref-ms| resulted in exception. Following failure messages were detected:
		+ Downloading https://npe.codeplex.com/releases/clickonce/Application Files/NuGetPackageExplorer_3_21_0_0/NuGetPackageExplorer.exe.manifest did not succeed.
		+ The remote server returned an error: (500) Internal Server Error.

When trying to open that URL in browser it redirects to https://www.codeplex.com/site/notallowed
I'm not sure if it's for everyone or just for me though.

**Comment by 304NotModified** [comment]
See https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/wiki#installing-with-clickonce-failed

**Comment by 304NotModified** [comment]
Closing this one as ClickOnce is unstable and we are removing ClickOnce in the (near) feature. Sorry about the inconvenience, but we can't fix it.
