### ISSUE TITLE
Not working in W10  high contrast enabled

### ISSUE THREAD

**Issue by jmroyb** [NuGetPackageExplorer/NuGetPackageExplorer#188]
Hi folks,

I intalled v3.21 in Windows 10 using High Contrast due my visually impaired. 

Menus, text are not shown. It causes I can't use NPE...

You can test it pressing `left Alt`+`left Shift`+`Print Screen`.

Thank for understanding

**Comment by 304NotModified** [comment]
print screens:

![image](https://cloud.githubusercontent.com/assets/5808377/25053319/e2432c16-2156-11e7-9047-4fcc1b797e8b.png)

![image](https://cloud.githubusercontent.com/assets/5808377/25053327/efa87302-2156-11e7-941b-08330936f227.png)

![image](https://cloud.githubusercontent.com/assets/5808377/25053331/f7a6f006-2156-11e7-9665-f26b0f4c8e36.png)

![image](https://cloud.githubusercontent.com/assets/5808377/25053339/003708be-2157-11e7-878e-ee214c98462c.png)

![image](https://cloud.githubusercontent.com/assets/5808377/25053352/0c8b485a-2157-11e7-98e4-487907330268.png)

The start screen isn't in high contrast at all?

![image](https://cloud.githubusercontent.com/assets/5808377/25053364/1f853bf0-2157-11e7-8cd8-84f260dbaa83.png)

**Comment by 304NotModified** [comment]
Unfortunately I don't have any experience with high contract mode, so any help would be highly appreciated!

**Comment by 304NotModified** [comment]
helpful resource: https://blogs.msdn.microsoft.com/wpf/2010/11/30/systemcolors-reference/

**Comment by jmroyb** [comment]
Hi,

I'm in trouble with these colors combinations:
- white foreground + gray background
- dark red/dark blue foreground + black background.

High Contrast Black is the solution. I think this is the combination that VS (2013 and higher) uses
when HC is on.

In my WPF apps I use two themes: Dark and Light. By default I load Dark. This theme is not a real HC but it helps me developing.

I detect HC changes at App (where I set themes there):

`
        public App()
        {
            Microsoft.Win32.SystemEvents.UserPreferenceChanged += (s, e) =>
            {
                if (e.Category != Microsoft.Win32.UserPreferenceCategory.Accessibility)
                    return;

                if (SystemParameters.HighContrast == true)
                    System.Diagnostics.Debug.WriteLine("UserPreferenceChanged: HC is ON");
                else
                    System.Diagnostics.Debug.WriteLine("UserPreferenceChanged: HC is OFF");
            };

            if (SystemParameters.HighContrast == true)
                System.Diagnostics.Debug.WriteLine("Startup: HC is ON");
            else
                System.Diagnostics.Debug.WriteLine("Startup: HC is OFF");
        }
`

Hope this can help you

**Comment by petterlabraaten** [comment]
There is a lot of "home made" styling in the application and as far as I can see the easiest would be to strip it all out and use standard system colors instead, and we would get high contrast more or less for free.

I've done an early attempt here:
https://github.com/petterlabraaten/NuGetPackageExplorer/tree/accessibility

**Comment by jmroyb** [comment]
Hi Petter:

Good job! Just few issues to solve:

1. see dark blue text: can not read when background is black. A light colour should be more comfortable instead dark colour (blue in this case).

![imatge](https://cloud.githubusercontent.com/assets/4932314/25555075/c4b2c444-2cdd-11e7-9e1f-a1a6693a119d.png)

2. Same edit window :
![imatge](https://cloud.githubusercontent.com/assets/4932314/25555117/8336a570-2cde-11e7-931d-245624ba1b7a.png)

Changing Syntax scheme to Patch or Plain Text I can read it comfortable:

![imatge](https://cloud.githubusercontent.com/assets/4932314/25555134/bc9672a0-2cde-11e7-857f-461fc5a0f5cb.png)

Do not detect other issues.

Thanks a million!

**Comment by petterlabraaten** [comment]
I've made some changes to the things @jmroyb  pointed out. Have a look.

In my opinion colors and font sizes should be handled by the OS and not by the application itself. It's a tool that doesn't rely on a lot of fanzy colors and themes.

**Comment by 304NotModified** [comment]
hey @petterlabraaten 
thanks for the demo.

Any way, I looked at this also, but it has a huge effect on the default colors? Could we make it into a setting?

**Comment by 304NotModified** [comment]
FYI created a PR to see the changes and to make it easier to find your branch :)

https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/pull/194

**Comment by jmroyb** [comment]
Hi @petterlabraaten,

Fantastic! Now it is very confortable. When HC is ON Plain Tex as default, ligth forecolor/black brackground and large font. 

Thank you very much for your work

**Comment by petterlabraaten** [comment]
@304NotModified I guess there are three options (probably more, but this isn't my area at all):

1) The way I did, using SystemColors. IMO this will be more maintainable in the long run, but we might not get the exact theme and colors that we're used to.

2) Duplicate the style and have one for normal and one for high contrast mode. Quick and dirty and will give us twice the amount of styles to maintain.

3) Extract all colors and backgrounds into a seperate resource dictionary , one DefaultColors.xaml, and one HighContrastColors.xaml then rewrite current styles to reference these colors instead of the hard coded ones that are there today. There are like 90 or so hardcoded hex-colors just for the menus and toolbars, and if we add named colors and special background images it will ba a 'small' initial job.

Anyway, I can have a got at reproducing my "demo" using option three. When I find time.

**Comment by jmroyb** [comment]
Hi folks,

NPE 3.23 still does not implements High Contrast. When it will be available?

Cheers
