### ISSUE TITLE
Windows Store version's icon appearance is inconsistent with other apps when pinned to Start

### ISSUE THREAD

**Issue by bording** [NuGetPackageExplorer/NuGetPackageExplorer#189]
**Type**: Bug

**NPE version**: 3.22.0

**Installed from**: Windows Store

When the app's icon is pinned to Start as a tile, the icon is overly large compared to other tiles. It is also missing the application name text.

Medium-sized tile:
![icon](https://cloud.githubusercontent.com/assets/753669/25292265/5f2d36ee-26a3-11e7-9ab4-bf68bf400dfe.png)

The other tile sizes have similar issues. For example, the large-sized tile looks like this:
![large-icon](https://cloud.githubusercontent.com/assets/753669/25292411/f980d5ac-26a3-11e7-95fb-702cd2ee7cdc.png)

While this obviously doesn't impact actual functionality, it would be nice to see this improved!

**Comment by onovotny** [comment]
This is actually by-design. We use the full icon area whereas the legacy Win32 apps are constrained to smaller sizes.

**Comment by bording** [comment]
I'd much rather see the name and icon and not just an icon. It would be nice if the text didn't overlap the icon, also.

For example, these apps are all UWP/Store apps and they still show both:

![image](https://user-images.githubusercontent.com/753669/32922367-dfd411fe-caff-11e7-9848-2abe5dc9df7c.png)

**Comment by 304NotModified** [comment]
@bording I think also that's an improvement!
