### ISSUE TITLE
Migrate codeplex issues / discussions?

### ISSUE THREAD

**Issue by caioproiete** [NuGetPackageExplorer/NuGetPackageExplorer#19]
([originally created](https://github.com/dsplaisted/NuGetPackageExplorer/issues/7) by @304NotModified)

**Comment by 304NotModified** [comment]
@dsplaisted please for opinion on this

**Comment by dsplaisted** [comment]
I don't think we need to migrate the old discussions.  If there are issues on the codeplex site that we want to address, then we should file those here.
