### ISSUE TITLE
IS THERE ANY CHANCE WE CAN CHANGE THE ALL CAPS MENU OPTIONS?

### ISSUE THREAD

**Issue by NickCraver** [NuGetPackageExplorer/NuGetPackageExplorer#190]
HELLO PEOPLE!

WOULD IT BE ACCEPTABLE IF I SUBMITTED A PULL REQUEST TO CHANGE THE ALL CAPS MENU TO TITLE CASE?

NEED: SANITY
USE CASE: STAYING SANE

**Comment by ghuntley** [comment]
🐼

**Comment by NickCraver** [comment]
THANK YOU!
