### ISSUE TITLE
Error while installing new package via Visual Studio 2017

### ISSUE THREAD

**Issue by TedSharp** [NuGetPackageExplorer/NuGetPackageExplorer#195]
- Bug

**NPE version**: (e.g. 3.12) (see Help -> about)

**Installed from**: Visual Studio 2017

In Visual Studio 2017 i want to install the EntityFramework package to my project. I get the following error message:
"Der Dienstindex für die Quelle "https://api.nuget.org/v3/index.json" konnte nicht geladen werden.
Fehler beim Senden der Anforderung.
Die Verbindung mit dem Remoteserver kann nicht hergestellt werden.
Der Zugriff auf einen Socket war aufgrund der Zugriffsrechte des Sockets unzulässig 93.184.221.200:443"

Even the package resources can't get from nuget.org.

Can someone help me?
Thanks!

**Comment by svick** [comment]
This repo is for NuGet Package Explorer, it's not for general issues with NuGet, so your issue does not belong here.

That being said, based on Google Translate of the error message, you likely have some kind of network issue. If it doesn't fix itself after a while, it means there's probably something wrong with your network.

**Comment by 304NotModified** [comment]
Agree on @svick . Closing this as there isn't something we can do about it.
