### ISSUE TITLE
NuGet package cannot be opened by PackageExplorer when it contains a file that does not have an extension

### ISSUE THREAD

**Issue by alinapopa** [NuGetPackageExplorer/NuGetPackageExplorer#197]
Using Visual Studio 2017 and the new project system.
File is included as:
` <Content Include="..\..\LICENSE" />`
The resulting NuGet package gives the following error when trying to open it with NuGet Package Explorer:
![image](https://cloud.githubusercontent.com/assets/8061142/25688452/1b37826a-3034-11e7-8bce-c1662893c4dd.png)
This is caused by LICENSE file not having an extension (does not happen if file is renamed to LICENSE.txt or another extension; also happens with any file that does not have an extension).
Repro project: https://github.com/alinapopa/Windsor/tree/NuGetReproFileWNoExtension
Link to resulting packages: https://ci.appveyor.com/project/alinapopa/windsor/build/1.0.90/artifacts

https://github.com/NuGet/Home/issues/5158

**Comment by jjdotcc** [comment]
I've been testing this on NPE 3.22 and I can't reproduce it. what version of NPE are you using?

**Comment by alinapopa** [comment]
It's version 3.22.
The link to packages was wrong (it was pointing to the "latest" build which is no longer latest), I fixed it up:
https://ci.appveyor.com/project/alinapopa/windsor/build/1.0.90/artifacts

**Comment by 304NotModified** [comment]
This is also not allowed on nuget.org?

**Comment by jjdotcc** [comment]
Thank you, I was now able to replicate the issue. After looking into this i can see it's caused during the build process of Windsor. It appears to be generating an invalid PartName within the ContentTypes. 

![image](https://cloud.githubusercontent.com/assets/7555037/26180627/7ce45b8a-3b62-11e7-8502-2a13e2d106c9.png)

To fix this you will need to replace the following within the common.props file;
`<Content Include="..\..\LICENSE" />`
with
`    <Content Include="..\..\LICENSE">
      <PackagePath></PackagePath>
    </Content>`
 
Let me know how you get on.

**Comment by alinapopa** [comment]
Yes that works. Thanks @jjdotcc !
