### ISSUE TITLE
Bad links

### ISSUE THREAD

**Issue by kaby76** [NuGetPackageExplorer/NuGetPackageExplorer#198]
The NuGetPackageExplorer has moved to Github.com, and this repository seems active. But, if one visits the webpage https://github.com/NuGetPackageExplorer/NuGetPackageExplorer , the description reads "Create, update and deploy Nuget Packages with a GUI https://npe.codeplex.com" -- which points to the old Codeplex site (and that page says it's moved to Github). I'm not sure why the old link should be in the repository description. This repo is the current source, and downloads are through the Windows Store. Good tool, BTW.

**Comment by 304NotModified** [comment]
Not all the documentation has been moved yet, but I will remove the link.

**Comment by 304NotModified** [comment]
thanks for reporting!
