### ISSUE TITLE
Improve Semver 2.0.0 Support

### ISSUE THREAD

**Issue by loic-sharma** [NuGetPackageExplorer/NuGetPackageExplorer#199]
Hello,

Say I have the following nuspec file:

```
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
  <metadata>
    <id>Loshar.Dependency</id>
    <version>1.2.3-beta.123+test</version>
    <authors>Loic Sharma</authors>
    <owners>Loic Sharma</owners>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>Package Description</description>
    <dependencies>
      <group targetFramework=".NETStandard1.5">
        <dependency id="NETStandard.Library" version="1.6.1" exclude="Build,Analyzers" />
      </group>
    </dependencies>
  </metadata>
</package>
```

NPE 3.22.0.0 will display the version as `1.2.3-beta.123` when instead it should be `1.2.3-beta.123+test`.

**Comment by 304NotModified** [comment]
Afaik the + isnt allowed on nuget.org?

**Comment by loic-sharma** [comment]
The build metadata (segments after `+`) are being added in! [Here is the issue tracking this for NuGet's gallery.](https://github.com/NuGet/NuGetGallery/issues/3547)

**Comment by onovotny** [comment]
This should be fixed in #240

**Comment by onovotny** [comment]
Fixed in latest, thanks!

**Comment by Spiralis** [comment]
Which version is this fixed for? 
I just tried 3.25.0, and it does not show the additional build-info (i.e. `+test` as in the original request).

**Comment by onovotny** [comment]
This is fixed in 6.0.

**Comment by Spiralis** [comment]
Ok, thanks. It seems I am not up to speed on the roadmap. What is the plans in regards to going from 3.x to 6.x?

**Comment by onovotny** [comment]
There's not really a lot more, you can see the remaining issues here: https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/milestone/18

I expect something around late dec/early jan.

**Comment by Spiralis** [comment]
Not that it matters, but by curiosity: Why the "violent" version-bump?

**Comment by onovotny** [comment]
The Types NuGet package is currently at 5.0. This let's us unify the versions.
