### ISSUE TITLE
Update NuGetPackageExplorer.Types

### ISSUE THREAD

**Issue by 304NotModified** [NuGetPackageExplorer/NuGetPackageExplorer#201]
Update NuGetPackageExplorer.Types to V5

alpha 
[NuGetPackageExplorer.Types.5.0.0-alpha2.nupkg.zip](https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/files/998793/NuGetPackageExplorer.Types.5.0.0-alpha2.nupkg.zip)

**Comment by 304NotModified** [comment]
@dotnetjunky could you give access to publish the NuGetPackageExplorer.Types package?

**Comment by 304NotModified** [comment]
@onovotny could you release a new version of this? I don't have publish rights to https://www.nuget.org/packages/NuGetPackageExplorer.Types/

**Comment by onovotny** [comment]
Yeah, will take care of it. It is 5.0. In my PR, I'm bumping all the versions to 6 just to consolidate and have the same version for the API and the app.

**Comment by 304NotModified** [comment]
another option is to rename NuGetPackageExplorer.Types and move to 4.0

**Comment by onovotny** [comment]
Either way... there's really not a lot of downloads of the package

https://www.nuget.org/packages/NuGetPackageExplorer.Types/

I don't think the version numbers matter too much, long as they're aligned.

**Comment by 304NotModified** [comment]
> I don't think the version numbers matter too much, long as they're aligned.

But only if it's really possible to align things. Bumping up a major version only for aligning is semver-bad IMO. 

Sorry, semver fan here.

**Comment by onovotny** [comment]
SemVer is a means to an end. Having a consistent experience counts too. In this case, we're changing the dependencies drastically, so it's a major version. Whether it skips one or two doesn't really seem to matter to me.

**Comment by 304NotModified** [comment]
> Whether it skips one or two doesn't really seem to matter to me.

That's not the point. If you're making a new major version of NPE (e.g. 7), but there aren't breaking changes in NuGetPackageExplorer.Types, then it's bad to move it to 7

**Comment by onovotny** [comment]
There are breaking changes to everything in this case...because NuGet.client is drastically different.

**Comment by 304NotModified** [comment]
> There are breaking changes to everything in this case...because NuGet.client is drastically different.

Yes I'm aware of that. It's more a case against aligning versions, because:

- it's hard (or sometimes impossible) to keep the versions aligned
- we could bump a major version without a breaking change.

**Comment by onovotny** [comment]
One thing to consider is that NPE is an app and the Types library is in direct support of that. I'm not sure how much sense it is to version it independently. If you want to write an add-in for NPE, then you need the corresponding types version; keeping the version the same might help re-enforce that.

As far as keeping the versions aligned, that's easy since the version.json at the root controls all of it.

**Comment by onovotny** [comment]
the 5.0 package is now on nuget.org...pending indexing, etc.
