### ISSUE TITLE
Release MSI Build Package

### ISSUE THREAD

**Issue by mancoast** [NuGetPackageExplorer/NuGetPackageExplorer#202]
Greetings Fellow Nuget Collaborators,

This issue **Type** chooses a Feature request.

**NPE version**: forall future release

**Installed from**: MSI Build Package

For this case of a FEATURE REQUEST:
 
We need Microsoft Installer Build Packages for Windows Server 2016.
I do not feel comfortable with unsigned installers.

Please provide a signed Microsoft Installer Build Package.

Thanks,
coast

**Comment by 304NotModified** [comment]
Unfortunately a code signing cert is expensive.

**Comment by mancoast** [comment]
If we cannot proceed with the certificate signage, I have an alternative suggestion:
Build the MSI on appveyor, display the SHA1 during cloud compilation.
I can then verify the SHA1 of the MSI installer internally.

**Comment by 304NotModified** [comment]
It's this also fine with a chocolatey package? That one is build from appveyor.

**Comment by mancoast** [comment]
Cannot install chocolatey on some Servers; it is not feasible due to policy.
It's easier to see allowances for installation of MSI packages.
These MSI packages require cloud verification.

**Comment by 304NotModified** [comment]
Another option is build it yourself? The code is open.

**Comment by mancoast** [comment]
That is what we do in the current state.
In the future it would be nice to have an MSI for imaging.

There is no Windows Store for Server 2016.
The chocolately packages are convenient, but too much security risk.

**Comment by fredatgithub** [comment]
I compile and zip the version 3.24 for Windows if any body is interested
[Windows executable v3.24](https://github.com/fredatgithub/NuGetPackageExplorer/releases/download/V3.24/NuGetPackageExplorer-v3.24.zip)

**Comment by onovotny** [comment]
We can provide a zip version that you can use, there's really not much to install, would that work?

**Comment by 304NotModified** [comment]
I think a zip is also a good choice, we could make it from appveyor and create a Github release (with zip) automatically.

**Comment by mancoast** [comment]
Thanks! That would be perfect.

**Comment by onovotny** [comment]
@mancoast Can Windows Server 2016 sideload appx's like Windows 10 AU+ can?

Can you try this link? https://nugetpackageexplorer.blob.core.windows.net/nightly/PackageExplorer.Package.Nightly.appxbundle 

Download that to your server and double-click it. It should open up an install utility...

**Comment by mancoast** [comment]
Greetings @onovotny,
I am not able to sideload appx's using Server2016.  Perhaps I am missing something?

Thanks,
coast

**Comment by onovotny** [comment]
No, probably not, was just checking to see if Server 2016 could sideload like that. We'll have the zip file for the next release.

**Comment by mancoast** [comment]
thanks!

**Comment by onovotny** [comment]
Closing as the CI now generates a zip file for this purpose. Will be published on the releases tab for the next release.
