### ISSUE TITLE
Switch to a different delivery mechanism than CodePlex

### ISSUE THREAD

**Issue by dsplaisted** [NuGetPackageExplorer/NuGetPackageExplorer#204]
[CodePlex is shutting down](https://blogs.msdn.microsoft.com/bharry/2017/03/31/shutting-down-codeplex/), so we'll need an alternate way to host the installer for NuGet Package Explore.

**Comment by sbrockway** [comment]
The codeplex link is present in the ReadMe.md file that is displayed below the code explorer on the welcome page for this site.

**Comment by 304NotModified** [comment]
Currently the alternatives are chocolatey and Windows store. 

Clickonce has too many install issues and without code certificate it also shows security warnings. 

If you think a Wix installer is also a good alternative, feel free to create a PR.

**Comment by sbrockway** [comment]
Maybe the resolution for this issue is to remove the link to the click once installer link and text from the readme, if the plan is to part ways with that installation option?

**Comment by tebeco** [comment]
@304NotModified sooo all corporation stuck on Win7 wont be able to install it ?
* No way i will be able to authorize and want to use Choco over Forward proxy / firewall
* Windows store is not available

**Comment by 304NotModified** [comment]
I think a portable version is a good idea. Currently very busy, still look at this next month

**Comment by tebeco** [comment]
i thought so but found PInvoke in the actual code, i'll have to take a deep dive in the code to understand all of it

**Comment by 304NotModified** [comment]
it's on windows store  / chocolatey.

**Comment by tebeco** [comment]
it means not accessible for company behind proxy ;)
