### ISSUE TITLE
ASP.NET Core package can be built and deployed but nothing is actually installed.

### ISSUE THREAD

**Issue by lordofscripts** [NuGetPackageExplorer/NuGetPackageExplorer#208]
Hi! Thanks for reporting this feature/bug/question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

**Type** (choose one):
- Bug

**NPE version**: (e.g. 3.12) (see Help -> about)
v3.21.0.0

**Installed from**: ClickOnce

In case of a BUG:

- What is the current result?
The PE does not detect any anomaly with the package. 
The PE can build the NUPKG
In VS.2017 I can install the said NUPKG into an ASP.NET CORE 1.1 web application, no installation errors occur but none of the files in the package are actually installed on the web application source tree.

- What is the expected result?

The files should be installed and appear in the Solution Explorer of VS.2017 in particular:

       ProjectRoot\
           Areas\Admin\Controllers\MyController.cs
           Areas\Admin\Views\Shared\Components\*
           Areas\Admin\Views\My\*.cshtml

When I used to build for traditional ASP.NET I could put the above files under the \content\ folder in the
Package Explorer and they would be deployed on the root of the web application.

Now that I am using ASP.NET Core I tried the same and while it said it "installed' the package (and showed it as installed) none of the files appeared in the tree.

I tried the same approach but building the package by putting all the above said files in a \contentFiles\ folder but the result was the same.

I read http://blog.nuget.org/20160126/nuget-contentFiles-demystified.html but that does not clarify the issue. 

Note that this is DIFFERENT than building a NuGet package directly from VS.2017 because that only works for Class Library projects, one cannot create a nuget from a (subset of) files of an MVC web application type of project. For that reason I pruned the files to build the package myself.

- Please post full exception details in case of an Exception (message, stacktrace, inner exceptions)
No errors were given, it said it installed successfully.

- Are there any work arrounds? yes/no
none that I know of

- Is there a version in which it did worked? 
I was able to build and install packages for traditional (ASP).NET but does not work for ASP.NET Core.

- Is there a package on Nuget.org which shows the bug?
No

**Comment by 304NotModified** [comment]
I think this is https://github.com/NuGet/Home/issues/1792 ?

**Comment by 304NotModified** [comment]
Please don't SHOUT thanks

**Comment by 304NotModified** [comment]
Afaik this isn't NPE. So close
