### ISSUE TITLE
Merge license from CodePlex site

### ISSUE THREAD

**Issue by dsplaisted** [NuGetPackageExplorer/NuGetPackageExplorer#21]
Before he transferred the ownership, I asked Luan to change the license of NuGet Package Explorer to MIT.  He did, and added a LICENSE file to the repo on CodePlex.  We should merge that change in here.

**Comment by 304NotModified** [comment]
Agree,  that's the only missing commit right now.

**Comment by 304NotModified** [comment]
@dsplaisted 

it this commit? https://github.com/dsplaisted/NuGetPackageExplorer/commit/cd5c14e8b7c7f8a553c5928023cfebb0ad93e387

**Comment by 304NotModified** [comment]
Why is it `[year] [fullname]`?

**Comment by 304NotModified** [comment]
@dsplaisted can you confirm this? Then I will cherry pick it.

> @dsplaisted
> 
> It's this commit? dsplaisted/NuGetPackageExplorer@cd5c14e

**Comment by dsplaisted** [comment]
@304NotModified Yes, that's the commit.  I'd prefer a merge to a cherry-pick for this, since I think that makes it more clear that the original author of the commit was Luan.

I pointed Luan to the MIT License and I guess he just copied it directly, without replacing the `[year] [fullname]`.  We can change that in a subsequent commit.  For name we could use "NuGet Package Explorer contributors".
