### ISSUE TITLE
Is it possible to have a package in each Release ready to install in Releases TAB?

### ISSUE THREAD

**Issue by fredatgithub** [NuGetPackageExplorer/NuGetPackageExplorer#215]
Hi!  

- Feature request and a
- Question

**NPE version**: (e.g. 3.23.0.0) 

- What is the current result? 
There's only the source code, I use to go to [https://npe.codeplex.com/] to upgrade my version to the latest one but Codeplex is shutting down soon so GitHub should have an easy way to upgrade to the latest version.

- What is the expected result? 
a package with executable ready to run on windows.

- Are there any work arrounds? 
yes : load the source into Visual Studio and compile to create the exe

in case of a FEATURE REQUEST:
 
 - Why do we need it? 
to be able to download the exe package and run it on Windows PC without Visual Studio

 - Please provide an use case : 
I go to Releases tab, download the exe package and run it on a Windows PC without Visual Studio
I volunteer to create such a package for every version if you want to.
[EXE-Release-v3.23.zip](https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/files/1200951/EXE-Release-v3.23.zip)

**Comment by 304NotModified** [comment]
> I volunteer to create such a package for every version if you want to.

Thanks. This could be done from appveyor. Would you also volunteer to create the appveyor script? :)

**Comment by fredatgithub** [comment]
yes sure, I have to figure out how to do it. do you have a sample appveyor script ?

**Comment by 304NotModified** [comment]
These docs could be helpful:

https://www.appveyor.com/docs/deployment/github/

https://www.appveyor.com/docs/packaging-artifacts/

Steps to set up AppVeyor for your own fork.

AppVeyor:

1. Login with your Github account to https://ci.appveyor.com
1. Choose "projects"
1
 Select your fork and press "+" button
1. Done. All config is in appveyor.yml already

**Comment by fredatgithub** [comment]
I've forked the project and create a new Appveyor project and build it
[NPE](https://ci.appveyor.com/project/fredatgithub/nugetpackageexplorer)
Now how to get the build package ?

**Comment by fredatgithub** [comment]
Appveyor tells me that  ("appveyor_repo_tag" is "false", should be "true")
despite my appveyor.yml file has appveyor_repo_tag: true 
as you can see [here](https://github.com/fredatgithub/NuGetPackageExplorer/blob/master/appveyor.yml)

**Comment by 304NotModified** [comment]
Have you created a tag in github?

**Comment by 304NotModified** [comment]
As far as I understand appveyor_repo_tag: true works only when pushing a tag. 

(A release in github creates a git tag, so this could be done in github.com)

**Comment by 304NotModified** [comment]
works, or isn't it? 

![image](https://user-images.githubusercontent.com/5808377/28998609-11fa6bd6-7a30-11e7-8f92-b7c3280f8b1f.png)

**Comment by fredatgithub** [comment]
No I haven't create a tag yet. I'm looking for how to do it.
V3.23 is what I have created manually
I'm still trying to find out how Appveyor is pushing build package to Github

**Comment by 304NotModified** [comment]
Just create a new release in your fork. 

https://github.com/fredatgithub/NuGetPackageExplorer/releases

And then new release.

**Comment by 304NotModified** [comment]
need some help on this?

**Comment by onovotny** [comment]
This is now available via the Microsoft Store and the CI builds. Is there something more that's needed?

**Comment by onovotny** [comment]
A standalone zip file will be available upon release as well.

**Comment by fredatgithub** [comment]
Thanks for the info except that Microsoft Store prevents to download NPE if I am on a Windows 7 machine

**Comment by onovotny** [comment]
@fredatgithub we will post a standalone zip file on the releases tab for the next release. The current version is also available via Chocolatey.
