### ISSUE TITLE
Files with spaces do not display in Nuget explorer

### ISSUE THREAD

**Issue by psandhu79** [NuGetPackageExplorer/NuGetPackageExplorer#219]
Hi

If you pack a nuget package which has files with spaces in the name they are not display properly in the GUI. The package works as expected however not displayed.

**Comment by onovotny** [comment]
Do you have a repro? This may be a bug with the underlying NuGet packing tasks itself. NPE just displays the entries as they were written in the underlying package.

**Comment by onovotny** [comment]
Closing for now. Please re-open with a repro package if still an issue with the latest.
