### ISSUE TITLE
"Open with" in Windows 10: The plugin that registers to read this file type fails to read the content of this file

### ISSUE THREAD

**Issue by 304NotModified** [NuGetPackageExplorer/NuGetPackageExplorer#22]
If I open an nupkg with double click. When starting NuGetPackageExplorer and then "open a local package", it works. 

> **\* The plugin that registers to read this file type fails to read the content of this file. ***

![image](https://cloud.githubusercontent.com/assets/5808377/11440836/2b582ae8-9506-11e5-847a-6aa4974ea4a9.png)

We should at least log the message? I think it could a permission/security issue. 

https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/4ba823deb94a360cc95bdf4775349d5bd65822f7/PackageViewModel/Commands/ViewContentCommand.cs#L101

it should be: 
![image](https://cloud.githubusercontent.com/assets/5808377/11440921/fd1179c2-9506-11e5-8345-3832a7302473.png)

tested with 3.9 and 3.10 RC2

**Comment by 304NotModified** [comment]
Can't reproduce in 3.11. Close for now.

**Comment by elv1s42** [comment]
Hello. 
I have the same problem with Windows 10 and Nuget Package Explorer 3.13.

> *** The plugin that registers to read this file type fails to read the content of this file. ***

> System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.OrderedEnumerable\`2..ctor(IEnumerable\`1 source, Func\`2 keySelector, IComparer\`1 comparer, Boolean descending)
   at PackageExplorer.AssemblyFileViewer.GetView(String extension, Stream stream)
   at PackageExplorerViewModel.ViewContentCommand.ShowFile(PackageFile file)

**Comment by 304NotModified** [comment]
Hi!

Which file do you like to read (.dll etc)? Can you post a screenshot?

Thanks!

**Comment by elv1s42** [comment]
Problem appears for .dll and .exe files, here is a screenshot:

![screenshot](https://cloud.githubusercontent.com/assets/6689884/14496807/207ff2a0-019d-11e6-8189-2ce127aa48fd.png)

.xml and .config files do not have this problem.
Issue appears only when I open an nupkg with double click. When starting NuGetPackageExplorer and then "open a local package", it works fine.

**Comment by 304NotModified** [comment]
Thanks! I will check this in the source code

**Comment by 304NotModified** [comment]
I checked the source code. Something goes wrong when reading the file. I added a nullref check for the exception in the master, but that won't resolve your case.

I have no issues when reading the package (so it's not package related), but I know this can be an issue.

![image](https://cloud.githubusercontent.com/assets/5808377/14500462/8534e1a6-01a2-11e6-9b4f-15f449a488fc.png)



I had also this problem, and I think it's a ClickOnce/registry  issue. Did you have installed a previous version before?

After a registry cleanup with CCleaner (beware not to install the toolbar!), https://www.piriform.com/ccleaner/builds, it was solved. Can you test that? 

![image](https://cloud.githubusercontent.com/assets/5808377/14500427/5f9e1f8e-01a2-11e6-8257-71ab90a6a6e1.png)


I'm thinking to include NLog in this project, although that also won't work well with ClickOnce I guess

**Comment by elv1s42** [comment]
Hello again.

> Did you have installed a previous version before?

No.

> After a registry cleanup with CCleaner (beware not to install the toolbar!), https://www.piriform.com/ccleaner/builds, it was solved. Can you test that?

That didn't help:
![screenshot](https://cloud.githubusercontent.com/assets/6689884/14520986/e97afdac-022f-11e6-87ad-16029b0a02fa.png)
I still can reproduce this issue.

**Comment by 304NotModified** [comment]
closed by #196
