### ISSUE TITLE
PowerShell Get installation scenario

### ISSUE THREAD

**Issue by am11** [NuGetPackageExplorer/NuGetPackageExplorer#221]
**Type**
- Feature request

In additional to Chocolatey, it would be convenient for the user to install it straight from PowerShell without additional dependency, if NPE package is made available on [PowerShell Gallery](https://docs.microsoft.com/en-us/powershell/gallery/psgallery/psgallery_gettingstarted).

https://docs.microsoft.com/en-us/powershell/gallery/psgallery/creating-and-publishing-an-item

For example, posh-git supports such an installation scenario: https://github.com/dahlbyk/posh-git#installing-posh-git-via-powershellget

**Comment by 304NotModified** [comment]
do you have any idea which steps we have to do for this?

**Comment by onovotny** [comment]
Is PSGallery appropriate for a GUI tool like this? I thought PSGallery was mostly aimed at distributing powershell cmdlets and extensions?

**Comment by am11** [comment]
> I thought PSGallery was mostly aimed at distributing powershell cmdlets and extensions?

Agree; not a best choice for GUI tool. Furthermore, apparently PSGallery doesn't allow additional artifacts ([ref](https://docs.microsoft.com/en-us/powershell/gallery/psgallery/psgallery-publishingguidelines)). :(

**Comment by 304NotModified** [comment]
thanks for the feedback!
