### ISSUE TITLE
how to i remove packages from version?

### ISSUE THREAD

**Issue by bouyeijiang** [NuGetPackageExplorer/NuGetPackageExplorer#222]
Hi! Thanks for reporting this feature/bug/question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

**Type** (choose one):

- Bug
- Feature request
- Question

**NPE version**: (e.g. 3.12) (see Help -> about)

**Installed from**: ClickOnce / chocolatey.org / Zip on CodePlex / Windows Store

In case of a BUG:

- What is the current result?
- What is the expected result?
- Please post full exception details in case of an Exception (message, stacktrace, inner exceptions)
- Are there any work arrounds? yes/no
- Is there a version in which it did worked? 
- Is there a package on Nuget.org which shows the bug?

in case of a FEATURE REQUEST:
 
 - Why do we need it?
 - Please provide an use case.

**Comment by tiesont** [comment]
It would help if you actually filled in the issue template. It's not exactly clear what you are asking.

**Comment by 304NotModified** [comment]
> tiesont commented on Aug 21
> It would help if you actually filled in the issue template. It's not exactly clear what you are asking.

Closing for now, will reopen if the provided info is provided
