### ISSUE TITLE
Not able to access V3 feed

### ISSUE THREAD

**Issue by pemo11** [NuGetPackageExplorer/NuGetPackageExplorer#223]
I am not able to acccess the following  feed:

https://powershell.myget.org/F/powershell-core/api/v3/index.json

The reason is probably that the Nuget Package Explorer does not Support V3 feeds.

Are there any plans to include this? I know that Package Explorer is not under develoment at the moment but since its such a valuable tool that might change in the future.

**Comment by 304NotModified** [comment]
Unfortunately there aren't plans to develop this feature.

**Comment by onovotny** [comment]
Closing as a duplicate of #50
