### ISSUE TITLE
nuspec format support errors

### ISSUE THREAD

**Issue by CollinChaffin** [NuGetPackageExplorer/NuGetPackageExplorer#224]
Hi! Thanks for reporting this feature/bug/question! 
 
Please keep / fill in the relevant info from this template so that we can help you as best as possible.

**Type** (choose one):

- Bug
![snag_8-27-2017_17-47-30](https://user-images.githubusercontent.com/9301483/29754680-dc326efa-8b4f-11e7-8c7e-c5320e2490e5.png)

**Installed from**:  chocolatey.org

In case of a BUG:

![snag_8-27-2017_17-46-21](https://user-images.githubusercontent.com/9301483/29754683-f4aa1b90-8b4f-11e7-983b-8b08c80c7c2f.png)

This has been coming up almost continually with all new packages lately, so I'm not sure if folks are just starting to utilize newer metadata elements that just have not been added to this explorer's parser code, or ? but if I edit the xml and remove the elements it complains about, then it functions just fine.

**Comment by KirillOsenkov** [comment]
Seeing the same thing. @onovotny @dsplaisted @emgarten

This is for packages generated with .NET SDK 2.0.2.

**Comment by emgarten** [comment]
I believe this comes from Package Explorer using nuget.core.dll which is legacy and no longer used in NuGet for VS 2017/dotnet CLI.

Possibly NuGet should avoid using an older nuspec.xsd namespace that nuget.core.dll understands and verifies, but this wasn't done I think nuget.core.dll would just reject the package completely and refuse to open it.

**Comment by KirillOsenkov** [comment]
Thanks. Are you saying that NuGet Package Explorer should be migrated off of NuGet.Core.dll onto something else? What should it be using instead? Any pointers?

**Comment by emgarten** [comment]
https://www.nuget.org/packages/NuGet.Packaging/ is what the current nuget client uses.

I'm not sure if this error is from package explorer or nuget.core.dll itself, I know package explorer uses a lot of internal things from nuget.core.dll and extends it.

**Comment by onovotny** [comment]
Help wanted! Initial pass has 84 errors :)

**Comment by onovotny** [comment]
Fixed in latest, thanks!
