### ISSUE TITLE
Download a package with all the dependencies

### ISSUE THREAD

**Issue by Leonardo76** [NuGetPackageExplorer/NuGetPackageExplorer#227]
How can I download a package with all the dependencies? For example, I want to download Microsoft.AspNetCore with all the dependencies.

**Comment by 304NotModified** [comment]
Currently to have to do that manually.

**Comment by Leonardo76** [comment]
It will be nice to have this feature for the situations where you have to build an application off-line (in an enterprise environment for example). Imagine to download all dependencies for Microsoft.AspNetCore for example and the dependencies of dependencies etc.

**Comment by monty241** [comment]
Yes, some functionality to "flatten" the dependency tree would be great!

**Comment by monty241** [comment]
Had Some more experience with nuget explorer. Some way of right click on dependency and suggest to have then choices like:
- merge into package (1 level)
- merge recursively into packages

For such functionality I am willing to fund upto eur 250 since it saves labor efforts.

**Comment by onovotny** [comment]
Closing as this is outside the scope of NuGet Package Explorer. To download all of the packages at once, you can use `dotnet restore` or `msbuild /t:restore` on project, and it'll download all of the packages to your userprofile cache directory.
