### ISSUE TITLE
No assembly info shown for .NET Standard 2.0 assemblies

### ISSUE THREAD

**Issue by luigiberrettini** [NuGetPackageExplorer/NuGetPackageExplorer#229]
**Type** (choose one): bug

**NPE version**: 3.21.0.0

**Installed from**: ClickOnce

![assembly-info-in-package-explorer](https://user-images.githubusercontent.com/4513301/30962881-c3465d92-a44b-11e7-96f9-c75e578dedb1.png)

Assembly info taken from build DLL and DLL extracted from NuGet package (ILSpy CI build):
```csharp
[assembly: CompilationRelaxations(8)]
[assembly: RuntimeCompatibility]
[assembly: Debuggable()]
[assembly: TargetFramework(".NETStandard,Version=v2.0")]
[assembly: AssemblyCompany("Asbly company")]
[assembly: AssemblyConfiguration("Debug")]
[assembly: AssemblyCopyright("Asbly copyright")]
[assembly: AssemblyDescription("Asbly description")]
[assembly: AssemblyFileVersion("3.0.0.0")]
[assembly: AssemblyInformationalVersion("4.0.0.0")]
[assembly: AssemblyProduct("Asbly product")]
[assembly: AssemblyTitle("Asbly title")]
[assembly: NeutralResourcesLanguage("en")]
[assembly: AssemblyVersion("2.0.0.0")]
```

Related to [dotnet/sdk issue 1555](http://github.com/dotnet/sdk/issues/1555) and [NLog/NLog issue 1536](http://github.com/NLog/NLog/issues/1536)

**Comment by 304NotModified** [comment]
Thanks for submitting!

Reproducible with NLog 4.5 beta 2:


![image](https://user-images.githubusercontent.com/5808377/30963097-8a5b6b3e-a44c-11e7-8a3a-44b38f729f94.png)

**Comment by 304NotModified** [comment]
With NLog 5 beta 11

- netstandard 1.3 works
- netstandard 1.5 doesn't work

![image](https://user-images.githubusercontent.com/5808377/30963148-b42f8346-a44c-11e7-8b67-67da3ccda359.png)


![image](https://user-images.githubusercontent.com/5808377/30963155-bb798bec-a44c-11e7-9415-1b22f98d2bc2.png)

**Comment by luigiberrettini** [comment]
Repo [dotnet-core-assembly-info](http://github.com/luigiberrettini/dotnet-core-assembly-info) available for investigation.

Try looking at ILSpy CI build code to understand how to solve this issue.

**Comment by 304NotModified** [comment]
👍

**Comment by 304NotModified** [comment]
@onovotny this will be 3.24 I think? Could you release a new version?

**Comment by onovotny** [comment]
I already released 3.24 to fix a NuGet publish compat issue. The next release would be 3.25. Also am awaiting a fix from the VS team around the packaging projects that #237 exposed. Hopefully should have a workaround shortly.

**Comment by 304NotModified** [comment]
ah, choco is still 3.24

**Comment by 304NotModified** [comment]
also the store says 3.23? Or is it the text only?

![image](https://user-images.githubusercontent.com/5808377/32332570-1db1494e-bfe6-11e7-979f-cfda6aa71746.png)

**Comment by onovotny** [comment]
That's the text only, forgot to update that.

**Comment by 304NotModified** [comment]
@onovotny are you on gitter?
