### ISSUE TITLE
Add individual classification for package version

### ISSUE THREAD

**Issue by netdragoon** [NuGetPackageExplorer/NuGetPackageExplorer#23]
As classification of packets could be designed one ratings scheme for package version. This proposal for including packages that already exist and are never updated are improved.

_Example:_

>![ratings](https://cloud.githubusercontent.com/assets/15145509/12071456/45e70f3c-b095-11e5-9a6b-9c1008c1ab5a.png)

___What opinion on the matter? and if it's possible?___

**Comment by dsplaisted** [comment]
I'm not sure what you mean.  It sounds like you're talking about a rating feature.  Do you want NuGet package manager to keep track of package ratings, or is this a request for nuget.org, or what?

**Comment by netdragoon** [comment]
__Rating Feature__

__Resume:__

_It sounds like you're talking about a rating feature. Do you want NuGet package manager to keep track of package ratings_

__It would be a 5-star rating control and a way to also organize the list of packages in the polls.__

**Comment by 304NotModified** [comment]
@netdragoon 

Thanks for this suggestion. As the NPE is only a client library, this feature would be a bit strange here - we cannot save the ratings anywhere.

I suggest to post the feature to https://github.com/nuget/nugetgallery. Do you agree?

**Comment by 304NotModified** [comment]
I think this feature isn't possible in NPE as we don't have a server to store this, so closing this one.
