### ISSUE TITLE
tizen3 lib folder results in "Unrecognized framework"

### ISSUE THREAD

**Issue by peterfoot** [NuGetPackageExplorer/NuGetPackageExplorer#230]
**Type** (choose one):

- Bug

**NPE version**: 3.23.0.0

**Installed from**:  Windows Store

In case of a BUG:

- What is the current result?
Adding a "tizen3" lib folder shows "Unrecognized framework" and an "Invalid framework folder" when analysing the package.

- What is the expected result?
NPE needs to have Tizen framework support and be aware of the framework names and versions

- Please post full exception details in case of an Exception (message, stacktrace, inner exceptions)
n/a

- Are there any work arounds? no
However package will still compile and be valid

- Is there a version in which it did worked? 
No - Tizen is a recent .NET platform addition
- Is there a package on Nuget.org which shows the bug?

**Comment by 304NotModified** [comment]
FYI,

this is an issue of [NuGet.Core,](https://www.nuget.org/packages/NuGet.Core/) which don't recognizes Tizen and we have the lastest version (2.14)

**Comment by 304NotModified** [comment]
related: https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/pull/240

**Comment by onovotny** [comment]
Fixed in latest, thanks!
