### ISSUE TITLE
Applying version ranges on Packages dependencies

### ISSUE THREAD

**Issue by TheHunter** [NuGetPackageExplorer/NuGetPackageExplorer#231]
Hi everyone,
I notice that it's impossible to add a nuget package dependency which it's applied a range or specific version, so at the moment is possible to add a dependency package with minimum version inclusive ( ex. 
MyPackage >= [the version chosen])  

Being impossible to apply a range of version, It could imply a big problem whenever anyone tries to UPDATE a package specifying its own dependencies.

In my case, my package must install an unique version of one dependency (see image bellow):
![image](https://user-images.githubusercontent.com/992665/31228390-a35f5d8e-a9dd-11e7-9acd-93c98a82217b.png)

However, at the moment to make it possible I made my package using nuget command line with nuspec file.. but I'd like do it using Nuget Package Explorer.

I suggest you to add this feature adding the possibility to modify a range of version (as explained in this link)
https://docs.microsoft.com/en-us/nuget/reference/package-versioning

So, in my opinion could be to settable the label "version", in order to apply / modify the range of version.
![image](https://user-images.githubusercontent.com/992665/31228609-5c1b9108-a9de-11e7-9025-b2b21b748426.png)

I hope It's clear... in my opinion It would be a simple task to do.

Thanks a lot.

**Comment by onovotny** [comment]
This works in #240

**Comment by onovotny** [comment]
Fixed in latest, thanks!
