### ISSUE TITLE
Update for NuGet.org protocol changes

### ISSUE THREAD

**Issue by 304NotModified** [NuGetPackageExplorer/NuGetPackageExplorer#232]
See https://github.com/NuGet/NuGetGallery/issues/4805

**Comment by 304NotModified** [comment]
@onovotny @dsplaisted   any idea if this is just updating the dependencies?

**Comment by onovotny** [comment]
It's one line, I have the changes

**Comment by 304NotModified** [comment]
:+1:

**Comment by onovotny** [comment]
The change is here
https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/master/PackageViewModel/GalleryServer.cs#L42 

Add  `httpRequest.Headers.Add("X-NuGet-Protocol-Version", "4.1.0");`

We really ought to figure out how to get to the latest client library though

**Comment by anangaur** [comment]
Is it already available to install from chocolatey? I see 3.23 version when I install using `choco install nugetpackageexplorer`

**Comment by 304NotModified** [comment]
Not yet, as there is some version numbering things unclear to me for doing the chocolatey release.

**Comment by anangaur** [comment]
@304NotModified we are planning to enforce the 4.1.0 requirements on Nov 27th (was No 10th) and hence if we can target the release by then, it would help in unblocking many users once the enforcement is live.
Is there anything I or NuGet team can help with?

**Comment by onovotny** [comment]
The Store version has already been updated to add that header. It's just the chocolatey version that needs to be published.

**Comment by anangaur** [comment]
@onovotny Yepp. Saw that. Thanks! Lets see if we can update choco version too. In any case I am going to [document](https://github.com/NuGet/NuGetGallery/issues/4805#issuecomment-345392364) the various ways to use the latest/compatible clients (nuget.exe and others)  and I am using the Windows Store link for NPE.
