### ISSUE TITLE
Issue with pushing packages to NuGet.org

### ISSUE THREAD

**Issue by JustTotallyMe** [NuGetPackageExplorer/NuGetPackageExplorer#239]
Hi! Thanks for reporting this feature/bug/question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

**Type**: Bug or just an issue on my machine

**NPE version**: 3.21.0.0

**Installed from**: ClickOnce 

Hi Guys,

I do have an issue or it could be a bug I'm not quite sure.
When I click on publish to upload the package to NuGet, I'm getting an error saying the following:
Failed to process request: 'A client version "4.1.0' or higher is required to be able to push packages. Please contact etc...'

I already made sure to have the newest nuget.exe but I do not know where I'm supposed to put that .exe in order to have NPE use it.

Is it not supported anymore to push packages or I'm a missing something here?

Hope you could help me with this.

Thanks and kind regards,

Andy

**Comment by onovotny** [comment]
You need to use the latest version from the Windows Store. That has the fix in it.

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, let us know!
