### ISSUE TITLE
No lib > 4.5 ?

### ISSUE THREAD

**Issue by netdragoon** [NuGetPackageExplorer/NuGetPackageExplorer#24]
When will be released lib greater than _4.5_ in __Nuget Explorer__?

![save02](https://cloud.githubusercontent.com/assets/15145509/12123430/20de05d4-b3c8-11e5-812b-b4dcaa8bc148.png)

__That is,__ _4.5.1_, _4.5.2_, _4.6_ and _4.6.1_ !!!

**Comment by 304NotModified** [comment]
This has been merged, but not released. 

Too bad we cannot host the clickonce in github.

**Comment by netdragoon** [comment]
Have any date forecast?

**Comment by 304NotModified** [comment]
Sorry, not yet.

**Comment by 304NotModified** [comment]
3.10 is now live:

https://npe.codeplex.com/downloads/get/clickOnce/NuGetPackageExplorer.application

(first remove the old installation first)
