### ISSUE TITLE
Chocolatey version on AppVeyor is non-semver

### ISSUE THREAD

**Issue by 304NotModified** [NuGetPackageExplorer/NuGetPackageExplorer#243]
It looks like the current versioning on AppVeyor for Chocolatey packages is non-semver.

![image](https://user-images.githubusercontent.com/5808377/33043423-b5741870-ce45-11e7-862e-6d9a736bd90f.png)

e.g. it should be 3.25 or 3.25.0

**Comment by 304NotModified** [comment]
Looks like a "feature"? https://github.com/AArnott/Nerdbank.GitVersioning#why-is-the-git-height-used-for-the-patch-version-component-for-public-releases

**Comment by onovotny** [comment]
You can also explicitly set the third version -- use `5.0.0`. If you want the height, you can use the `{height}` macro, like `5.0.0-build.{height}`

**Comment by onovotny** [comment]
This is fixed in #254 where the Choco package is always created with `MajorMinor`.

**Comment by 304NotModified** [comment]
👍
