### ISSUE TITLE
Support Package Signing

### ISSUE THREAD

**Issue by ridomin** [NuGetPackageExplorer/NuGetPackageExplorer#248]
**Type**:  Feature request
**NPE version**: 3.21.0.0
**Installed from**:  Windows Store

NPE should be updated to be aligned with NuGet Package signing https://github.com/NuGet/Home/issues/2577 

I'd suggest the next User Stories by priority

- P0. Disable edits if the package is signed.
- P1. Show signature information.
- P1. Allow removing the signature when saving.
- P2. Allow signing packages.

**Comment by maartenba** [comment]
Is there any news on signing into for non-MS projects?

**Comment by ridomin** [comment]
Hi @maartenba 
We are finishing the signature format spec, although we have started the implementation in the https://github.com/NuGet/NuGet.Client/commits/dev-feature-signing branch

We will announce progress once we publish the spec and have beta bits with signing support.

**Comment by maartenba** [comment]
Thanks!

**Comment by onovotny** [comment]
@maartenba I have a client app impl that uses Key Vault to do the sign operations and uses Bouncy Castle to generate the SignedCms message (since the APIs in the .NET one to do what I need don't exist yet):
https://github.com/onovotny/NuGetKeyVaultSignTool

**Comment by onovotny** [comment]
P0 is done, P1 is partial (show signature information shows the publisher, but not validation status yet).

**Comment by onovotny** [comment]
We now support showing signature information. Removing signature info and signing will likely wait until the next release.

**Comment by onovotny** [comment]
The P0 and P1 items are both done now.

**Comment by onovotny** [comment]
Closing out this issue as #292 tracks signing packages from NPE and the rest of the items here have been completed.
