### ISSUE TITLE
Use Packaging Object Model for Save / NuSpec

### ISSUE THREAD

**Issue by onovotny** [NuGetPackageExplorer/NuGetPackageExplorer#251]
#240 updated the code to leverage the Packaging OM for opening `nupkg` files. This is to track the remainder of the work.

Success criteria for this is that direct XML serialization is removed.

**Comment by 304NotModified** [comment]
> Success criteria for this is that direct XML serialization is removed.

What could be used instead?

**Comment by onovotny** [comment]
@304NotModified The NuGet.Packaging types have this support directly. We just need to map to it -- basically the reverse of what I did for reading the package in #240. This probably didn't exist in the NuGet 2.x days.

**Comment by onovotny** [comment]
This is implemented in #252
