### ISSUE TITLE
Add "Nightly" release channel

### ISSUE THREAD

**Issue by onovotny** [NuGetPackageExplorer/NuGetPackageExplorer#253]
Goal is to have an `appx` that can be sideloaded on machines as part of the CI build. This will help let people use it before we're ready for a "stable" release to the store.

Requirements:
- Must be SxS with the store version

Due to manifest requirements, we'll need a new packaging project with a new manifest that uses a different package id. An overlay on the icon to tell the difference would be nice.

Also for versioning, we'll be incrementing the patch for every build since the packages can't use "prerelease" labels. That means, builds will be like `6.0.48`, etc. Once deemed stable, the released version will go to the store.

The CI process will ensure the bits are signed with a certificate to a publically trusted root CA, so no issues with sideloading.

/cc @304NotModified

**Comment by onovotny** [comment]
Implemented in #254

**Comment by 304NotModified** [comment]
🎉
