### ISSUE TITLE
Add support for $version$ with new object model

### ISSUE THREAD

**Issue by onovotny** [NuGetPackageExplorer/NuGetPackageExplorer#255]
#252 breaks current support for the $version$ token since code is read through the NuGet object model.

https://github.com/NuGet/Home/issues/6228 tracks this on the NuGet side, but we'll attempt to workaround it a different way here.

**Comment by onovotny** [comment]
There's a PR for NuGet that'll fix this:
https://github.com/NuGet/NuGet.Client/pull/1842

**Comment by 304NotModified** [comment]
Nice :+1:

Hope they merge faster than the nuget/home team ;)
