### ISSUE TITLE
Release tag NuGet Package Explorer v3.25 is wrong it is v3.24

### ISSUE THREAD

**Issue by fredatgithub** [NuGetPackageExplorer/NuGetPackageExplorer#261]
Hi!

**Type**:
- BUG

**NPE version**: (e.g. 3.2.4) (see Help -> about)

**Installed from**: download source from release tag v3.25 and compile it on Visual Studio 2017 on Windows 7

In case of a BUG:

- What is the current result? 
The tag says NuGet Package Explorer v3.25
- What is the expected result?
The about box after compiling says NuGet Package Explorer v3.24
- Are there any work arrounds? yes
delete tag The tag says NuGet Package Explorer v3.25 and create a new one The tag says NuGet Package Explorer v3.24
- Is there a version in which it did worked? 
yes the NuGet Package Explorer v3.24

You can verify here:
[https://github.com/fredatgithub/NuGetPackageExplorer/releases](https://github.com/fredatgithub/NuGetPackageExplorer/releases)

**Comment by onovotny** [comment]
Thanks for the report. This is a bug, but we're not going to do a new release for it. The code has been updated in #265 to always be up-to-date.
