### ISSUE TITLE
a client version '4.1.0' or higher is required to be able to push packages

### ISSUE THREAD

**Issue by bouyeijiang** [NuGetPackageExplorer/NuGetPackageExplorer#262]
Hi! Thanks for reporting this feature/bug/question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

**Type** (choose one):

- Bug
- Feature request
- Question

**NPE version**: (e.g. 3.12) (see Help -> about)

**Installed from**: ClickOnce / chocolatey.org / Zip on CodePlex / Windows Store

In case of a BUG:

- What is the current result?
- What is the expected result?
- Please post full exception details in case of an Exception (message, stacktrace, inner exceptions)
- Are there any work arrounds? yes/no
- Is there a version in which it did worked? 
- Is there a package on Nuget.org which shows the bug?

in case of a FEATURE REQUEST:
 
 - Why do we need it?
 - Please provide an use case.

**Comment by 304NotModified** [comment]
please fill in the template

**Comment by bouyeijiang** [comment]
does this tool support the vs plug-in?do not support online upgrades?

**Comment by santoshCRM** [comment]
Not bale to resolve this issue. Can you share link for latest download. or step to resolve this issue.

**Comment by santoshCRM** [comment]
I am using nuget package explorer 
![image](https://user-images.githubusercontent.com/23490088/33651067-85c55458-da8a-11e7-9112-e8172450be02.png)

**Comment by 304NotModified** [comment]
this is solved in 3.25

- The Chocolatey package is live: https://chocolatey.org/packages/NugetPackageExplorer/3.25.0
- The Windows Store update is in the store's queue.
- ClickOnce/codeplex is dead

**Comment by onovotny** [comment]
The current 3.24 version in the store has this fix as well.

**Comment by 304NotModified** [comment]
👍
