### ISSUE TITLE
Synchronize Store and Choco versions

### ISSUE THREAD

**Issue by zvirja** [NuGetPackageExplorer/NuGetPackageExplorer#268]
Currently you have a bit of dispersion for the published versions. Previously we had Store version which was ahead of Choco, while currently Choco version is ahead of Store version:

![image](https://user-images.githubusercontent.com/1074182/33822755-62b050be-de61-11e7-96c1-194be0f52445.png)

Could you please synchronize the published artifacts and have the same version in both the stores? The current situation forces to constantly re-install app to use the latest version 😕

Thank you.

**Comment by onovotny** [comment]
There's only a very minor difference between the choco and store version. We're not planning on releasing 3.25 to the store. They'll both go to the latest version later this month.

**Comment by zvirja** [comment]
@onovotny Thanks for the reply. Would it be possible in future to always have releases in sync?

**Comment by onovotny** [comment]
Yes, that's the goal. We hit a glitch in the Packaging project that needed a workaround.

**Comment by zvirja** [comment]
Awesome, thanks 😉
