### ISSUE TITLE
Crash on opening push dialog/save: The DateTimeOffset specified cannot be converted into a Zip file timestamp.'

### ISSUE THREAD

**Issue by 304NotModified** [NuGetPackageExplorer/NuGetPackageExplorer#269]
**Type** (choose one):

- Bug

**NPE version**: (e.g. 3.12) 3.25

**Installed from**: source - 6fb8f2638206af4e2a98ffcc71f450ef3636d1b3

In case of a BUG:

- What is the current result? exception
- What is the expected result? showing popup for push
- Please post full exception details in case of an Exception (message, stacktrace, inner exceptions)
```
System.ArgumentOutOfRangeException
  HResult=0x80131502
  Message=The DateTimeOffset specified cannot be converted into a Zip file timestamp.
Parameter name: value
  Source=System.IO.Compression
  StackTrace:
   at System.IO.Compression.ZipArchiveEntry.set_LastWriteTime(DateTimeOffset value)
   at NuGet.Packaging.PackageBuilder.CreatePart(ZipArchive package, String path, Stream sourceStream, DateTimeOffset lastWriteTime)
   at NuGet.Packaging.PackageBuilder.WriteFiles(ZipArchive package, HashSet`1 filesWithoutExtensions)
   at NuGet.Packaging.PackageBuilder.Save(Stream stream)
   at PackageExplorerViewModel.PackageHelper.SavePackage(IPackageMetadata packageMetadata, IEnumerable`1 files, String targetFilePath, Boolean useTempFile) in X:\_github\NuGetPackageExplorer\PackageViewModel\Utilities\PackageHelper.cs:line 34

```
- Are there any work arrounds? no
- Is there a version in which it did worked? not checked
- Is there a package on Nuget.org which shows the bug?
Nlog 4.4.12

steps:
![image](https://user-images.githubusercontent.com/5808377/33853042-d499ef90-debc-11e7-9a14-43114027ea24.png)

![image](https://user-images.githubusercontent.com/5808377/33853053-dfd4ca9c-debc-11e7-8260-0ea1ae5c2dc8.png)

extra info:

- current culture: nl-NL
- current ui culture: en-US

**Comment by 304NotModified** [comment]
mmm same for save and with a new package.

Setting current culture on en-US won't help (or maybe too late)

@onovotny any idea?

**Comment by onovotny** [comment]
Is this a localization thing? Is there a sample? What's the DateTimeOffset that's failing?

**Comment by 304NotModified** [comment]
I don't know where there is a DateTimeOffset. Trying to debug it

**Comment by onovotny** [comment]
Here it is:
https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/commit/ec476eb5466ce22411362a4e0bf59e50d5c5056a

I stubbed it out, guess we need to populate it.

**Comment by 304NotModified** [comment]
`public DateTimeOffset LastWriteTime => DateTimeOffset.MinValue;`?

think so, seeing this call stack:

```
   at System.IO.Compression.ZipArchiveEntry.set_LastWriteTime(DateTimeOffset value)
   at NuGet.Packaging.PackageBuilder.CreatePart(ZipArchive package, String path, Stream sourceStream, DateTimeOffset lastWriteTime)
   at NuGet.Packaging.PackageBuilder.WriteFiles(ZipArchive package, HashSet`1 filesWithoutExtensions)
   at NuGet.Packaging.PackageBuilder.Save(Stream stream)
   at PackageExplorerViewModel.PackageHelper.SavePackage(IPackageMetadata packageMetadata, IEnumerable`1 files, String targetFilePath, Boolean useTempFile) in X:\_github\NuGetPackageExplorer\PackageViewModel\Utilities\PackageHelper.cs:line 43
```

**Comment by 304NotModified** [comment]
any idea if we could use `File.LastAccessTime(path) `?

as we only have a partial path of course

**Comment by onovotny** [comment]
I think that should work long as that doesn't throw. AFAIK, the base is set to the directory the nuspec file is in.

**Comment by 304NotModified** [comment]
it gives also minValue. 

I could read the content of the file (e.g. dll) as stream in 
https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/master/Core/Packages/ZipPackageFile.cs#L17

but that doesn't have a lastWriteTime of course.

**Comment by 304NotModified** [comment]
ah found it, but now thinking where this code should be added

![image](https://user-images.githubusercontent.com/5808377/33854991-da2cf432-dec3-11e7-9480-584261ad3602.png)

**Comment by 304NotModified** [comment]
I think i'm almost there

**Comment by ItsMrQ** [comment]
304NotModified + this still appears to be an issue when creating a new package with several files and folders. Upon saving (as) the program will hang and eventually respond with "DateTimeOffset specified cannot be converted into a zip file timestamp. It seems to work fine with a smaller amount of files and/or saving the initial package with a smaller amount of files and adding more in after each save. I have an older stable release in my repository which does not report this issue.

**Comment by onovotny** [comment]
@ItsMrQ can you repro on the current CI version? The one that has these changes has not been in a stable release yet. Otherwise, please open a new issue with a repro.

Thanks!

**Comment by genyx** [comment]
I can confirm that the error still happens on the new CI version. I can't use NPE anymore. It seems to have affected the whole program

**Comment by onovotny** [comment]
@genyx can you share a repro?

**Comment by genyx** [comment]
Unfortunally, i don't know... I start NPE (used the CI setup on the main github page) leave the metadata as default, add a lib folder, add an empty net45 folder and click save. It does not save and says the error like above.

**Comment by onovotny** [comment]
Thanks, should be fixed in https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/pull/325

**Comment by genyx** [comment]
Yes, that fixed it for me. thanks

**Comment by WspDev** [comment]
I got this issue when I had an empty folder under a net folder under lib.
Putting files in it solved the issue.

**Comment by ebicoglu** [comment]
**My solution:**

Run the below Powershell script. 
It sets all the invalid DLL dates to 01/01/2000.
Change the `path` parameter for your computer. 
My GitHub repositories are on my `C` drive so I'm running this `-path C:\`.

```
gci -path "C:\" -rec -file *.dll | Where-Object {$_.LastWriteTime -lt (Get-Date).AddYears(-20)} | %  { try { $_.LastWriteTime = '01/01/2000 00:00:00' } catch {} }
```
