### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by 304NotModified** [NuGetPackageExplorer/NuGetPackageExplorer#27]
@dsplaisted Daniel,

I would like to release a new version. Some bugs are fixed, but is is still not released. 

We can't release a clickonce it on Github (found out the hard way). Tried github raw links and a Github page. 

Can we release the Clickonce somewhere else? Or least on Codeplex for now? If you add me as admin (my account: https://www.codeplex.com/site/users/view/JulianV), I can do that.

**Comment by dsplaisted** [comment]
I've added you as an admin on the CodePlex NPE project.

Sorry I haven't found the time to do anything with the project yet.  Feel free to also edit the CodePlex site to redirect to the new GitHub project.

**Comment by 304NotModified** [comment]
OK will do that. Thanks!

**Comment by 304NotModified** [comment]
current location:
https://npe.codeplex.com/downloads/get/clickOnce/NuGetPackageExplorer.application

**Comment by 304NotModified** [comment]
@rikoe , @dsplaisted 

I tried a new deployment on npe.codeplex.com, but I have two issues:

- I get a new publisher is untrusted error. I tried with signing the clickonce, but I did not help (also unclear which certificate we should use for that)
- the file associations wont work (e.g. double click test.nuspec). Any idea why not? I cannot find the code to set-up the file associations. When in reinstall 3.9 it works.

**Comment by onovotny** [comment]
How about switching to Squirrel; you can store the bits on any blob storage for super cheap.

**Comment by 304NotModified** [comment]
But not on github /codeplex I guess? 

Clickonce worked fine with the previous releases. Dunno why is now not working.

**Comment by 304NotModified** [comment]
@dsplaisted , @rikoe can you help me on this one? Without getting this working, this whole repo is useless :(

**Comment by NanaLich** [comment]
can you publish the new version somewhere else? so i can try and find what's wrong with the file assoc thing

for the untrusted publisher problem, you'll need the original cert from the original project owner, which is usually not included in the repo and possibly no longer accessible, so you just publish new version with or without your own cert, and tell users to trust the new one(may need to uninstall older version, can't remember)

**Comment by 304NotModified** [comment]
Good idea.  

The untrusted publisher is indeed something we can't prevent (the previous certificate is expired) and that isn't a big issue. (too bad auto update won't work) 

I will create a new codeplex site to test this.

**Comment by 304NotModified** [comment]
@Licshee I was probably my machine. After uninstall previous version and install new one,, it works.

3.10 is now live:

https://npe.codeplex.com/downloads/get/clickOnce/NuGetPackageExplorer.application

**Comment by Licshee** [comment]
worked for me.
at least for now

**Comment by 304NotModified** [comment]
:) Thanks for the feedback!

**Comment by rikoe** [comment]
May I ask why the manual uninstall of the previous version is required? It would be great if it could seamlessly upgrade. I am happy to look into it if there's a technical limitation, I have some past experience with installs and ClickOnce.

**Comment by rikoe** [comment]
Also, is there any way to host the ClickOnce manifest on the GitHub repo releases page instead of on CodePlex (i.e. here: https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/releases).

E.g. another tool I use, GitExtensions, link all their downloads from the releases page: https://github.com/gitextensions/gitextensions/releases

**Comment by Licshee** [comment]
i believe it is not required to uninstall previous version, it used to be required might because @304NotModified used a different manifest url

also, usually an upgrade of windows can also mess your file assoc thing, idunno why

**Comment by 304NotModified** [comment]
> May I ask why the manual uninstall of the previous version is required? It would be great if it could seamlessly upgrade. I am happy to look into it if there's a technical limitation, I have some past experience with installs and ClickOnce.

2 reasons: I had problems upgrading it (error, log showed: "product with same name already installed" (or something like that), and the clickonce original certificate has been expired (these problems could be related)


> i believe it is not required to uninstall previous version, it used to be required might because @304NotModified used a different manifest url

The manifest URL is the same but the clickonce certificate not. 



> also, usually an upgrade of windows can also mess your file assoc thing, idunno why
> when this happens, you need to delete the corresponding registry keys manually

Yes, I had those problems

> Also, is there any way to host the ClickOnce manifest on the GitHub repo releases page instead of on CodePlex (i.e. here: https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/releases).

That won't work (tried it multiple times), due to Github won't send the right header. The info what can be found on stackoverflow/blogs on this is most of the time out-to-date.
