### ISSUE TITLE
Nullref on prerelease  version check

### ISSUE THREAD

**Issue by 304NotModified** [NuGetPackageExplorer/NuGetPackageExplorer#270]
![image](https://user-images.githubusercontent.com/5808377/33852576-5c3e8fc0-debb-11e7-9685-a788068def12.png)

**Type** (choose one):

- Bug

**NPE version**: (e.g. 3.12) master, 6fb8f2638206af4e2a98ffcc71f450ef3636d1b3

**Installed from**: source

In case of a BUG:

- What is the current result? Exception
- What is the expected result? no Excetpion
- Please post full exception details in case of an Exception (message, stacktrace, inner exceptions)
```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=PackageViewModel
  StackTrace:
   at PackageExplorerViewModel.Rules.PrereleasePackageDependencyRule.IsPrereleaseDependency(PackageDependency pd) in X:\_github\NuGetPackageExplorer\PackageViewModel\PackageAnalyzer\PrereleasePackageDependencyRule.cs:line 38

```
- Are there any work arrounds? no
- Is there a version in which it did worked? I think 3.25
- Is there a package on Nuget.org which shows the bug?
See attachment

open package
[NugetPackageExplorer.3.25.nupkg.zip](https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/files/1549366/NugetPackageExplorer.3.25.nupkg.zip)

**Comment by onovotny** [comment]
Should be an easy fix. Didn't realize it could be null. Should be `VersionRage.MinVersion?.IsPrerelease == true || VersionRage.MaxVersion?.IsPrerelease == true`

**Comment by 304NotModified** [comment]
But is `null` prelease or non-pre?
