### ISSUE TITLE
"Select File" shows deleted files

### ISSUE THREAD

**Issue by Krogsager** [NuGetPackageExplorer/NuGetPackageExplorer#273]
**Type**: Bug

**NPE version**: 3.24.0.0

**Installed from**: Windows Store

- What is the current result?
I delete a .nupkg but I can still open it and read metadata from NuGet Package Explorer
- What is the expected result?
NPE should not show deleted files nor be able to open them
- Are there any work arrounds? no
- Is there a version in which it did worked? 
N/A
- Is there a package on Nuget.org which shows the bug?
no

Actual state of directory:
![image](https://user-images.githubusercontent.com/27994384/33879158-df2df5d4-df2d-11e7-9cbc-bca03bae321d.png)
![image](https://user-images.githubusercontent.com/27994384/33879405-9fd2d142-df2e-11e7-92d2-81aed53ed8a4.png)

What NPE sees:
![image](https://user-images.githubusercontent.com/27994384/33879255-2c4e6632-df2e-11e7-8967-6aded877174a.png)

![image](https://user-images.githubusercontent.com/27994384/33879278-440f876a-df2e-11e7-924d-810841a21bba.png)

**Comment by zvirja** [comment]
I might be mistaken, but I believe they use the default .NET/Windows pickers to find the files.
Is this behavior persistent? Do you see the deleted files e.g. after the reboot?

**Comment by 304NotModified** [comment]
@Krogsager please check after reboot indeed. 

Also don't think we could change this behavior, sounds like a cache issue in windows explorer

**Comment by onovotny** [comment]
Closing this as external. We just use the regular file pickers.
