### ISSUE TITLE
What is the Serviceable checkbox for in the metadata?

### ISSUE THREAD

**Issue by eschneider999** [NuGetPackageExplorer/NuGetPackageExplorer#302]
What is the Serviceable checkbox for in the metadata?

**Comment by svick** [comment]
[The official documentation says](https://docs.microsoft.com/en-us/nuget/schema/nuspec#single-elements):

> For internal NuGet use only.

https://github.com/NuGet/Home/issues/2870 explains more:

> In nuspec file an attribute "like" this:
> `<serviceable>true</serviceable>`
> ...will enable Microsoft Update servicing for Microsoft delivered packages.
