### ISSUE TITLE
Error while saving!

### ISSUE THREAD

**Issue by eschneider999** [NuGetPackageExplorer/NuGetPackageExplorer#308]
Something invalid error...

- Bug

**NPE version**: (e.g. 3.12) (see Help -> about)

Windows Store

In case of a BUG:

- What is the current result?
Error while saving, thanks wasted an hour and lost all my work!

- What is the expected result?
- Please post full exception details in case of an Exception (message, stacktrace, inner exceptions)
- Are there any work around? no
- Is there a version in which it did worked? See it before
- Is there a package on Nuget.org which shows the bug?

**Comment by 304NotModified** [comment]
> Error while saving, thanks wasted an hour and lost all my work!

Please "be nice". This in't a paid service.
