### ISSUE TITLE
Save Error

### ISSUE THREAD

**Issue by eschneider999** [NuGetPackageExplorer/NuGetPackageExplorer#309]
Unknown block type. Stream might be corrupted.

- Bug

3.24.0.0

Windows Store

In case of a BUG:

- What is the current result?
- What is the expected result?
- Please post full exception details in case of an Exception (message, stacktrace, inner exceptions)
- Are there any work arrounds? no
- Is there a version in which it did worked? seen before
- Is there a package on Nuget.org which shows the bug?

**Comment by 304NotModified** [comment]
please fill in the template
