### ISSUE TITLE
Cannot use with other package sources

### ISSUE THREAD

**Issue by TedMobile** [NuGetPackageExplorer/NuGetPackageExplorer#313]
Hi 
We would like to use this package but we found out that only work with the following package source url
https://www.nuget.org/api/v2/

when used with any other url  eg https://api.nuget.org/v3/index.json or myget urls  I get an error

"Cannot add count option to the resource set because it would conflict with existing count option"

could let me know if this tool can be used to download packages from any other package source?

thanks
Ted

**Comment by 304NotModified** [comment]
I think this is https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/issues/50?

**Comment by learn9969** [comment]
Yes it is. I didnt know that. it's not a usable software if we can only use 1 feed.

**Comment by onovotny** [comment]
Closing a as a dup of #50 for now. We definitely want to support v3 endpoints but that's a significant amount of work. For now, please continue to use the v2 endpoints.

**Comment by svick** [comment]
> when used with any other url eg https://api.nuget.org/v3/index.json or myget urls I get an error

In case it was unclear: Adding other URLs works, as long as they are v2. Since MyGet does support v2, you just have to make sure to use that URL and not v3.
