### ISSUE TITLE
Crash when adding Framework Assembly Refs

### ISSUE THREAD

**Issue by heroius** [NuGetPackageExplorer/NuGetPackageExplorer#315]
**Type** : Bug

**NPE version**: 3.25.0

**Installed from**:  Zip on CodePlex

**OS version**: Win 10 x64 Home 1709 (16299.192)

**Program stops working when trying to add a Framework Assembly Reference.**

In the 'Package metadata' panel, when try to _add_ a Framework Assembly Reference (by clicking the plus mark beside the editor-box, in the 'Framework assemblies' groupbox), the program stops, and the windows error report dialog popup (says nothing but there is an error), and all is over.

If a package has several framework assemblies refs already, it stays fine -- you just cannot add new refs.

It might be important to notice that: _the Assembly Name dropdown list is empty(contains no item)_.

This happens everytime no matter editing an existing package, or creating a new one.

Runing it under Administrator makes no change.

**Comment by 304NotModified** [comment]
Hi!

Could you please try this with the latest CI version? (4.x) - https://nugetpackageexplorer.blob.core.windows.net/nightly/PackageExplorer.Package.Nightly.appxbundle 

(installed as NPE nightly) 

thanks!

**Comment by onovotny** [comment]
Closing as this should be fixed in 4.x Please reopen if still an issue with those.
