### ISSUE TITLE
BSODs with NPE Windows Store App

### ISSUE THREAD

**Issue by Monte-Christo** [NuGetPackageExplorer/NuGetPackageExplorer#322]
**Type**: Bug

**NPE version**: 3.24.0.0

**Installed from**: Windows Store

I am getting a BSOD (UNEXPECTED_KERNEL_MODE_TRAP) upon first start of NPE and then every time I try to add an new item to a newly created package. Never had a BSOD on my laptop before.

Switched to VS 2017 package creation using msbuild which works like a charm.

Win 10 Pro, 1709 (Build 16299.192).

Minidumps attached.

[Desktop.zip](https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/files/1649765/Desktop.zip)

**Comment by onovotny** [comment]
I think this is a Windows bug and I'd suggest raising it in the feedback hub or other similar channels. There's nothing NPE does directly that can trigger a BSOD.
