### ISSUE TITLE
Store version is out of date

### ISSUE THREAD

**Issue by Zastai** [NuGetPackageExplorer/NuGetPackageExplorer#323]
**Type**: Feature request (I guess)
**NPE version**: 3.24.0.0
**Installed from**: Windows Store

Even though README.md claims the Windows Store version is 4.0.11.0, this is not in fact the case (at least not in Belgium). The store installs version 3.24.0.0.

**Comment by onovotny** [comment]
Sorry about that...the badge gets updated during publish, which equates to store submission. It then takes 1-4 days to go through the store publish process. I don't know of a way to get a badge based on the what's visible. I'll be available soon!

**Comment by Zastai** [comment]
Ah, I had not realized the 4.0.11 release was so recent. Thanks for the update!

**Comment by Zastai** [comment]
Seems to still be at 3.24 on the store.

**Comment by onovotny** [comment]
Yeah, it's taking longer than I thought due to some unexpected store issues. Working on it. In the mean time, the CI/Nightly build is pretty much the same thing.

**Comment by onovotny** [comment]
FWIW #335 is related to this, hopefully will be visible soon.

**Comment by maxraab** [comment]
Finally the new version (4.0.12) is available in the store.
