### ISSUE TITLE
Remove "Great! Your are running on Windows 8"

### ISSUE THREAD

**Issue by 304NotModified** [NuGetPackageExplorer/NuGetPackageExplorer#33]
![image](https://cloud.githubusercontent.com/assets/5808377/12536519/0e822a66-c2a8-11e5-8e1d-b27fe2f5a417.png)

- First of all, Windows 8 isn't great...
- Second, I'm running Window 10
- Last, but not least, this version is not maintained and not good rated. Last release in 2013.  

Proposal: remove this popup, at least until the version in the Window Store is maintained. 

![image](https://cloud.githubusercontent.com/assets/5808377/12536532/5ef826a8-c2a8-11e5-8cac-2712839be05c.png)

**Comment by 304NotModified** [comment]
@dsplaisted @rikoe 

Please your opinion on this. Thanks!

**Comment by 304NotModified** [comment]
merged this already as it was really annoying in Windows 10

**Comment by rikoe** [comment]
Great, thanks. Good catch.
