### ISSUE TITLE
Publish Package does not work

### ISSUE THREAD

**Issue by campersau** [NuGetPackageExplorer/NuGetPackageExplorer#331]
**Type**: Bug

**NPE version**: master

**Installed from**: Compiled from source!

- What is the current result?
Publishing a package does not work, because the publish button is always disabled.

- What is the expected result?
Publish button should not be disabled if all required data is available.

- Is there a version in which it did worked? 
The bug was introduced by https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/pull/256.
The publish dialog is using a `BindingGroup` for validation so bindings are not applied until [`UpdateSources`](https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/a75b6d687f40e520085b3e80df8520cb5437a7a9/PackageExplorer/PublishPackageWindow.xaml.cs#L20) is called. So the [`IsAuthSet`](https://github.com/ironicnet/NuGetPackageExplorer/blob/a9d485c4fe0c11fecb11118d158b0ee1cb5ab287/PackageExplorer/PublishPackageWindow.xaml#L116) property does never change. 

![image](https://user-images.githubusercontent.com/4009570/35478987-930e7c5e-03eb-11e8-9a19-abefb9161740.png)

**Comment by eicthecat** [comment]
A simple solution is to add the updateSourceTrigger=PropertyChanged on the PublishPackageWindow.xaml file as following :
[PublishPackageWindow.zip](https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/files/1681883/PublishPackageWindow.zip)


<TextBox x:Name="PublishKey" VerticalContentAlignment="Center" IsEnabled="{Binding CanPublish}" Margin="0" Text="{Binding PublishKey, UpdateSourceTrigger=PropertyChanged}">

**Comment by campersau** [comment]
Thanks @eicthecat I have provided your solution in a separate commit https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/pull/332/commits/ca8fad5559010dde81effc203750695df7ebbbcb 

Note: this can also be fixed by #326 which removes the "Credentials" completly.

**Comment by onovotny** [comment]
Fixed by #326
