### ISSUE TITLE
Publish Button in Publish Package Window of Nuget Server is disabled/grayed out

### ISSUE THREAD

**Issue by AtallPreston** [NuGetPackageExplorer/NuGetPackageExplorer#355]
Question:  We have had a local nuget server up and running for about a year now.  Everything has worked well when publishing a new package or updating one.  This week however, when going to publish an updated version of a nuget package to our server, we noticed that the publish button in the publish package window was grayed out/disabled.  What would cause this?  Our publish url (local web server) and publish key have not changed that we are aware of.  If this is not a bug, what do I need to check to see about getting it to enable again?

Thanks

**NPE version**: 4.0.12 + g90e2a8e0fd

**Installed from**: Windows Store

**Comment by onovotny** [comment]
@AtallPreston Can you try the Nightly build? There were some changes/fixes in that area.

**Comment by campersau** [comment]
See https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/issues/331 and https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/issues/346

**Comment by AtallPreston** [comment]
@onovotny  I did just download that one - looks like version 4.1.32 - and it worked.  So I will continue to use the newer version.  Thanks!
