### ISSUE TITLE
Error opening Portable.BouncyCastle

### ISSUE THREAD

**Issue by bc3tech** [NuGetPackageExplorer/NuGetPackageExplorer#37]
v3.0.0.4 of Windows Store app throws:
![Error dialog](http://content.screencast.com/users/bc3tech/folders/Snagit/media/15353dac-948d-4bfc-9a0e-48266cacd9e5/01.27.2016-11.09.png)

for the [Portable.BouncyCastle](http://www.nuget.org/packages/Portable.BouncyCastle/) project

**Comment by 304NotModified** [comment]
Thanks. We're trying to reboot npe. The window store app isn't maintained yet. We look to it in the future if there is  more demand for it.

**Comment by bc3tech** [comment]
You should remove its Store listing then.

**Comment by 304NotModified** [comment]
@dsplaisted do we have permissions for that?

**Comment by bc3tech** [comment]
Turns out this fails in NPE proper as well:
![see](http://content.screencast.com/users/bc3tech/folders/Snagit/media/bc4529eb-ad3e-4a96-9156-f5424fe33486/01.27.2016-12.51.png)

**Comment by 304NotModified** [comment]
Yes,  that will be fixed in the new release (already fixed in master) . Too bad we have troubles releasing the clickonce  (it will be the first release after maintainer move) . Something with signing and file associations

**Comment by 304NotModified** [comment]
This should be fixed in 3.10. 

https://npe.codeplex.com/downloads/get/clickOnce/NuGetPackageExplorer.application

**Comment by 304NotModified** [comment]
Will close this as this has been fixed in 3.10

![image](https://cloud.githubusercontent.com/assets/5808377/13202971/b106b400-d8ab-11e5-91ed-21e2f58f8526.png)


If you still experiencing problems, please let us know!
