### ISSUE TITLE
Improve package chooser dialog

### ISSUE THREAD

**Issue by onovotny** [NuGetPackageExplorer/NuGetPackageExplorer#372]
The current package chooser dialog is a basic grid. The NuGet API provides a lot more rich data, and it'd be nice to have a chooser dialog that looks a lot closer to the one VS uses.

**Comment by khaister** [comment]
@onovotny What do you envision the improved dialog should look like?

**Comment by onovotny** [comment]
I was hoping to make it like VS:

Not necessarily the dark theme, but based largely on their XAML. Just not tied to the VS object model.
![image](https://user-images.githubusercontent.com/1427284/38633588-2e58ac94-3d8e-11e8-9306-a62a58324dfe.png)

**Comment by campersau** [comment]
FYI: Here is the source code of the VS UI:
https://github.com/NuGet/NuGet.Client/tree/dev/src/NuGet.Clients/NuGet.PackageManagement.UI

Interesting things:
- the main UI https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/NuGet.PackageManagement.UI/Xamls/PackageManagerControl.xaml
- the list https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/NuGet.PackageManagement.UI/Xamls/InfiniteScrollList.xaml
- the details https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/NuGet.PackageManagement.UI/Xamls/DetailControl.xaml
- the metadata https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/NuGet.PackageManagement.UI/Xamls/PackageMetadataControl.xaml

**Comment by khaister** [comment]
I have a working UI change. Would you like a PR?

![image](https://user-images.githubusercontent.com/1192669/38759289-02ebf3ca-3f2a-11e8-86e0-a95a202a9e53.png)

**Comment by onovotny** [comment]
@khaister Definitely!

**Comment by onovotny** [comment]
Fixed by @khaister, major thank you!
