### ISSUE TITLE
Just need an exe

### ISSUE THREAD

**Issue by aptbid2005** [NuGetPackageExplorer/NuGetPackageExplorer#378]
Question:

Work has my access neutered.

I do not have access to the windows store on my work machine and powershell scripts are disabled. Also, I cannot build the project due to missing components. FML.

Can I just get an exe from you guys so I can publish my dlls to my local Nuget server? I've used this product in the past and it worked great. I'd like to use it again.

Someone please help :) Thanks.

**Comment by onovotny** [comment]
There's two options:

1. Best approach - use the CI build and you should be able to double-click to install it. No powershell scripts required.
2. On the releases tab, we have a zip file.

The CI build is easiest since you can easily update it anytime by downloading/running it again.

**Comment by aptbid2005** [comment]
Thank you very much, I didn't see the releases tab. Sorry for bothering you with a trivial matter.
