### ISSUE TITLE
Support drag & drop of files to outside of NPE

### ISSUE THREAD

**Issue by svick** [NuGetPackageExplorer/NuGetPackageExplorer#383]
**Type**: Feature request

**NPE version**: 4.2.13

**Installed from**: Windows Store

I wanted to extract a file from a NuGet package, so I did the obvious thing: open the package in NPE and then drag and drop the file from NPE to a folder. But it didn't work, the mouse cursor turns into the "you can't drop here" state.

Pretty much the same thing can be accomplished by selecting "Save As…" from the context menu, so this is just a convenience feature.

**Comment by campersau** [comment]
I am currently working on it. Also going to implement copy & past (both ways) (maybe also with context menu).
This will only work for single files (not folders) for now.
