### ISSUE TITLE
Undo hacky ref->lib workaround when VS is fixed

### ISSUE THREAD

**Issue by onovotny** [NuGetPackageExplorer/NuGetPackageExplorer#397]
Tracking issue to undo this hack once the underlying issue in VS is fixed:
https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/pull/394

**Comment by campersau** [comment]
Response from Microsoft:
> Thank you for your feedback! We have determined that this issue is not a bug.
This is by design.
ref folders always take precedence over lib.
I'd suggest contacting the package owner if you are having issues with the package.

https://developercommunity.visualstudio.com/content/problem/231208/wap-project-references-wrong-nuget-package-dlls-re.html

**Comment by campersau** [comment]
Another response from Microsoft:
> Thank you for your feedback! There was an issue in WAP projects that we addressed in 15.7 Preview causing us to package the reference assemblies instead of the lib assemblies, if you are referring to build time, we should be using the ref assemblies to build. Thank you for helping us build a better Visual Studio!

I can check if this works in VS Preview on friday.

**Comment by onovotny** [comment]
@campersau It's fixed in 15.7 preview 4.
