### ISSUE TITLE
Windows Authentication fails

### ISSUE THREAD

**Issue by 304NotModified** [NuGetPackageExplorer/NuGetPackageExplorer#4]
Copy of https://npe.codeplex.com/workitem/142

-----
Hello folks, 
I recently tried out the tool NuGet Package Explorer, and I have to say that it is a very comfortable tool. 
On my NuGet server I activated the Windows Authentification in my IIS properties. 
The problem is that the Package Explorer responds me: 
Failed to process request: 'Unauthorized'.
How about adding Windows Authetification support? 

greetings 
Nico
comments

WhiteIntel wrote Apr 14, 2014 at 9:31 PM

Anyone?
WhiteIntel wrote May 7, 2014 at 9:56 PM

Does anyone take care about the posted issues?!
dobossandor wrote Sep 15, 2014 at 5:48 PM

Same issue with Basic authentication.
Nuget Package Explorer 3.9.0.0
dobossandor wrote Sep 15, 2014 at 5:56 PM

Something went wrong between 3.6.0.0 and 3.7.0.0.
Just tried these. 3.6.0.0 works, 3.7.0.0 isnt. (At least with basic auth)
rouslanp wrote May 13 at 5:50 PM

Windows Authentication is an extremely important feature for those who dared to maintain their own NuGet repositories. Please fix this bug!

--------

**Comment by rikoe** [comment]
My merge in #16 should fix this - I just need to rebase and test my fix on this repo.

**Comment by 304NotModified** [comment]
:+1:

FYI 

I think rebase won't work, because the commit sha are different every import (from codeplex) 

If it does work, let me know. :)

**Comment by 304NotModified** [comment]
@rikoe did you see the Admin invite?

**Comment by rikoe** [comment]
I didn't, I'll take a look. Thanks!

**Comment by 304NotModified** [comment]
Fixed by #49
