### ISSUE TITLE
A local file header is corrupt - while saving

### ISSUE THREAD

**Issue by leofucci** [NuGetPackageExplorer/NuGetPackageExplorer#403]
Hi! Thanks for reporting this feature/bug/question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

**Type** (choose one):

- Bug

**NPE version**: (e.g. 3.12) (see Help -> about)
4.2.13+g3c91390f30

**Installed from**: ClickOnce / chocolatey.org / Zip on CodePlex / Windows Store
Windows Store

In case of a BUG:

- What is the current result?
"A local file header is corrupt" message shown while saving everytime. Not sure if file is actually saved.

Steps to reproduce, open any existing package, press CTRL+S, then press CTRL+S again.
Message will pop with mentioned error.

- What is the expected result?
To save without warnings.

- Please post full exception details in case of an Exception (message, stacktrace, inner exceptions).

- Are there any workarounds? yes/no
yes, close file and try again.

- Is there a version in which it did work?
I experienced this issue since previous non-windows store version.

- Is there a package on Nuget.org which shows the bug?
no.

In case of a FEATURE REQUEST:
 
 - Why do we need it?
 - Please provide an use case.

![image](https://user-images.githubusercontent.com/38676737/39162431-d8babfa8-474b-11e8-8cf7-fd789224ed01.png)

**Comment by onovotny** [comment]
Dup of #376

**Comment by onovotny** [comment]
Fixed by #459
