### ISSUE TITLE
Package Explorer Limit is now 15

### ISSUE THREAD

**Issue by 304NotModified** [NuGetPackageExplorer/NuGetPackageExplorer#41]
From https://npe.codeplex.com/workitem/167

> I am unable to see more than 15 packages when using a filter. When I type "StructureMap", I get a lot of packages, but can only see 15. Evening trying to sort by Id doesn't seem to work when I use a filter.

![image](https://cloud.githubusercontent.com/assets/5808377/13203142/9203afae-d8b0-11e5-8cbc-60b41d3d8aa3.png)

**Comment by rikoe** [comment]
How do you reproduce this issue? I see 153 packages for StructureMap, with 15 per page

**Comment by 304NotModified** [comment]
Indeed, this seems to be fixed

![image](https://cloud.githubusercontent.com/assets/5808377/13245746/830a9070-da0f-11e5-9836-e8adb3686e6f.png)
