### ISSUE TITLE
File -> Open from Feed opens the dialog in the previous location; should be center parent

### ISSUE THREAD

**Issue by khaister** [NuGetPackageExplorer/NuGetPackageExplorer#418]
**Type** (choose one):

- **Bug**
- ~Feature request~
- ~Question~

**NPE version**: "Edge" Version

**Installed from**: Built from Source

- *What is the current result?* The package chooser dialog shows up in the previously opened location.
- *What is the expected result?* The dialog should be center parent (`CenterOwner`).
- *Are there any workarounds?* Not that I know of.
- *Is there a version in which it did work?* Not that I know of.

**Comment by khaister** [comment]
@onovotny This issue is caused by the fact that the dialog is hidden by calling `Hide()` method, which causes the window to be invisible instead of being destroyed. So this is expected. Do you still want to enhance the dialog to show center of parent?

**Comment by onovotny** [comment]
@khaister Yes, I think that's better behavior.

**Comment by khaister** [comment]
@onovotny We can try calling `Close()` explicitly but when the window gets instantiated every time it opens. What do you think?

**Comment by onovotny** [comment]
That should be ok
