### ISSUE TITLE
Add dotnet 5.3, 5.2, 5.1, 5.0.  

### ISSUE THREAD

**Issue by 304NotModified** [NuGetPackageExplorer/NuGetPackageExplorer#42]
Add dotnet5.3,  dotnet5.2,  dotnet5.1,  dotnet5.0. 

to https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/7164cbf205c987e9fa7ff445a481b74cc2f83085/PackageExplorer/PackageViewer.xaml.cs (note "key-value" array)

more info: https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md#mapping-the-net-platform-standard-to-platforms

**Comment by onovotny** [comment]
Please don't. dotnet is being replaced with netstandard.

**Comment by 304NotModified** [comment]
Will there be a 1.6?

Finding up to date docs about this is really hard there days.

**Comment by onovotny** [comment]
Hard to say....maybe the dialog should either prompt for a folder name or leave the version off. I don't think it's worth trying to keep up with them...or just update the context menu as necessary.

**Comment by 304NotModified** [comment]
This is not needed anymore as we don't crash on unknown platforms anymore: #68
