### ISSUE TITLE
VS2017 freezes during Loading switching between Installed Browse etc

### ISSUE THREAD

**Issue by mwpowellhtx** [NuGetPackageExplorer/NuGetPackageExplorer#421]
Running against the latest ``VS2017`` bits, as far as I know. The default view is ``Installed``. I click to ``Browse``, and it hangs there frozen during mid-``Loading``.

A workaround is to not be so aggressive in the click, but I think that there is a task that should be canceled there.

**Comment by mwpowellhtx** [comment]
To be honest, I don't know. I see the symptoms starting with Package Explorer.

**Comment by mwpowellhtx** [comment]
@onovotny No, this is starting in the Package Explorer, for starters. Whether NuGet itself is the root cause, I cannot tell you.

**Comment by onovotny** [comment]
I'm not sure I understand the repro then, can you please elaborate?

**Comment by mwpowellhtx** [comment]
Just like my description states. The default view shows when I first open it; I click ``Browse``, and it is hanging. Not sure if this issue is a duplicate of another reported one or whether the errant behavior has been corrected by this point.

**Comment by onovotny** [comment]
Where do you see "Browse," there's item with that link.

![image](https://user-images.githubusercontent.com/1427284/44948998-7453a900-adf6-11e8-9d30-ac57f8417694.png)

**Comment by mwpowellhtx** [comment]
Perhaps I have my bits confused. *NuGet Package Manager*:

![image](https://user-images.githubusercontent.com/1824187/44949032-3d31c780-adf7-11e8-8a91-9107461975e4.png)

**Comment by onovotny** [comment]
Right, that's part of Visual Studio. Issues should be reported either via the "Report a Problem" icon in the top-right of Visual Studio and/or on the NuGet repo: https://github.com/nuget/home

This program uses some of their libraries, but is not the same team.
