### ISSUE TITLE
Can't preview RTF file

### ISSUE THREAD

**Issue by svick** [NuGetPackageExplorer/NuGetPackageExplorer#432]
**Type**: Bug

**NPE version**: 4.4.3

**Installed from**: Windows Store

When I try to preview the ThirdPartyNotices.rtf file from [the Microsoft.Net.Compilers 2.8.2 package](https://www.nuget.org/packages/Microsoft.Net.Compilers/2.8.2), I get the following exception:

```
*** The plugin that registers to read this file type fails to read the content of this file. ***
System.NotSupportedException: This operation is not supported.
   at System.IO.Compression.DeflateStream.get_Length()
   at PackageExplorer.RtfFileViewer.GetView(String extension, Stream stream)
   at PackageExplorerViewModel.ViewContentCommand.ShowFile(PackageFile file)
```

I don't know anything about this code, but the obvious workaround would be copy the `DeflateStream` into a `MemoryStream` and use that.

**Comment by campersau** [comment]
Yes, I did exactly this for the avalon editor for file editing https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/pull/330 . Do you want to send a PR? If not I can do it tomorrow.
