### ISSUE TITLE
Package file is locked while opened

### ISSUE THREAD

**Issue by ramonsmits** [NuGetPackageExplorer/NuGetPackageExplorer#434]
**Type** (choose one):

- Bug / Feature request

**NPE version**: 4.4.3
**Installed from**: Windows Store

When NPE has a package open, it locks the nuget zip file. It cannot be overwritten by visual studio which means NPE must exit or close the opened package.

It would be very nice if it would not lock the file while open or even auto-refresh detecting the file is overwritten.

**Comment by onovotny** [comment]
This has been a long-standing issue. NPE uses an open read/write in case the user makes a change and hits save.


I believe it should use an open read, and only use a read/write for any saves. 


PR's accepted :)
