### ISSUE TITLE
NPE should be able to view unlisted packages

### ISSUE THREAD

**Issue by onovotny** [NuGetPackageExplorer/NuGetPackageExplorer#435]
If you search an unlisted package, nothing shows up today. Unlisted packages still have metadata and there should be a way to show them.

Current example package: `System.Reflection.Emit.Lightweight`

Perhaps with another checkbox like "show unlisted"? Alternatively, if it needs to be an exact id to get to the metadata endpoint, then perhaps `id:System.Reflection.Emit.Lightweight` should try the metadata endpoint directly instead of the search endpoint (which filters out unlisted packages)?

**Comment by campersau** [comment]
There is a [`IncludeDelisted` property on `SearchFilter`](https://github.com/NuGet/NuGet.Client/blob/20bdc98381aa5824b94bc6e9dd38ddbf5102df26/src/NuGet.Core/NuGet.Protocol/SearchFilter.cs#L52-L55) but it does not work. Even with [`packageId:`](https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/issues/348#issuecomment-366490686). See https://github.com/NuGet/Home/issues/6234

So the only way to get unlisted packages is by its id with the [`PackageMetadataResource`](https://github.com/NuGet/NuGet.Client/blob/20bdc98381aa5824b94bc6e9dd38ddbf5102df26/src/NuGet.Core/NuGet.Protocol/Resources/PackageMetadataResource.cs#L13-L22).

Which means we can do it like the [previous implementation](https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/pull/351#issuecomment-366502772) by adding a special case for `id:`. I would suggest that searching by id implies "show unlisted".
