### ISSUE TITLE
Error Running Windows 10 Store App

### ISSUE THREAD

**Issue by DRBlagg** [NuGetPackageExplorer/NuGetPackageExplorer#438]
- Bug

**NPE version**: 4.4.3.0
**Installed from**:  Windows Store

- What is the current result?  Application Errors and does not run at all.
- What is the expected result? Application will run.
- Please post full exception details in case of an Exception (message, stacktrace, inner exceptions).
  (See attached screen shot.)
- Are there any workarounds? no
- Is there a version in which it did work? Older desktop based version on Windows 8 PC
- Is there a package on Nuget.org which shows the bug? n/a

![nugetpackageexplorererror](https://user-images.githubusercontent.com/20732135/41436586-c2cc77b2-6fe7-11e8-9333-dea05ca31d81.png)

**Comment by DRBlagg** [comment]
Never mind, even though I was an administrator of the PC, I had to go in and take ownership of the C:\Program Files\WindowsApps folder.  But maybe this will save someone else the headache.

**Comment by onovotny** [comment]
Do you have SQL Server running on your machine? Could be this issue (with a fix):
https://support.microsoft.com/en-us/help/4073393/fix-the-data-area-passed-to-a-system-call-is-too-small-error-when-you
