### ISSUE TITLE
Package source URL with a trailing space fails

### ISSUE THREAD

**Issue by onovotny** [NuGetPackageExplorer/NuGetPackageExplorer#442]
If you paste in a url for a feed source and leave a trailing space, loading fails.

Leading/trailing spaces should be trimmed.

**Comment by kyungjaeson** [comment]
Newbie here, 
I am interested in taking on this issue

**Comment by onovotny** [comment]
Yes, please fork and submit a PR.

**Comment by kyungjaeson** [comment]
PR up
