### ISSUE TITLE
Chocolatey version vs. GitHub release version

### ISSUE THREAD

**Issue by smarts** [NuGetPackageExplorer/NuGetPackageExplorer#445]
**Type** (choose one):
- Question

I see a chocolatey package for version 4.4.9, but no github release here in the repository, which makes me hesitant to upgrade. Is 4.4.9 a real version?

**Comment by onovotny** [comment]
4.4.9 is real, just fixes for Chocolatey only. I would recommend using the version from the Microsoft Store as it auto-updates.
