### ISSUE TITLE
Add deprecated monikers

### ISSUE THREAD

**Issue by 304NotModified** [NuGetPackageExplorer/NuGetPackageExplorer#45]
Add:

![image](https://cloud.githubusercontent.com/assets/5808377/13258012/92438244-da51-11e5-8bf9-705b0ee59346.png)

to

https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/7164cbf205c987e9fa7ff445a481b74cc2f83085/PackageExplorer/PackageViewer.xaml.cs (note "key-value" array)

See also:
https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md#deprecated-monikers

**Comment by rikoe** [comment]
Could you add some description as to what this feature would entail? I don't understand just from the link.

**Comment by 304NotModified** [comment]
edited!

**Comment by 304NotModified** [comment]
This is not needed anymore as we don't crash on unknown platforms anymore: https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/pull/68
