### ISSUE TITLE
BUG - Cannot save packages

### ISSUE THREAD

**Issue by TheOneAndOnlyKelly** [NuGetPackageExplorer/NuGetPackageExplorer#452]
Bug
NPE Version 4.4.53+g671b4f96f5
Installed From: Windows Store

Editting an existing package, cannot Save changes to the package metadata from the form, even if no changes were made. Clicking the check button does nothing at all. Selecting File|Save or File|Save As gives the message "The operation cannot be completed because the edit form has come invalid input".

If you bring up the Package Analysis pane beforehand never shows any issues with the package.

**Comment by onovotny** [comment]
Do you have a repro package? I can't repro with a simple package, so it could be something in that particular one?

**Comment by TheOneAndOnlyKelly** [comment]
I have tried with a number of packages I have pulled down from our local nuget. I tested with my own packages along with others created by other developers.

**Comment by TheOneAndOnlyKelly** [comment]
Tried with packages pulled from the feed and saved locally on my disk. No difference.

**Comment by TheOneAndOnlyKelly** [comment]
I can edit the metadata source as a text field, so that is a workaround solution.

**Comment by onovotny** [comment]
I think I can repro, stand by

**Comment by onovotny** [comment]
This will be in the CI feed as soon as it updates; it takes a few days for the Store to publish it. The CI version can run SxS with the Store version.
