### ISSUE TITLE
BUG - Cannot drag and drop files

### ISSUE THREAD

**Issue by TheOneAndOnlyKelly** [NuGetPackageExplorer/NuGetPackageExplorer#453]
Bug
NPE Version 4.4.53+g671b4f96f5
Installed From: Windows Store

When adding/updating files to the Package Contents pane, you cannot drag files off of a Windows Explorer folder. This was something you could do in earlier releases and was very, very convenient.

**Comment by onovotny** [comment]
I just tried this and it works for me. Does this happen for all packages, or just a specific one?

**Comment by TheOneAndOnlyKelly** [comment]
Okay, just retested and it works. It had been broken for quite a while. Disregard issue.
