### ISSUE TITLE
Get code certificate to prevent Smartscreen notification

### ISSUE THREAD

**Issue by 304NotModified** [NuGetPackageExplorer/NuGetPackageExplorer#46]
We get a smartscreen error because we don't have a (valid) code signing certificate (which isn't the same as a SSL certificate and a lot more expensive)

![image](https://cloud.githubusercontent.com/assets/5808377/14502356/2e40840a-01ab-11e6-99ee-6b033f59d05d.png)

**Comment by 304NotModified** [comment]
@dsplaisted 

I saw your post on twitter. Any luck on this? How to continue?

**Comment by onovotny** [comment]
This isn't really needed anymore for people that use the Windows Store version. The only place this impacts is the Chocolatey version.

**Comment by 304NotModified** [comment]
I don't think this is needed for the Chocolatey version?

**Comment by onovotny** [comment]
Technically, smart screen still could have an error/warning for running an untrusted binary. If it hasn't been an issue with choco, then we can close this. Just wasn't sure.

**Comment by 304NotModified** [comment]
this is not needed anymore.
