### ISSUE TITLE
Add repository field to nuspec editor

### ISSUE THREAD

**Issue by quasarea** [NuGetPackageExplorer/NuGetPackageExplorer#476]
Feature request 

 - Why do we need it?
It is a valid field already specifed in documentation https://docs.microsoft.com/en-us/nuget/reference/nuspec

 - Please provide an use case.
Adding this data enables use of SourceLink in vs2017 while debugging

**Comment by quasarea** [comment]
Possibly duplicate of #354

**Comment by onovotny** [comment]
This is valid -- we display it but do not have it in the editor yet.
