### ISSUE TITLE
Display SourceLink enabled status

### ISSUE THREAD

**Issue by JamesNK** [NuGetPackageExplorer/NuGetPackageExplorer#496]
- Feature request

Today NPE displays repository information on a package. This is only some of the metadata that SourceLink adds. NPE does not show whether the DLL/PDB files have correct SourceLink information.

Note: this can be done today using a command line tool - https://github.com/ctaggart/SourceLink#test
 
 - Why do we need it?

NPE would provide package authors a visual way to verify that SourceLink is enabled.

**Comment by onovotny** [comment]
Sounds great! Definitely a useful feature to test validity of contained packages

**Comment by onovotny** [comment]
@JamesNK Would a content viewer that shows the source information suffice?

The code in the sourcelink repo appears to go further and download each source to validate the hashes. Are you looking for that as well?

**Comment by JamesNK** [comment]
I think showing information is enough. Validating against the source would have perf implications. The dotnet tool can be used if someone wants to validate.

**Comment by onovotny** [comment]
Available in build 4.5.86 and higher. In the CI feed first, then others soon.
