### ISSUE TITLE
Use NuGet v3 API package source

### ISSUE THREAD

**Issue by rikoe** [NuGetPackageExplorer/NuGetPackageExplorer#50]
I don't know much about it yet, but is it conceivable to add the option to https://api.nuget.org/v3/index.json (the v3 JSON-LD URL) as package source?

**Comment by 304NotModified** [comment]
Yes, we need that. Dunno what have to be changed for that.

**Comment by rikoe** [comment]
I would suggest looking at the code for the NuGet Visual Studio extension and/or command line tools to see how they use the v3 API - there's not a lot of documentation around it currently from the looks of things.

**Comment by 304NotModified** [comment]
I guess there is a [Nuget package for it](https://www.nuget.org/packages?q=nuget)

**Comment by 304NotModified** [comment]
See http://blog.nuget.org/20160216/Switching-from-WCF-OData-to-Web-API.html

**Comment by onovotny** [comment]
Why can't you just use the NuGet client libraries directly? They are open source after all. No need to reinvent the wheel.

**Comment by 304NotModified** [comment]
Yes that was also my intention :)

**Comment by 304NotModified** [comment]
Current error: 

![image](https://cloud.githubusercontent.com/assets/5808377/21532617/283fa46e-cd52-11e6-9b40-fd917d1cab96.png)
