### ISSUE TITLE
[Bug] Hard crash on app start (versions 4.5.26+)

### ISSUE THREAD

**Issue by GoodmanEScott** [NuGetPackageExplorer/NuGetPackageExplorer#500]
### Steps to reproduce
1. Download the release zip from https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/releases
2.  Unzip the zip file using 7zip
3. Execute NuGetPackageExplorer.exe from Windows Explorer 

### Result
The program immediately crashes with the following error message: The application was unable to start correctly (0x0000005). Click OK to close the application.

**Note**
Also had the same result when executing version 4.5.46 installed via Chocolatey.

### Reproduced with versions
4.5.26
4.5.27
4.5.46

### Eventvwr log
Faulting application name: bad_module_info, version: 0.0.0.0, time stamp: 0x00000000
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0x00000001
Fault offset: 0x00000000
Faulting process id: 0x3164
Faulting application start time: 0x01d46e4375c0e675
Faulting application path: bad_module_info
Faulting module path: unknown
Report Id: 501ba2ed-61f5-4906-866a-67617c16194d
Faulting package full name: 
Faulting package-relative application ID: 

### Is there a version in which it did work?
Version 4.5.9 seems to work

### systeminfo

OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.16299 N/A Build 16299
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Member Workstation
OS Build Type:             Multiprocessor Free
Product ID:                00329-10180-00000-AA554
Original Install Date:     11/22/2017, 6:52:08 PM
System Boot Time:          10/22/2018, 4:44:08 PM
System Manufacturer:       Dell Inc.
System Model:              Precision 3510
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 94 Stepping 3 GenuineIntel ~2400 Mhz
BIOS Version:              Dell Inc. 1.12.6, 2/7/2017
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume4
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC-05:00) Eastern Time (US & Canada)
Total Physical Memory:     16,266 MB
Available Physical Memory: 9,032 MB
Virtual Memory: Max Size:  18,698 MB
Virtual Memory: Available: 10,540 MB
Virtual Memory: In Use:    8,158 MB
Page File Location(s):     C:\pagefile.sys
Hotfix(s):                 13 Hotfix(s) Installed.
                           [01]: KB4048951
                           [02]: KB4053577
                           [03]: KB4054022
                           [04]: KB4056887
                           [05]: KB4073120
                           [06]: KB4074595
                           [07]: KB4088785
                           [08]: KB4103729
                           [09]: KB4131372
                           [10]: KB4132650
                           [11]: KB4287903
                           [12]: KB4457146
                           [13]: KB4457136
Network Card(s):           3 NIC(s) Installed.
                           [01]: Intel(R) Dual Band Wireless-AC 8260
                                 Connection Name: Wi-Fi
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.1.1
                                 IP address(es)
                                 [01]: 192.168.1.58
                                 [02]: fe80::71e7:a426:2556:68c4
                           [02]: Intel(R) Ethernet Connection (2) I219-LM
                                 Connection Name: Ethernet
                                 Status:          Media disconnected
                           [03]: Bluetooth Device (Personal Area Network)
                                 Connection Name: Bluetooth Network Connection 3
                                 Status:          Media disconnected
Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
                           Virtualization Enabled In Firmware: Yes
                           Second Level Address Translation: Yes
                           Data Execution Prevention Available: Yes

**Comment by onovotny** [comment]
I'm not sure here and I can't repro it. Looking up `bad_module_info` appears to affect other programs, mainly games, as well. You might want to try some of their suggested fixes and report back if anything worked.

One thread here mentions some 3rd party software from Razer might be a cause:
https://help.daybreakgames.com/hc/en-us/articles/360000660427-What-causes-Bad-module-info-errors-

Not sure what I can do here specifically.

**Comment by GoodmanEScott** [comment]
On Monday I'll check with some co-workers who have similar workstations to see if they run into the same problem.

**Comment by GoodmanEScott** [comment]
Looks like its just my machine =\

**Comment by aStefanW** [comment]
Obviously it's not just your machine, I've got exactly the same problem. And Version 4.5.9 seems to work for me also.
