### ISSUE TITLE
Problem running NuGetPackageExplorer on Chocolatey Test Environment

### ISSUE THREAD

**Issue by gep13** [NuGetPackageExplorer/NuGetPackageExplorer#501]
Following a conversation with Oren on Twitter:

https://twitter.com/onovotny/status/1056553141573951490

I took the latest Chocolatey Package for NuGet Package Explorer for a spin on the Chocolatey Test Environment.  While the installation went fine, running the application resulted in the following:

![image](https://user-images.githubusercontent.com/1271146/47618193-1c6cb200-dac8-11e8-8862-b08b866efc3f.png)

The Stack Trace in Event Viewer shows the following:

![image](https://user-images.githubusercontent.com/1271146/47618203-3d350780-dac8-11e8-8e7d-f9d678869782.png)

As a test, I went ahead and installed the .Net Framework 4.7.2, just to make sure that it wasn't a runtime issue (`choco install dotnet4.7.2`), however, that still resulted in the same.

However, doing `choco install vcredist140`) made the application work:

![image](https://user-images.githubusercontent.com/1271146/47618223-71a8c380-dac8-11e8-9758-8a352997381f.png)

Looks like the self contained publish is missing something to make it work in all scenarios.

**Comment by onovotny** [comment]
@gep13 Can you please test https://dev.azure.com/onovotny/GitBuilds/_build/results?buildId=1402&view=results

I added the `vcredist140` as a temporary workaround.

**Comment by gep13** [comment]
>@onovotny said...
What do you mean by this?

Last time we spoke about this, you mentioned that you thought there was something "missing" in the generated standalone package.  I was wondering if you had been following up with the relevant Microsoft Team (via GitHub issues) to try to narrow down what is wrong, or whether a dependency on vcredist is "working as expected".

**Comment by onovotny** [comment]
It's being looked at separately. I put this workaround in since I want to make this the default in master and published once .NET Core 3 preview 1 hits.

I'll close this out for now, but I'll add another issue to track removing the dependency.
