### ISSUE TITLE
Unable to create PreRelease packages

### ISSUE THREAD

**Issue by arnoldpistorius** [NuGetPackageExplorer/NuGetPackageExplorer#51]
I used to create pre release packages by adding a suffix to the version number. In my case I was adding -A (for example: 1.0.1-A) to the end of the version number. 

With the new version (released on Feb 21st 2016) I get the error "A stable release must not have a dependency on a prerelease package" 

The fact is I am trying to publish the package as a prerelease, not stable. (see screenshot attached). 

In the previous version, the GUI showed: "Version number (Prerelease)" in the version section.

![package](https://cloud.githubusercontent.com/assets/6072267/13245856/5b9272dc-da10-11e5-981b-baccc76f926e.png)

**Comment by arnoldpistorius** [comment]
Someone probably created a fix in this pull request:

https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/pull/47

**Comment by 304NotModified** [comment]
Yes, #47 should fix this.

**Comment by 304NotModified** [comment]
Fixed by #47

**Comment by 304NotModified** [comment]
3.11 has been released! Thanks for the issue report!
