### ISSUE TITLE
'Save As' does not truncate existing file leading to file corruption

### ISSUE THREAD

**Issue by skennedyfromfresche** [NuGetPackageExplorer/NuGetPackageExplorer#516]
- Bug

**NPE version**: 4.5.62

**Installed from**: Windows Store

- What is the current result?
Calling 'Save As' command and targeting an existing file copies its content but does not terminate contents correctly leaving previous old content at end of file. For example if the file is XML and was previously longer than the updated file content then the XML will potentially be invalid post 'Save As'.

- What is the expected result?
Calling 'Save As' command and targeting an existing file should completely replace its content and none of the previous content should remain.

- Are there any workarounds? 
You can work around this by deleting the old destination file first. However if your not aware of this issue it may show up as errors (in our case corrupt XML) when opening file in other applications. We originally thought this was a bug in our own code that generated the file in the first place.

- Is there a version in which it did work?
This is the first version I've used so not sure.

- Is there a package on Nuget.org which shows the bug?
Not sure. I don't believe this is specific to any nuget package.

**Comment by onovotny** [comment]
Do you have any repro steps? I'm looking at the code paths and don't see where this could be happening?

Thanks

**Comment by skennedyfromfresche** [comment]
Hi @onovotny 

I noticed that you've already created a release for the fix for this issue (which I have verified works).

Do you still require repo steps?
