### ISSUE TITLE
Unable to open snupkg

### ISSUE THREAD

**Issue by JamesNK** [NuGetPackageExplorer/NuGetPackageExplorer#531]
Bug

**NPE version**: 4.5.88

**Installed from**:  Windows Store

Double clicking on a snupkg prompts you with the "Common tasks" dialog instead of opening the package. And choosing a snupkg from the open dialog does nothing.

Would expect symbol package to open in NPE

**Comment by onovotny** [comment]
Should be fixed in 4.6.4 in the CI channel.
