### ISSUE TITLE
Suggestion: Leverage the NugetGet Client package for references

### ISSUE THREAD

**Issue by ravensorb** [NuGetPackageExplorer/NuGetPackageExplorer#54]
Now that the NuGet framework has gone full opensource with its components broken out it is easier than ever to leverage it in other solutions.  It might reduce maintenance if all of the constants, and framework version information was pulled from it rather than duplicating it all.  

For example take a look at this class: [DefaultFrameworkMappings.cs](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Frameworks/DefaultFrameworkMappings.cs) and [FrameworkConstants.cs](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Frameworks/FrameworkConstants.cs) in the NuGet client assembly

as I think they contain most of what would be needed.

**Comment by 304NotModified** [comment]
Good idea! Is this a nuget package?

**Comment by ravensorb** [comment]
Yes -- look for [NuGet.Client.V3NuGet.Client.V3](https://www.nuget.org/packages/NuGet.Client.V3/)

**Comment by ravensorb** [comment]
Here is something that could help alot

[FrameworkNameHelpers.cs] (https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Frameworks/FrameworkNameHelpers.cs)

**Comment by 304NotModified** [comment]
This would be a big enhancement. :)

**Comment by 304NotModified** [comment]
Fixed by https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/pull/147
