### ISSUE TITLE
Cannot open package built with PackageLicenseExpression

### ISSUE THREAD

**Issue by adamralph** [NuGetPackageExplorer/NuGetPackageExplorer#543]
**Type** (choose one):

- Question

**NPE version**: 4.7.19

**Installed from**: Windows Store

Asking a question, because I know there's a bug somewhere, but I don't know if it's in NPE or in NuGet.

When I pack [this project](https://github.com/adamralph/minver/blob/00b31c21002384b4ac7409cda5c5b9c434d5a475/MinVer/MinVer.csproj) with `dotnet pack` and then try and open the package in NPE, I get:

<img src="https://user-images.githubusercontent.com/677704/48953873-949f8980-ef47-11e8-92c4-091a8acd8642.png" width="411px" />

And indeed, I see both those in the nuspec:

```xml
    <license type="expression">Apache-2.0</license>
    <licenseUrl>https://licenses.nuget.org/Apache-2.0</licenseUrl>
```

[MinVer.1.0.0-adhoc.zip](https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/files/2611327/MinVer.1.0.0-adhoc.zip)

As you can see in the project, I'm only specifying `PackageLicenseExpression`.

**Comment by campersau** [comment]
I guess this is already fixed by https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/pull/542. A new version will be available soon.

**Comment by adamralph** [comment]
Thanks @campersau. I tried to find an issue before I raised this one but I couldn't find one.
