### ISSUE TITLE
System.DllNotFoundException: dwrite.dll ---> System.ComponentModel.Win32Exception: Access is denied.

### ISSUE THREAD

**Issue by ddechant** [NuGetPackageExplorer/NuGetPackageExplorer#565]
**Type** (choose one):
- Bug

**NPE version**: (e.g. 5.x) (see Help -> about)
5.0.78.0

**Installed from**: 
Microsoft Store

- What is the current result?
The application does not run. 
- What is the expected result?
The application should run
- Please post full exception details in case of an Exception (message, stacktrace, inner exceptions).
Stack trace from event logs:
```
Application: NuGetPackageExplorer.exe
CoreCLR Version: 4.6.27121.3
Description: The process was terminated due to an unhandled exception.
Exception Info: System.TypeInitializationException: The type initializer for 'System.Windows.Application' threw an exception. ---> System.TypeInitializationException: The type initializer for '<Module>' threw an exception. ---> <CrtImplementationDetails>.ModuleLoadException: The C++ module failed to load during appdomain initialization.
 ---> System.DllNotFoundException: dwrite.dll ---> System.ComponentModel.Win32Exception: Access is denied.
   --- End of inner exception stack trace ---
   at MS.Internal.NativeWPFDLLLoader.LoadDwrite()
   at CModuleInitialize.{ctor}(CModuleInitialize* , IntPtr cleaningUpFunc)
   at ?A0xf3e61052.CreateCModuleInitialize()
   at ?A0xf3e61052.??__E?A0xf3e61052@cmiStartupRunner@@YMXXZ()
   at _initterm_m((fnptr)* pfbegin, (fnptr)* pfend)
   at <CrtImplementationDetails>.LanguageSupport.InitializePerAppDomain(LanguageSupport* )
   at <CrtImplementationDetails>.LanguageSupport._Initialize(LanguageSupport* )
   at <CrtImplementationDetails>.LanguageSupport.Initialize(LanguageSupport* )
   --- End of inner exception stack trace ---
   at <CrtImplementationDetails>.ThrowModuleLoadException(String errorMessage, Exception innerException)
   at <CrtImplementationDetails>.LanguageSupport.Initialize(LanguageSupport* )
   at .cctor()
   --- End of inner exception stack trace ---
   at System.Windows.Application.ApplicationInit()
   at System.Windows.Application..cctor()
   --- End of inner exception stack trace ---
   at System.Windows.Application..ctor()
   at PackageExplorer.App..ctor() in D:\a\1\s\PackageExplorer\App.xaml.cs:line 25
   at PackageExplorer.App.Main()
```
- Are there any workarounds? no
- Is there a version in which it did work?
I get the same error in the zipped release of version 5.0.78.0. I do not get the error when running version 4.6.26.
- Is there a package on Nuget.org which shows the bug?
Bug is not related to a specific nuget package

**Comment by onovotny** [comment]
Is this from the Store or Chocolatey?

**Comment by ddechant** [comment]
Microsoft Store. I'm using Windows 10 Education (1809).

**Comment by onovotny** [comment]
Okay, interesting, will look into it.

**Comment by onovotny** [comment]
Digging, but can you try the chocolatey version?

**Comment by ddechant** [comment]
Chocolately version (5.0.78) results in the same error.

**Comment by onovotny** [comment]
Okay, thanks for the confirmation. That rules out vcredist-related issues.

**Comment by vatsan-madhavan** [comment]
I just tried this on a fresh installation of Win10 1809 x64 Education Edition, and both the Store version and the Chocolatey  one seems to launch without any problems for me. 

Would you mind getting a Time Travel trace of the crash with Loader snaps enabled for NugetPackageExplorer.exe (preferably, the non-Appx version)? 

You can install Windbg Preview from the [Store ](https://www.microsoft.com/store/apps/9pgjgd53tn86) which has [Time Travel](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/time-travel-debugging-overview) capture functionality. 

You'll need [gflags.exe ](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/gflags) to enable loader snaps - you'll find this option in the _Image File_ tab. Make sure you are using 32-bit version of gflags.exe when targeting a 32-bit process for debugging.  Alternatively, you can do this manually by creating the following registry keys and values:

-  `HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\nugetpackageexplorer.exe`
   - Set `REG_DWORD` value `GlobalFlag` to `0x2`. 
- `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\nugetpackageexplorer.exe`
  - Set `REG_DWORD` value `GlobalFlag` to `0x2`.

Remember to delete these registry keys after collecting the trace.

**Comment by ddechant** [comment]
I wasn't able to reproduce due to my antivirus being over-aggressive with Windbg. Fortunately, that is also what was causing my original issue. Once NugetPackageManager was whitelisted, the error was no longer presented.
