### ISSUE TITLE
Support publishing to servers that require authentication

### ISSUE THREAD

**Issue by andyseres** [NuGetPackageExplorer/NuGetPackageExplorer#58]
We have a package feed in VSTS that requires authentication. It would be nice if NPE would allow the usage of credentials (i.e., PAT)

**Comment by 304NotModified** [comment]
Hi,

What is the version you have running?

**Comment by andyseres** [comment]
3.11.0.0

**Comment by 304NotModified** [comment]
Indeed, we have at least support basic Auth

**Comment by timothyparez** [comment]
![image](https://cloud.githubusercontent.com/assets/2060470/14595646/7ed3283e-0573-11e6-9815-1ca87a7962fb.png)

This is what we get when trying to publish to a NuGet.Server hosted by IIS with basic authentication enabled (over HTTPS)

**Comment by 304NotModified** [comment]
Some info is also in https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/issues/92

**Comment by jackfoxy** [comment]
Adding my voice: this is a must have to be useful in my company. The Explorer can solve a lot of problems for us, would really like to be using.

**Comment by Vonnguru** [comment]
What is the status of this? This seems pretty basic...

**Comment by 304NotModified** [comment]
From the readme 

> Current development state / looking for developers

> Currently NPE isn't actively developed, but we do accept (not too large) pull requests (PR).

> If you like to help, please check the Github issues. If you like to contribute more structurally, we would be happy to add you to our team

**Comment by jackfoxy** [comment]
@304NotModified can you tag up-for-grabs? Might help.

**Comment by 304NotModified** [comment]
Good idea!

**Comment by jackfoxy** [comment]
tweeted https://twitter.com/foxyjackfox/status/867755529010991104
re-tweets encouraged

**Comment by 304NotModified** [comment]
FYI,

for future reference, if you like to help on this,  `PushPackage()` and `DeletePackageFromServer` in the `GalleryServer` class are a good place to start

**Comment by dsslayers** [comment]
For anyone who actually ends up looking into this, this is actually possible to do in version 3.6, so something was happened in 3.7 that broke this, and has never been fixed. If you run a local executable of 3.6 you can connect to a server that requires authentication.
