### ISSUE TITLE
Support Chocolatey packages (<PackageSourceUrl> etc.)

### ISSUE THREAD

**Issue by 304NotModified** [NuGetPackageExplorer/NuGetPackageExplorer#59]
See https://github.com/chocolatey/package-validator/wiki/PackageSourceUrlMissing

**Comment by 304NotModified** [comment]
> Additional information: The element 'metadata' in namespace 'http://schemas.microsoft.com/packaging/2011/08/nuspec.xsd' has invalid child element 'projectSourceUrl' in namespace 'http://schemas.microsoft.com/packaging/2011/08/nuspec.xsd'. List of possible elements expected: 'frameworkAssemblies, developmentDependency, dependencies, references, language' in namespace 'http://schemas.microsoft.com/packaging/2011/08/nuspec.xsd'.
You can repro by selecting https://chocolatey.org/api/v2 and trying vagrant.

**Comment by ferventcoder** [comment]
https://github.com/chocolatey/nuget-chocolatey/commit/9b703a89ffdffed488f04c4daa10eb961470e945 are the elements and the schema is https://github.com/chocolatey/nuget-chocolatey/commit/9b703a89ffdffed488f04c4daa10eb961470e945#diff-3ee333a10a43039639aea6ebf33818a3R49

**Comment by ferventcoder** [comment]
These are the elements added to the nuspec metadata:

- Project source url
- Package source url
- Docs url
- Wiki Url
- Mailing List Url
- Bug Tracker Url

Adding the following elements, reserving for future use with respect to
package relationships.
- Replaces
- Provides
- Conflicts

**Comment by ferventcoder** [comment]
As a heads up, we will be adding more https://github.com/chocolatey/choco/issues/325

**Comment by 304NotModified** [comment]
Wow that's a lot!

Too bad is Nuget itself really restrained with adding new elements.

**Comment by ferventcoder** [comment]
The NuGet authoring bits are hostile to any elements it doesn't recognize instead of just warning and allowing them.

**Comment by 304NotModified** [comment]
Note: current check is in:

![image](https://cloud.githubusercontent.com/assets/5808377/13412711/6493a240-df45-11e5-8460-632bbff820f2.png)

**Comment by 304NotModified** [comment]
@ferventcoder is there for choco a XSD / XML schema name?

NuGet uses mainly "http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd" schema (see examples https://docs.nuget.org/create/nuspec-reference)

**Comment by ferventcoder** [comment]
@304NotModified already provided. See https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/issues/59#issuecomment-188993392

**Comment by ferventcoder** [comment]
Short version is 

~~~cs
 internal const string SchemaVersionV7 = "http://schemas.microsoft.com/packaging/2015/06/nuspec.xsd";
~~~

**Comment by 304NotModified** [comment]
> @304NotModified already provided. See #59 (comment)

oops. 

Thanks again!

**Comment by flcdrg** [comment]
This causes NGPE to crash hard.

**Comment by dragon788** [comment]
It would probably be better to warn and not fail if it detects any elements that it doesn't understand. That provides a much better user experience, especially if they are trying to use NGPE to figure out WHAT is wrong with their package and comparing it to a known good package. Much easier than having the user rename to zip, extract, open text files and compare.

**Comment by 304NotModified** [comment]
> It would probably be better to warn and not fail if it detects any elements that it doesn't understand.

Agree, but currently it reads the content and if the schema won't match, you will loose info on save. I guess that's also not nice.

**Comment by dragon788** [comment]
Perhaps make it allow opening the package if it fails schema validation but put the package into a hard "read-only" state where they can make changes but are unable to actually save and modify the current package. This would allow them to "save as" if they were willing to lose that information, otherwise they could simply view whatever information was actually there if it doesn't get lost during the exception.

I see from your screenshot most of the logic is probably here, https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/3521f638384a6b418c4a045188ef3f860b046e25/Core/Authoring/Manifest.cs#L263 though from what I can tell there isn't a simple read of the XML to ensure validity, it is only use the xsd schemas to determine that so like you said, high change of losing data during the exception if it doesn't simply bypass further validation and open read-only with the raw data.

**Comment by onovotny** [comment]
This is likely to be virtually impossible in the current configuration as we use the NuGet libraries for serializing/deserializing nuspec files.

Does Chocolatey have a set of libraries that mirror NuGet.Packaging? It might be possible to sniff and use those if they exist, but we're not doing any raw XML parsing anymore.

**Comment by 304NotModified** [comment]
> This is likely to be virtually impossible in the current configuration as we use the NuGet libraries for serializing/deserializing nuspec files.

I propose to close this as wontfix, as for this reason.
