### ISSUE TITLE
No working Search for static feeds

### ISSUE THREAD

**Issue by tmat** [NuGetPackageExplorer/NuGetPackageExplorer#607]
Hi! Thanks for reporting this feature/bug/question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

**Type** (choose one):

- Bug

**NPE version**: (e.g. 5.x) (see Help -> about)

5.0.132+f33e9c233d

**OS version**: (Windows 7, 10 - 1803/17134, etc)

Windows 10

**Installed from**: Microsoft Store

***Repro**
Open feed https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json.

Enter `Arcade` into search box and hit enter.

After a while the package list refreshes but contains all packages, not just those that include "Arcade".

**Comment by tmat** [comment]
I see. Would it be possible to detect this case and do client side search?

**Comment by onovotny** [comment]
I'm a bit hesitant to replicate search logic that NuGet has; we don't really know what kind of feed it is. If this replicates on VS, can you file a bug on the NuGet issue tracker?

**Comment by vatsan-madhavan** [comment]
I've been hitting this same problem and I wish we could have a temporary client-side workaround until Nuget fixes it.

**Comment by AdamYoblick** [comment]
+1

search has never worked for us in the Nuget Package Explorer. :)

**Comment by vatsan-madhavan** [comment]
There is a related discussion here that could be of interest - https://github.com/emgarten/Sleet/issues/79

This doesn't work in Visual Studio either. 

Since it's possible to detect when a feed is a _static + sleet_ feed, I'm wondering if it would be possible to turn on client-side searching for those types of feeds. Not sure if this is the most maintainable approach for solving this problem...

**Comment by 304NotModified** [comment]
the performance is also bad with static feeds (duh, paging wont work).

@vatsan-madhavan what's a *sleet* feed? How should we detect is static? One thing is to do a search a see you get the same results, but that need at least 2 downloads

**Comment by 304NotModified** [comment]
> edit: or maybe if we get more then 15 feeds if we request 15... ;)

working on this

**Comment by 304NotModified** [comment]
For the search the ordering is also important.

Does anyone know a good algorithm? 

I think we should at least search on these fields: Title, Description, Tags.

(Maybe also the summary?)

A first simple approach could be:

full match title: 50, 
found in title: 20, found in description: 10, found in tags: 5. Summarize and order.

**Comment by vatsan-madhavan** [comment]
@304NotModified - see https://github.com/emgarten/Sleet/

**Comment by 304NotModified** [comment]
FYI, I have the basics working. Need some refactoring and details for the search & ordering. Will try to finalize it upcoming week.

**Comment by onovotny** [comment]
Awesome. I'll get a new release out now and update with this when you have it.

**Comment by loic-sharma** [comment]
@304NotModified Hey, I'm a developer from the team that runs nuget.org. We're currently working on  improving our search on top of Azure Search. Here's an info dump on how we rank results currently using Azure Search. Note that this stuff may change drastically as we continue to iterate :)

**Index Definition**
The `PackageId` field contains the name of a package, like "Newtonsoft.Json". This field has a weight of 2 and is used to boost package results whose "id" exactly match the search query.

The `TokenizedPackageId` field also contains the name of a package. We split this field's tokens on non-alphanumeric characters and case changes to support finer grain matches. This field has a weight of 5.

The `DownloadScore` field is derived from a package's download count:

```
DownloadScore = sqrt(package's download count) / 220
```

For example, the package "Newtonsoft.Json" has 255 million downloads, resulting in a `DownloadScore` of ~72.6. Download scores range from [0-100) as the most downloaded package has less than 500 million downloads.

This field is used in a magnitude scoring function with linear interpolation and a boost of 3000. This scoring function increases quickly at first, and then becomes approximately linear near the upper bound of download counts. In other words, packages get a strong boost from additional downloads, but this effect tapers. We may revisit this scoring function to include favor recent downloads.

**Azure Search query generation**
We've improved our results by favoring results that match all terms in the inputted query. Given the following input query:

> entity framework

We will generate the following Azure Search query using Lucene query syntax:

> entity framework (+entity +framework)^3

**References**
* Search index document definition: https://github.com/NuGet/NuGet.Services.Metadata/blob/master/src/NuGet.Services.AzureSearch/Models/SearchDocument.cs#L20
* Analyzer for `PackageId` field: https://github.com/NuGet/NuGet.Services.Metadata/blob/master/src/NuGet.Services.AzureSearch/Analysis/ExactMatchCustomAnalyzer.cs
* Analyzer for `TokenizedPackageId` field: https://github.com/NuGet/NuGet.Services.Metadata/blob/master/src/NuGet.Services.AzureSearch/Analysis/PackageIdCustomAnalyzer.cs
* Download score definition: https://github.com/NuGet/NuGet.Services.Metadata/blob/master/src/NuGet.Services.AzureSearch/DocumentUtilities.cs#L37
* Scoring profile: https://github.com/NuGet/NuGet.Services.Metadata/blob/master/src/NuGet.Services.AzureSearch/ScoringProfiles/DefaultScoringProfile.cs#L69
* Query building: https://github.com/NuGet/NuGet.Services.Metadata/blob/master/src/NuGet.Services.AzureSearch/SearchService/SearchTextBuilder.cs

**Comment by onovotny** [comment]
@loic-sharma thanks for the details!

Are there any plans to do any of this client-side in the NuGet libraries to make static feeds searchable in Visual Studio?

**Comment by loic-sharma** [comment]
The client team is considering a `dotnet search` command that needs a similar feature (you have to rank results from multiple feeds). I’m not sure when/how they’ll tackle this.

**Comment by onovotny** [comment]
@loic-sharma is there an issue to follow for that?

**Comment by loic-sharma** [comment]
I can’t seem to find an issue tracking this... we had an early design meeting on this. I’ll ask the client team on Monday.

**Comment by 304NotModified** [comment]
@loic-sharma  really thanks for sharing in detail!
Do I understand it correctly that the search isn't searching in the summary/description? Or do I missed something?

**Comment by loic-sharma** [comment]
These fields are searchable (see [this](https://github.com/NuGet/NuGet.Services.Metadata/blob/eff7f7a75fb9210fe271ee1729480f06d0139d9a/src/NuGet.Services.AzureSearch/Models/BaseMetadataDocument.cs#L23) and [this](https://github.com/NuGet/NuGet.Services.Metadata/blob/eff7f7a75fb9210fe271ee1729480f06d0139d9a/src/NuGet.Services.AzureSearch/Models/BaseMetadataDocument.cs#L68)), but they are unweighted.

**Comment by 304NotModified** [comment]
unweighted means weight=1, isn't? So summary and description has the same weight?

I also think longer search term match should weight more, eg.

```
ab -> weight 1
abcdef -> weight 3
```

**Comment by loic-sharma** [comment]
> unweighted means weight=1, isn't? So summary and description has the same weight?

Yup, that's correct.

> I also think longer search term match should weight more, eg.

Term length is likely an interesting factor. Generally, search rankings score off term frequency (if `ab` is a common term it produces a lower score than a less common term like `abcdef`). For example: `core` is common in package names, but `mvc` is not. Term length would give you the opposite effect here.

**Comment by 304NotModified** [comment]
FYI,  I'm delayed on building this as I am unfortunately ill :(
