### ISSUE TITLE
Package information text can't be selected

### ISSUE THREAD

**Issue by tmat** [NuGetPackageExplorer/NuGetPackageExplorer#608]
Hi! Thanks for reporting this feature/bug/question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

**Type** (choose one):

- Bug

**NPE version**: (e.g. 5.x) (see Help -> about)

5.0.132+f33e9c233d

**OS version**: (Windows 7, 10 - 1803/17134, etc)

Windows 10

**Installed from**: Microsoft Store

The text displayed in package view can't be selected (for copy & paste).
![image](https://user-images.githubusercontent.com/41759/50714306-0bdb3980-102d-11e9-99ed-f9ff6e0a7654.png)

**Comment by onovotny** [comment]
What information would you want to copy/paste from this dialog?

**Comment by tmat** [comment]
The version for example.
