### ISSUE TITLE
Add to up-for-grabs.net

### ISSUE THREAD

**Issue by 304NotModified** [NuGetPackageExplorer/NuGetPackageExplorer#61]
Add to http://up-for-grabs.net/

How: https://github.com/up-for-grabs/up-for-grabs.net#add-your-project

**Comment by alexmajor** [comment]
Closed once up-for-grabs/up-for-grabs.net/pull/493 is merged.

**Comment by bigwave** [comment]
up-for-grabs/up-for-grabs.net#493 has been merged so this issue can be closed.

**Comment by 304NotModified** [comment]
Thx!
