### ISSUE TITLE
Authors meta shouldn't be a prerequisite to opening .snupkg

### ISSUE THREAD

**Issue by daniel-v** [NuGetPackageExplorer/NuGetPackageExplorer#611]
**Type** (choose one):

- Bug

**NPE version**: 

NuGet Package Explorer - Store - (5.0.132+f33e9c233d)

**OS version**:
Win 10

**Installed from**: 
Microsoft Store

- What is the current result?

Can't open `.snupkg` because of an error displaying that authors is required.

- What is the expected result?

`.snupkg` files can also be opened with missing authors meta.

**Reasoning**:
As per MSDN page https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg 

```
authors and owners field will be excluded from the snupkg's nuspec.
```
Therefore I think it is not a valid expectation from `.snupkg` packages to contain authors meta.

**Comment by onovotny** [comment]
Do you have a sample snupkg? This sounds like a bug in the NuGet library API's that they can't open their own nuspec. (wouldn't be the first time).
