### ISSUE TITLE
Signing and then Publishing requires Restart

### ISSUE THREAD

**Issue by RickStrahl** [NuGetPackageExplorer/NuGetPackageExplorer#624]
**Type** (choose one):

- Bug

**NPE version**: (e.g. 5.x) (see Help -> about)
5.0.132

**OS version**: (Windows 7, 10 - 1803/17134, etc)

**Installed from**: Microsoft Store / Chocolatey.org / Zip on GitHub / CI channel
Microsoft Store

In case of a BUG:

There appears to be a problem with both signing and publishing from the same instance of the app.

Steps:

* Open from Nuspec file
* Sign and Save
* Pick Certificate and Save
* Signature now shows up in the viewer and file shows as .nupkg
* Now try and publish

Error: Trusted certificate is required to publish this package

> Note I have a certificate registered on NuGet and I can publish (see below)

To fix, exit Package Explorer and re-open the `.nupgkg` file. Now publish succeeds.

Not  a big deal since the workaround works, but this should probably work in one operation.

**Comment by onovotny** [comment]
@campersau care to take a stab at this one?
