### ISSUE TITLE
Unable to view nuget.org feed behind corporate firewall

### ISSUE THREAD

**Issue by WattsC-90** [NuGetPackageExplorer/NuGetPackageExplorer#625]
**Type** (choose one):
    Bug

**NPE version**: 5.0.132+f33e9c233d

**OS version**: Win10 - 1803 (OS Build 17134.523)

**Installed from**: Microsoft Store

In case of a BUG:
![image](https://user-images.githubusercontent.com/10712792/52061428-2ccc7700-2566-11e9-9a29-c5ae0f2025c5.png)

- What is the current result?
   Attempting to view main nuget.org feed results in message in picture.
   If i manually navigate in chrome, it loads no problem.

- What is the expected result?
   shows the packages!

- Please post full exception details in case of an Exception (message, stacktrace, inner exceptions).
   n/a

- Are there any workarounds? no

- Is there a version in which it did work?
   It used to work, but now we operate a different proxy (zscaler - cloud based with a pac file). so think it may be more complicated, but cannot set any proxy at all

- Is there a package on Nuget.org which shows the bug?
   n/a

**Comment by 304NotModified** [comment]
What's the next step here? Create a proxy config in NPE? Or read proxy settings from e.g. IE? Or something else?

**Comment by onovotny** [comment]
TBH, I'm not sure.

@rrelyea, what do we need to do for NuGet to support proxies? How does NuGet.exe/dotnet nuget do it?

**Comment by rrelyea** [comment]
I imagine the user should go through the steps in this faq:
https://docs.microsoft.com/en-us/nuget/nuget-org/nuget-org-faq#nugetorg-not-accessible

**Comment by onovotny** [comment]
So the NuGet libraries will automatically pick up the users proxy? Wasn’t sure if the apps that used the libraries had to do anything in particular?

**Comment by campersau** [comment]
Looks like the [`ProxyCache`](https://github.com/NuGet/NuGet.Client/blob/ef9eb47e886cd5abe7e5d3160cc48312274b1c06/src/NuGet.Core/NuGet.Configuration/Proxy/ProxyCache.cs) tries to read the system proxy on `!IS_CORECLR`. What build are we using?

https://github.com/NuGet/NuGet.Client/blob/ef9eb47e886cd5abe7e5d3160cc48312274b1c06/src/NuGet.Core/NuGet.Configuration/Proxy/ProxyCache.cs#L60-L68

The other places for proxysettings are nuget settings and environment variables: https://github.com/NuGet/NuGet.Client/blob/ef9eb47e886cd5abe7e5d3160cc48312274b1c06/src/NuGet.Core/NuGet.Configuration/Proxy/ProxyCache.cs#L80-L138

**Comment by onovotny** [comment]
We are using a custom build of the CoreCLR version, due to the crypto. Looks like I’ll need another patch to it for this, assuming the APIs are available on Core 3. Also seems like something NuGet would need to handle more generally anyway?

**Comment by onovotny** [comment]
Looks like it should be automatic in CoreCLR. If the issue is credentials, the handler may not be using the default credentials: 

https://github.com/dotnet/corefx/issues/7037#issuecomment-449979122

The `HttpHandlerResourceV3Provider` sets a proxy but isn't setting DefaultProxyCredentials.

https://github.com/NuGet/NuGet.Client/blob/3803820961f4d61c06d07b179dab1d0439ec0d91/src/NuGet.Core/NuGet.Protocol/HttpSource/HttpHandlerResourceV3Provider.cs#L46
