### ISSUE TITLE
Can't unpublish package

### ISSUE THREAD

**Issue by wjk** [NuGetPackageExplorer/NuGetPackageExplorer#659]
**Type** (choose one): Bug  
**NPE version**: 5.0.182+b1cf95a480  
**OS version**:17763.316  
**Installed from**: Microsoft Store

As the title says, when I try to publish and delist a package (I was trying to delist my obsolete `Sunburst.NET.Sdk.WindowsForms` package), I get a weird error message. First of all, I see this when I try to open the Publish dialog:

![unpublish error 1](https://user-images.githubusercontent.com/1915951/53276438-f8fbf180-36cc-11e9-9c4a-ff1db14e78de.jpg)

I click OK on that, enter my PAT and check the delisting box, then I get this when I click Publish:

![unpublish error 2](https://user-images.githubusercontent.com/1915951/53276448-087b3a80-36cd-11e9-99f7-cd4aadeda27f.jpg)

As far as I know, there are no usable workarounds. This is actually the first time I've ever published a package using NGPE (I usually use it to download and view package contents), so I can't say if it worked on an earlier version or not. (Presumably, it would, though!) No proxy is used or required. Thanks for looking into this!

**Comment by campersau** [comment]
This is already fixed. But I guess not released yet.
See #650 and #651

**Comment by onovotny** [comment]
I’ll get this out shortly. The CI channel should have it though.

**Comment by onovotny** [comment]
5.0.198 is rolling out with this fix in it.
