### ISSUE TITLE
Consider using NuGet client libraries wherever possible

### ISSUE THREAD

**Issue by onovotny** [NuGetPackageExplorer/NuGetPackageExplorer#66]
The complexity of NuGet package parsing is exploding. It might be worthwhile using the NuGet client libraries directly instead of trying to maintain the TFM's and parsing logic.

**Comment by 304NotModified** [comment]
Agreed! 

This has been discussed already :https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/issues/54

**Comment by GrimaceOfDespair** [comment]
+1: It would also enable the new package layout:

[![image](https://cloud.githubusercontent.com/assets/228782/18863796/84dada3e-8493-11e6-9413-b3026f5a80a2.png)][1]

 [1]: https://docs.nuget.org/ndocs/tools/nuget.exe-cli-reference

**Comment by 304NotModified** [comment]
Fixed by https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/pull/147
