### ISSUE TITLE
"Date Modified" flag updated on FILE -> EXPORT feature

### ISSUE THREAD

**Issue by Karuskrokro** [NuGetPackageExplorer/NuGetPackageExplorer#663]
**Type** 

- Bug
- Question

**NPE version**: 3.21.0.0 **UPDATE** : same result on (5.0.198+0d56f54642)

**OS version**: Windows 7

**Installed from**: Microsoft Store (manifest)

- What is the current result?
I have a nupkg containing dll's and an exe. Let's say these dll's were created at 12:00
FILE -> EXPORT is updating "Date modified" of all dll's and .exe : if i export this nupkg at 14:00, all the dll's and exe in the package will have "Date modified" updated to 14:00, which is wrong !
If i use classic 7zip to extract the nupkg, regardless of the date, it will have his original "Date modified" at 12:00 

- What is the expected result?
Original "Date Modified" on EXPORT feature, this date has to remains the original compilation date to be able to track dll's changes (builds, ect..)

- Are there any workarounds?
The use of 7zip is ok to keep the Original date.

- Is there a version in which it did work?
I've always used 3.21.0

**Comment by 304NotModified** [comment]
Fixes here -> #742
