### ISSUE TITLE
Open from online feed not working anymore

### ISSUE THREAD

**Issue by fubar-coder** [NuGetPackageExplorer/NuGetPackageExplorer#692]
**Type**: Bug

**NPE version**: 5.0.230+25a5761361

**OS version**: Windows 10 1903

**Installed from**: Microsoft Store

I cannot load packages from online feeds. 

When I use `https://api.nuget.org/v3/index.json`, I get the error message `Unable to load the service index for source https://api.nuget.org/v3/index.json`.

The same problem exists when I try to use one of the following URLs:

- `https://www.nuget.org/api/v2`
- `https://www.nuget.org/api/v2/Packages`

**Comment by campersau** [comment]
For me it is working fine with this version. Can you open [https://api.nuget.org/v3/index.json](https://api.nuget.org/v3/index.json) in the browser? Have you configured a proxy?
Maybe these help: https://stackoverflow.com/questions/41185443/nuget-connection-attempt-failed-unable-to-load-the-service-index-for-source, https://stackoverflow.com/questions/52977703/nuget-package-manager-unable-to-load-the-service-index

**Comment by fubar-coder** [comment]
Ugh ... so it might be a problem with our AV solution? Will close this issue then.
