### ISSUE TITLE
Smartscreen notification in 3.12

### ISSUE THREAD

**Issue by 304NotModified** [NuGetPackageExplorer/NuGetPackageExplorer#70]

**Comment by DominicJ2** [comment]
After updating from 3.11 to 3.12 Windows is now telling me to not run the application.  Downgraded back to 3.11 and am having no issues
![capture](https://cloud.githubusercontent.com/assets/17558055/13413788/29ebfdf6-df02-11e5-95ef-ba85e5233b6e.PNG)

**Comment by 304NotModified** [comment]
Hi,

this is niet chocolaty  and this is the smartscreen error as stated in the notes:

![image](https://cloud.githubusercontent.com/assets/5808377/13426823/5b084f26-dfb0-11e5-9c47-fb0a893f4476.png)

We cannot prevent this without paying a lot for a coding certificate :(

**Comment by 304NotModified** [comment]
@dsplaisted Can't you get a code certificate bargain ;) 

Maybe we could add a funding badge for buying a code certificate?

**Comment by 304NotModified** [comment]
https://gripdev.wordpress.com/2015/04/08/appveyor-github-and-chocolatey-automatically-build-your-project-and-publish-updates-it-to-chocolatey/

**Comment by 304NotModified** [comment]
Superseded by https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/issues/46
