### ISSUE TITLE
Save File - Replace existing file dialog contains literal \r\n

### ISSUE THREAD

**Issue by rjvdboon** [NuGetPackageExplorer/NuGetPackageExplorer#705]
**Type**
- Bug

**NPE version**: (e.g. 5.x) (see Help -> about)
5.2.15

**OS version**: (Windows 7, 10 - 1803/17134, etc)
Windows 7

**Installed from**: Microsoft Store / Chocolatey.org / Zip on GitHub / CI channel
Chocolatey.org

- What is the current result?
There is the text `\r\n` in the replace existing file message box.
![image](https://user-images.githubusercontent.com/1241158/58001774-bf286480-7adc-11e9-909b-00a4fed85e4e.png)

- What is the expected result?
A newline.

- Please post full exception details in case of an Exception (message, stacktrace, inner exceptions).
n/a
- Are there any workarounds? yes, ignore the typo.
- Is there a version in which it did work? Don't know.
- Is there a package on Nuget.org which shows the bug? n/a

**Comment by mjjames** [comment]
For reference this also happens in Windows 10

**Comment by mjjames** [comment]
the error is actually in the Microsoft.Win32.SaveFileDialog code, not NugetPackageExplorer.[ Within the WPF Core source](https://github.com/dotnet/wpf/blob/ae1790531c3b993b56eba8b1f0dd395a3ed7de75/src/Microsoft.DotNet.Wpf/src/PresentationFramework/Microsoft/Win32/SaveFileDialog.cs#L488) it looks like its just calling out to a resource file which contains the \r\n. For reference it appears all of the resources which contain \r\n (for example when you try to add a file that doesn't exist) have the same issue. As this is an issue in .Net Core WPF should this issue just be closed?

**Comment by onovotny** [comment]
Can you file an issue on the WPF repo and link it here?

**Comment by mjjames** [comment]
doing it now :)

**Comment by mjjames** [comment]
For reference new case opened within the WPF repo https://github.com/dotnet/wpf/issues/977

**Comment by mjjames** [comment]
For reference I believe I found the issue and submitted a PR for dotnet/wpf#977 https://github.com/dotnet/wpf/pull/978

**Comment by weltkante** [comment]
I think this analysis/fix is wrong, \r\n is an escape sequence, if \n would work then you'd see a literal \r followed by a line break. If there is specific code to not translate \r\n escape sequences but translate \n escape sequences then this code needs to be fixed and not the resources.

**Comment by onovotny** [comment]
Closing as this is fixed in WPF in .NET Core. If not in Preview 7, I imagine it'll be in Preview 8, which we'll pick up eventually.
