### ISSUE TITLE
The option for .Net Core does not exist in 16.1.1 Visual Studio 2019

### ISSUE THREAD

**Issue by DataJuggler** [NuGetPackageExplorer/NuGetPackageExplorer#707]
I have Dot Net Core installed, but no where is there an option that says enable SDK Previews.

I have Tools > Options > Projec and Solutions > ..NET Core, and the only option is do not call MS Build for up to date projects.

Is there an older version of this tool that uses the .Net Framework, and only the .Dot Net Framework, and stable SDK's so I don't have to do whatever cryptographic instructions you are describing.

**Comment by onovotny** [comment]
I’m not sure I understand the issue? Install from the store (best option), chocolatey, or use the zip from the releases tab. There’s nothing else to install, the application is entirely self-contained.

**Comment by DataJuggler** [comment]
When I open up Visual Studio I get a message ‘Please Enable Dot Net Core SDK Previews’.

I figured it out with a  command line, sorry to bother you.

**Comment by onovotny** [comment]
This tool has nothing to do with Visual Studio, sorry.

**Comment by onovotny** [comment]
This tool has nothing to do with Visual Studio, sorry.

**Comment by DataJuggler** [comment]
Well the solution file is a .sln file so I bet to differ.

When I open the downloaded zip file, I get a NugetPackageExplorer.sln, and when I click on that 5 projects open in Visual Studio, and then I get
This error:

I didn’t know there was a file in the store, when you search google for Nuget Package Explorer Git Hub came up.

But I don’t understand your nothing to do with Visual Studio comment. But since you asked I sent you the message, and it does have to do with Visual Studio.

[A screenshot of a cell phone  Description automatically generated]

**Comment by onovotny** [comment]
You don’t need to clone/build this app to use it. Pre-built binaries are available from the locations mentioned above.

**Comment by DataJuggler** [comment]
Thank you, sorry I didn’t know.
