### ISSUE TITLE
Working on Windows 10 Enterprise

### ISSUE THREAD

**Issue by nische** [NuGetPackageExplorer/NuGetPackageExplorer#717]
Hi,
is it possible to use the NuGetPackageExplorer on Windows 10 Enterprise?
On my Maschine the Programm Crashs/Dont Start without an error. 
(Installed from Windows Store)

Best regards, 
Nico

**Comment by campersau** [comment]
Can you please try out the new version 5.2.49?
https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/issues/716#issuecomment-500812335

**Comment by nische** [comment]
Thanks for your reply.
I installed the 5.2.49 Version with Chocolatey and now it work perfect. 
Maybe the Windows Store has an older Version.
