### ISSUE TITLE
application unexpectedly close

### ISSUE THREAD

**Issue by inouefumina** [NuGetPackageExplorer/NuGetPackageExplorer#718]
Hi, from Tokyo.

the problem is that i downloaded one online package and succeeded but i cannot open that package through Nuget package Explorer.
When i click the line of that certain package in the file of my PC, only one second the application open but in the next second it automatically close.

At the end i want to use that package inside Uipath, and i used Nuget package explorer just for downloading the package in the Nuget form.

please tell me how i can solve this problem.

thank you.

**Comment by campersau** [comment]
possibly duplicate of #716

**Comment by campersau** [comment]
Can you please try out the new version 5.2.49?
https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/issues/716#issuecomment-500812335

**Comment by onovotny** [comment]
Closing as a dup. Please re-open if it happens with 5.2.49
