### ISSUE TITLE
Feature Request: Provide Shared IntelliCode Model for Contributors to use

### ISSUE THREAD

**Issue by mjjames** [NuGetPackageExplorer/NuGetPackageExplorer#721]
Feature Request: Provide Shared IntelliCode Model for Contributors to use
**NPE version**: N/A

**OS version**: N/A

**Installed from**:  N/A

This will help contributors follow the existing conventions and common use cases of methods and classes etc.

**Comment by onovotny** [comment]
`.editorconfig` should take care of most code style settings, but here's an IntelliCode model https://prod.intellicode.vsengsaas.visualstudio.com/get?m=B971F4617299420C8D5CFEF23F395D2A
