### ISSUE TITLE
Determine File Association 

### ISSUE THREAD

**Issue by jsimmonstx** [NuGetPackageExplorer/NuGetPackageExplorer#806]
NPE version: 5.2.88
OS version: Win7 (in a VirftualBox VM, on a Linux host)
Installed from: file download

Feature Request:
Since the app doesn't need "installation" to run, when the app starts, have it check to see if nuspec files are associated with the app. If they're not, have the app prompt the user to see if he wants to associate those file types with the app. In the dialog box that asks this, included a checkbox that says "Don't show this again if I click the NO button".

Why do we need it?
Because this is 2019, and development is supposed to be easier.

Please provide an use case:
I want the app to open the .nuspec file I double-click because it's faster that way.

**Comment by 304NotModified** [comment]
> OS version: Win7
> Why do we need it? Because this is 2019

;)

**Comment by onovotny** [comment]
Please use the Store version or the Chocolatey version. It registers the file types. The version from the Store is the best as it auto-updates. 

On Win7, Chocolatey will register the correct file types.

The standalone zip version isn't intended for wide use. Closing as won't fix for that.
