### ISSUE TITLE
Why don't we just startup from a vs project file *.csproj

### ISSUE THREAD

**Issue by xiong-ang** [NuGetPackageExplorer/NuGetPackageExplorer#808]
**Type** (choose one):
- Feature request

**NPE version**: (e.g. 5.x) latest

**OS version**: all

**Installed from**: Microsoft Store 

In case of a FEATURE REQUEST:
Since we could use nuget.exe create *.nupkg file, so why don't we startup our workflow from a .net project file.

**Comment by onovotny** [comment]
Hi,

Can you please clarify what you'd like to see? I'm not sure I understand.

**Comment by jsimmonstx** [comment]
I think he wants to be able to open a visual studio project, and open PackageExplorer within the context of the currently open project. Maybe he wants a nupkg project type.

**Comment by xiong-ang** [comment]
So sorry for my confusing expression.
Currently we provide the function to create a nuget package based on a nupkg project.
So I wonder if we could create the nuget package based on a visula studio project.

**Comment by xiong-ang** [comment]
Just a perspective of a nuget beginner
Wish you could understand.

**Comment by onovotny** [comment]
If you're using one of the newer SDK-style projects, that's already supported with either `msbuild /t:pack` or `dotnet pack`.

https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package-msbuild

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, please let us know!
