### ISSUE TITLE
Support Icons within the package

### ISSUE THREAD

**Issue by onovotny** [NuGetPackageExplorer/NuGetPackageExplorer#820]
NuGet is moving to include icons within the package. We need to support that:

Spec: https://github.com/NuGet/Home/wiki/Packaging-Icon-within-the-nupkg

We should also have a validation rule for ensuring the icon is actually within the package (error on save?) as that would fail push anyway.

**Comment by onovotny** [comment]
FakeItEasy 5.4.0 supports this. Looks like the feed metadata turns the url into a chached public link, so nothing to do for that view:
![image](https://user-images.githubusercontent.com/1427284/68531712-4a8fef00-02e3-11ea-994e-2ad3908a56d9.png)

We need to determine the best way to display it in the package view, indexing into the package stream so we don't need to extract it.

**Comment by campersau** [comment]
I'm currently working on it. Indexing works fine also for manual package creation:  https://github.com/campersau/NuGetPackageExplorer/blob/081eaadc5f8fe55b5264de014ac2f17463e663b1/PackageExplorer/Converters/PackageIconConverter.cs
