### ISSUE TITLE
Add support for PackageIcon

### ISSUE THREAD

**Issue by dotnetjunkie** [NuGetPackageExplorer/NuGetPackageExplorer#833]
**Type** Feature request
**NPE version**: 5.3

The use of `PackageIconUrl` has been [deprecated](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu5048) and `PackageIcon` is now [adviced](https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#packing-an-icon-image-file).

The NuGet Package Explorer, however, does not support adding a `PackageIcon`, and does not show the icon of packages that use the `PackageIcon`.

**Comment by onovotny** [comment]
Dup of #820
