### ISSUE TITLE
Double click on a nupkg with spaces in the path won't work correctly 

### ISSUE THREAD

**Issue by lbelloq** [NuGetPackageExplorer/NuGetPackageExplorer#835]
Hi! Thanks for reporting this feature/bug/question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

**Type** (choose one):

- Bug

**NPE version**: 5.2.49+290c8f97cd

**OS version**: Windows 7 Professional x64

**Installed from**: Chocolatey.org

In case of a BUG:

- **What is the current result?** Double-clicking a package in Windows Explorer opens NPE but the package is not open inside NPE
- **What is the expected result?** NPE opens and the selected package opens automatically inside it.
- **Please post full exception details in case of an Exception (message, stacktrace, inner exceptions).** No exceptions shown.
- **Are there any workarounds? yes** -> Opening NPE and manually selecting File -> Open...
- **Is there a version in which it did work?** Not AFAIK
- **Is there a package on Nuget.org which shows the bug?** No, behavior present in all cases.

**Comment by 304NotModified** [comment]
Do you double click on a nupkg? Or a nuspec?

**Comment by lbelloq** [comment]
In a .nupkg file.

**Comment by onovotny** [comment]
Are there spaces in the path to the package? Does it work if there aren't?

Might be a quoting issue https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/master/PackageExplorer/ChocolateyInstall.ps1#L14

**Comment by lbelloq** [comment]
Copying the package to a folder without spaces solves the problem.

**Comment by 304NotModified** [comment]
Thanks for the confirmation!

**Comment by 304NotModified** [comment]
This should be fixed in v5.4.1, thanks @onovotny !
