### ISSUE TITLE
Support for displaying deprecated packages

### ISSUE THREAD

**Issue by onovotny** [NuGetPackageExplorer/NuGetPackageExplorer#838]
NuGet's metadata can display package deprecation information. We should display it in a similar way in the Package Explorer UX

https://devblogs.microsoft.com/nuget/deprecating-packages-on-nuget-org/

![image](https://user-images.githubusercontent.com/1427284/65925127-8a4ae900-e3bd-11e9-9238-7bcb2d5df299.png)

**Comment by loic-sharma** [comment]
You should be able to use the package metadata resource (aka "registration) to grab a package's deprecation information: https://docs.microsoft.com/en-us/nuget/api/registration-base-url-resource#package-deprecation

**Comment by campersau** [comment]
For me visual studio does not show deprecated versions in the list view. Only in the package version details:
![image](https://user-images.githubusercontent.com/4009570/68527872-487e5e00-02ec-11ea-90a4-08519028123e.png)

Is that correct? Was it removed or will it be available in the future?
