### ISSUE TITLE
Azure Devlops Artifacts

### ISSUE THREAD

**Issue by generik0** [NuGetPackageExplorer/NuGetPackageExplorer#839]
Hi! Thanks for reporting this feature/bug/question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

Question

5.4.1
Win 10 x64
Chocolatey.org

I am having trouble using azure devops artifacts with the tool. I..e even thought the nuget source was added with a PAT, (and it is also in the credential manager) the package manager cannot connect to the internal azure devops artifacts.

Should it be able to connect with security?

**Comment by Stoolbend** [comment]
I'm also getting the same issue with version:

*NuGet Package Explorer - Store - X64 - (5.4.1+e95bd234fd)*

When trying to either open a package from the feed, or publish to the feed, I get a constant prompt for username & password. No combination of username & PAT, PAT & PAT or actual credentials works unfortunately.

**Comment by campersau** [comment]
For me this is working with NuGet Package Explorer - Store - X64 - (5.4.1+e95bd234fd).

1. Click on Profile -> Security (https://dev.azure.com/USERNAME/_usersSettings/tokens)
![image](https://user-images.githubusercontent.com/4009570/66873716-6c7aa800-efa9-11e9-84db-f8075daf96e7.png)

2. Create a new Personal Access Token
3. Use either Full Access or Custom Scopes
3.1 When using Custom Scopes click on Show all Scopes and select the ones under Packaging
![image](https://user-images.githubusercontent.com/4009570/66873796-aba8f900-efa9-11e9-8c82-21a1b7e9af77.png)

4. Click save and copy the Personal Access Token
5. Connect to the feed in NuGet Package Explorer (https://pkgs.dev.azure.com/USERNAME/_packaging/USERNAME/nuget/v3/index.json)
6. In the credential popup paste the Personal Access Token in the username field and click Login
![image](https://user-images.githubusercontent.com/4009570/66874592-e9a71c80-efab-11e9-847c-3790ab7d64ee.png)

You can also try out this build: https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/issues/840#issuecomment-538231467

**Comment by Stoolbend** [comment]
Looks like my PAT didn't have the relevant permissions 🤦‍♂️.
It would be great to have the ability to save the PAT so it doesn't prompt on each restart.

**Comment by clairernovotny** [comment]
Closing due to age.
