### ISSUE TITLE
3.14: ClickOnce error: Humanizer.resources must be installed in GAC

### ISSUE THREAD

**Issue by 304NotModified** [NuGetPackageExplorer/NuGetPackageExplorer#84]
Clickonce won't work again:

![image](https://cloud.githubusercontent.com/assets/5808377/14507583/907468f4-01c3-11e6-8611-37c92ad595aa.png)

**Comment by onovotny** [comment]
Huh? Late to this thread, but how does having satellite assemblies cause ClickOnce to fail?

**Comment by MatthewSteeples** [comment]
@onovotny In this instance it was because the satellite assemblies hadn't been packaged up in the ClickOnce installer. This meant that they weren't there to be downloaded, leading ClickOnce to think it was meant to look in the GAC for them. It's a bit of a backwards error message really.

**Comment by onovotny** [comment]
There are really two options here then:

1. Use the Humanizer.Core package if all you want is English. That one excludes all of the satellite assemblies
2. Package up the satellite assemblies in the ClickOnce

Just wanted to make sure that there wasn't/isn't a bug in Humanizer here!

**Comment by 304NotModified** [comment]
hey @MatthewSteeples  and @onovotny,

I tried packaging the satellite assemblies into ClickOnce, but failed. But don't think we need to fix it, as NPE is English only already and all those languages makes the installation package a lot larger.
