### ISSUE TITLE
Revert #841 when https://github.com/NuGet/Home/issues/8661 is fixed

### ISSUE THREAD

**Issue by campersau** [NuGetPackageExplorer/NuGetPackageExplorer#842]
Revert #841 when https://github.com/NuGet/Home/issues/8661 is fixed.

**Comment by campersau** [comment]
PR got merged (again) https://github.com/NuGet/Home/issues/8661

**Comment by clairernovotny** [comment]
Will get this in next time I pull & build the latest NuGet dev
