### ISSUE TITLE
Check that the targets file have the same name as package id for native NuGet packages

### ISSUE THREAD

**Issue by Konard** [NuGetPackageExplorer/NuGetPackageExplorer#845]
**Type**: Bug or Feature request

**NPE version**: NuGet Package Explorer - Store - X64 - (5.4.1+e95bd234fd)

**OS version**: Windows 10 Pro (10.0.18362)

**Installed from**: Microsoft Store

I`m not sure if this is a bug or feature request.

I was publishing native NuGet package: https://www.nuget.org/packages/Platform.Collections.Methods.TemplateLibrary

And I have set a name for `targets` file in the `build\native` directory to `PlatformCollectionsMethods` and `Platform.Collections.Methods` but not `Platform.Collections.Methods.TemplateLibrary`.
This caused the issue of not including the path to library's header files in the vcxproj, where the package was included.

Before publishing of each version I have used `Analyze Package` menu item and got result of `0 issues found.`

So to save time from future mistakes, I suggest to include the check that ensures that `targets` file in `build\native` directory has has the same name as the package id in the `nuspec` file.

That will ensure that `targets` file will be successfully included into `vcxproj` when the package is used.

I had the problem in the versions 0.0.1-0.0.2 of [Platform.Collections.Methods.TemplateLibrary](https://www.nuget.org/packages/Platform.Collections.Methods.TemplateLibrary) and I fixed it in the 0.0.3 version.

**Comment by Konard** [comment]
@onovotny @aerotog thank you!

**Comment by onovotny** [comment]
@Konard not completely sure when the next version will be pushed to choco/store, but you can use the CI feed version for now. It'll auto update.
