### ISSUE TITLE
Icons are blurry on Package Chooser 

### ISSUE THREAD

**Issue by clairernovotny** [NuGetPackageExplorer/NuGetPackageExplorer#862]
In the package chooser dialog, the icons look blurry.

Maybe there's something we can do with the decoding/scaling? These are all from `IconUrlToImageCacheConverter`

![image](https://user-images.githubusercontent.com/1427284/68535550-010ac880-0312-11ea-90db-38ce583ddadb.png)

**Comment by grantfar** [comment]
I will take this

**Comment by grantfar** [comment]
pull request made

**Comment by campersau** [comment]
@onovotny was this fixed by https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/pull/872 ?

**Comment by onovotny** [comment]
Should be, I think?
