### ISSUE TITLE
the type initializer for httpcontentwrapper threw an exception

### ISSUE THREAD

**Issue by MulderLiu** [NuGetPackageExplorer/NuGetPackageExplorer#866]
Hi! Thanks for reporting this feature/bug/question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

**Type** (choose one):

- Bug

**NPE version**: 5.5.23

**OS version**: Windows  10 - 1803

**Installed from**: Microsoft Store

In case of a BUG:
when i publish package get error info "the type initializer for httpcontentwrapper threw an exception"

**Comment by campersau** [comment]
Thanks! Somehow the tests in https://github.com/NuGet/NuGet.Client/pull/3078 didn't catch that. Will be fixed with https://github.com/NuGet/NuGet.Client/pull/3120

**Comment by boockie** [comment]
When will be fixed? I need fix asap :-(
