### ISSUE TITLE
<icon> node cause "This operation is not supported." exception

### ISSUE THREAD

**Issue by GreatFireWall** [NuGetPackageExplorer/NuGetPackageExplorer#869]
**Type** (choose one):

- Bug

**NPE version**: `NuGet Package Explorer - Store - X64 - (5.4.1+e95bd234fd)`

**OS version**: `Windows 10 1903`

**Installed from**: `Microsoft Store`

In case of a BUG:

- What is the current result?

If my package contains a `<icon>` node, when I click `Publish` it will casue an exception.

![image](https://user-images.githubusercontent.com/4510984/68992476-ef439b00-08a6-11ea-9bf1-ff47eaeb62a8.png)

![image](https://user-images.githubusercontent.com/4510984/68992477-f23e8b80-08a6-11ea-836b-6440517a3eaf.png)

- What is the expected result?

Works well even if contains <icon> node.

- Please post full exception details in case of an Exception (message, stacktrace, inner exceptions).

This operation is not supported.

- Are there any workarounds? yes/no

No.

- Is there a version in which it did work?

Never try.

- Is there a package on Nuget.org which shows the bug?

**Comment by onovotny** [comment]
Please try the latest version, 5.5.28. That should have working icon support.

**Comment by GreatFireWall** [comment]
I have try `5.5.28` just now, but has same issue.

**Comment by campersau** [comment]
This line throws the exception: https://github.com/NuGet/NuGet.Client/blob/c5c6ba438f4929e7ebe75e45ad69a8b113f7c388/src/NuGet.Core/NuGet.Packaging/PackageCreation/Authoring/PackageBuilder.cs#L630

In the `PackageHelper` the files from the `ZipArchive` package are added to the `PackageBuilder`. But zip streams don't support accessing its `Length` property.
https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/9a3863db2003a1f3b6ac33f5d9afaf756d9ccf7a/PackageViewModel/Utilities/PackageHelper.cs#L25

Steps to reproduce:
1. Open a package from a NuGet feed which uses an`<icon>` (like `Newtonsoft.Json`) **or** open a local package which uses an `<icon>`.
2. Remove package signature if there is one.
3. `File` -> `Publish...` **or** `File` -> `Save as...` **or** `File` -> `Save`

A possible fix would be to check for an icon file, extract it from the zip and supply that instead.

**Comment by onovotny** [comment]
Was really hoping to avoid extracting icons as temporary files :/

**Comment by GreatFireWall** [comment]
Thank you very much for fix this issue. 🌹

**Comment by i-e-b** [comment]
This issue also affects "Readme" files in the release: `NuGet Package Explorer - Zip - X64 - (5.10.4+4ab9498d27)`
