### ISSUE TITLE
Double clicking .nupkg with spaces in path does not open it

### ISSUE THREAD

**Issue by JVimes** [NuGetPackageExplorer/NuGetPackageExplorer#871]
**Type**: Bug
**NPE version**: 5.5.28+9a3863db20
**OS version**: Windows 10 1903
**Installed from**: Chocolatey.org

A .nupkg whose path has spaces does not open when double clicked. NPE launches but does not open the package. It seems caused by an un-quoted path in the default value of this registry key: `HKLM:\SOFTWARE\Classes\Nuget.Package\Shell\Open\Command\`.

This should be fixed by dd695ea1d89cc7dad2effd24790781cee6667f96, and I see that change in the installed "C:\ProgramData\chocolatey\lib\NugetPackageExplorer\ChocolateyInstall.ps1", but my registry key value doesn't have the quotes. I even tried deleting the key and doing a clean install.

**Workaround:** Edit that registry key's "(default)" value, putting double quotes around the `$1`.

This may be a regression of #835.

**Comment by clairernovotny** [comment]
Closing as fixed.

**Comment by JVimes** [comment]
Thanks @wischi-chr and @clairernovotny! 🎉 Verified fixed for me.
