### ISSUE TITLE
Version 5.5.28 doesn't work on Windows 7 32 bits

### ISSUE THREAD

**Issue by fredatgithub** [NuGetPackageExplorer/NuGetPackageExplorer#883]
Hi! 
here is my bug:
 NuGetPackageExplorer.exe version 5.5.28.14490 doesn't start on Windows 7 X86.

**Type**:
- Bug

**NPE version**: 5.5.28

**OS version**: (Windows 7 - Microsoft Windows [version 6.1.7601] )
PROCESSOR_ARCHITECTURE=x86
PROCESSOR_IDENTIFIER=x86 Family 6 Model 15 Stepping 11, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=0f0b
**Installed from**: Zip on GitHub 

In case of a BUG:

- What is the current result? version not compatible with your Windows system (X86)
- What is the expected result? NuGetPackageExplorer opens ok
- Are there any workarounds? no
- Is there a version in which it did work? NuGetPackageExplorer-v5.0.230
- Is there a package on Nuget.org which shows the bug? no

**Comment by fredatgithub** [comment]
I have tested version 5.5.28 on a Windows 7 64 bits and it works fine

**Comment by onovotny** [comment]
Closing as any Win7 support is incidental. Windows 7 is no longer supported by Microsoft.
