### ISSUE TITLE
Package dependency ranges not supported

### ISSUE THREAD

**Issue by gregsdennis** [NuGetPackageExplorer/NuGetPackageExplorer#89]
**Type**: Bug

**NPE version**: 3.14

**Installed from**: ClickOnce

- What is the current result?
When adding a package dependency, version ranges like "[4.0.0-5.0.0)" are disallowed

- What is the expected result?
These ranges are valid for Nuget packages and should be allowed.

- Please post full exception details in case of an Exception (message, stacktrace, inner exceptions)
No exception occurs.

- Are there any work arrounds?
no

- Is there a version in which it did worked?
Unknown

- Is there a package on Nuget.org which shows the bug?
No.

**Comment by 304NotModified** [comment]
Can you post a screenshot or give a package so we can easily reproduce?

**Comment by 304NotModified** [comment]
bump

**Comment by gregsdennis** [comment]
Sorry.  Been distracted.
![version ranges](https://cloud.githubusercontent.com/assets/2676804/14770937/ced82262-0a41-11e6-926e-825b34e0ed36.png)

**Comment by 304NotModified** [comment]
ah thanks! This makes things more clear :)

**Comment by gregsdennis** [comment]
Hang on.. went to nuget site for docs.  syntax uses commas...

Commas work.

**Comment by gregsdennis** [comment]
Maybe support for interpreting a hyphen and changing to a comma automatically.  Other than that, I think this should be closed as a non-bug.

**Comment by 304NotModified** [comment]
:+1: thanks for testing.
