### ISSUE TITLE
Unable to load the service index for source https://api.nuget.org/v3/index.json

### ISSUE THREAD

**Issue by dmurty** [NuGetPackageExplorer/NuGetPackageExplorer#890]
Hi! Thanks for reporting this feature/bug/question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

**Type** (choose one):

- Bug

**NPE version**: (e.g. 5.x) (see Help -> about)
5.5.61+325be69768

**OS version**: (Windows 7, 10 - 1803/17134, etc)
Windows 10 1909 18363.535

**Installed from**: Microsoft Store / Chocolatey.org / Zip on GitHub / CI channel
Chocolatey.org

In case of a BUG:
Cannot browse or publish to any feed
when trying to browse get the error Unable to load the service index for source
Can browse feeds from visual studio and nuget.exe
I tried to add registry key to disable tls 1.3 but that did nothing.

**Comment by supershowwei** [comment]
I have same issue

**Comment by filipnavara** [comment]
Same here, installed from Windows Store, auto-updated in the background to 5.5.61+325be69768.

I checked with Fiddler and didn't see any attempts to make network requests to the feeds.

**Comment by onovotny** [comment]
I suspect this is #730. We haven't been able to determine what's causing it. The workaround for that is to uninstall and reinstall the app.

**Comment by filipnavara** [comment]
Indeed, reinstall helped.

**Comment by TantumLabs** [comment]
I started getting this issue and now reinstalling doesn't fix it.

**Comment by MSkille** [comment]
I experience the same problem. Tried to add http_proxy (none was previously set) and no_proxy, but none of these had any effect. NuGet Package Explorer has been an excellent tool up to a day or two ago, but now it does not work, even for my colleague who downloaded and installed today.
NuGet cli lists the available packages without problem.
