### ISSUE TITLE
aint workin

### ISSUE THREAD

**Issue by big-main** [NuGetPackageExplorer/NuGetPackageExplorer#893]
Hi! Thanks for reporting this feature/bug/question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

**Type** (choose one):

- Bug
- Feature request
- Question

**NPE version**: (e.g. 5.x) (see Help -> about)

**OS version**: (Windows 7, 10 - 1803/17134, etc)

**Installed from**: Microsoft Store / Chocolatey.org / Zip on GitHub / CI channel

In case of a BUG:

- What is the current result?
- What is the expected result?
- Please post full exception details in case of an Exception (message, stacktrace, inner exceptions).
- Are there any workarounds? yes/no
- Is there a version in which it did work?
- Is there a package on Nuget.org which shows the bug?

In case of a FEATURE REQUEST:
 
 - Why do we need it?
 - Please provide an use case.

**Comment by campersau** [comment]
What exactly isn't working?
Which version are you using?
Please fill out the issue template so we can better understand your problem, thanks!
