### ISSUE TITLE
Cannot open nuspec files with parameter identifier stored in the ID field.

### ISSUE THREAD

**Issue by whighsmith** [NuGetPackageExplorer/NuGetPackageExplorer#90]
- Question
  **NPE version**: (e.g. 3.14) 
  **Installed from**: clickonce

I can no longer open nuspec files that include a custom parameter in the ID field.
The error message below is displayed .....

The package ID 'AndroidPackage$suffix$' contains invalid characters.  Examples of valid package IDs include 'MyPackage' and 'MyPackage.Sample'

Should 'Nuget Package Explorer' prevent a user from opening a nuspec file that includes a parameter name/identifier embedded in the value for the nuspec ID ?

For example:

``````
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">
    <metadata>
        <id>AndroidPackage$suffix$</id>
        <version>$version$</version>
        <authors>build</authors>

```etc....

Thanks.

``````

**Comment by 304NotModified** [comment]
We can remove the check, but is this really valid? Missed that when reading the specs.

**Comment by whighsmith** [comment]
We use "nuget pack" parameters during teamcity builds to create environment specific nuget packages so the deployment tool we are using can be configured to deploy the appropriate packages for the target environment.

The command we use in TeamCity is as follows:

nuget pack AndroidPackage.nuspec -version %build.number% -properties "suffix=%NugetPackageIDSuffix%"

where NugetPackageIDSuffix is a TeamCity template variable and is changed depending on the branch being built.

Examples of these "nuget pack" commands are as follows:

nuget pack AndroidPackage.nuspec -version 1.0.0.0 -properties "suffix=_MyBranch"
nuget pack AndroidPackage.nuspec -version 1.0.0.1 -properties "suffix=_Test"
nuget pack AndroidPackage.nuspec -version 1.0.0.2 -properties "suffix="
nuget pack AndroidPackage.nuspec -version 1.0.0.3 -properties "suffix=_Release"

So we get nupkg files like the following:
AndroidPackage_MyBranch.1.0.0.0.nupkg
AndroidPackage_Test.1.0.0.1.nupkg
AndroidPackage.1.0.0.2.nupkg
AndroidPackage_Release.1.0.0.3.nupkg

with the internal ID set to:

AndroidPackage_MyBranch
AndroidPackage_Test
AndroidPackage
AndroidPackage_Release

Here is screenshot of 'Nuget Package Explorer' showing the metadata of an actual artifact produced by TeamCity.  Note that the nuspec file for this output was edited using a text editor.

![image](https://cloud.githubusercontent.com/assets/4950124/14580935/d7bf3b68-03ac-11e6-82f1-09c68365ecaf.png)


Thanks.

**Comment by 304NotModified** [comment]
This seems relativity new (at least in the docs)

> The file may also contain other replacement tokens that will be specified using the nuget pack -Properties feature.

https://docs.nuget.org/create/nuspec-reference#replacement-tokens

**Comment by 304NotModified** [comment]
Confirm it isn't working, but dunno how to fix yet.

![image](https://cloud.githubusercontent.com/assets/5808377/15659176/d59c17a6-26c6-11e6-9c4e-cd7a4f795416.png)
