### ISSUE TITLE
Source Link check doesn't look in tools directory

### ISSUE THREAD

**Issue by AArnott** [NuGetPackageExplorer/NuGetPackageExplorer#915]
**Type**: Feature request

**NPE version**: 5.6.25+a5e5448620

**OS version**: Windows 10

**Installed from**: Microsoft Store

I wanted to see if I had done my Source Link right in my package, so I opened it up in NPE.
![image](https://user-images.githubusercontent.com/3548/77826990-aca59100-70d8-11ea-8d67-b47286fb0527.png)

This package doesn't have a lib folder, which I suspect is why NPE couldn't detect any need for source link. But it *does* have a tools folder that contains binaries that I want source link info for.

Can NPE be updated to search for source link info under tools?

**Comment by clairernovotny** [comment]
For now, this is by design since tools are likely to include files that are out of the author's control. 

I'm happy to include `tools` if there's a way we can look for "first party" things.

**Comment by AArnott** [comment]
Ya, I wondered about that. I can't think of a good way to solve that.
Thanks for your consideration.

**Comment by clairernovotny** [comment]
For tools, we might be able to get the tool name from the manifest and check that file. If there are other related files, that could be challenging.

The logic to gather files is here: https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/master/PackageViewModel/SymbolValidation/SymbolValidator.cs#L83-L85
