### ISSUE TITLE
Package analyzer CLI (or consumable analysis library)

### ISSUE THREAD

**Issue by tillig** [NuGetPackageExplorer/NuGetPackageExplorer#919]
**Type**: Feature request
**OS version**: Mac OS 10.15.4 (yeah, I'll explain)

I've been doing a lot of my development/packaging on MacOS and Linux platforms since .NET Core came out. Unfortunately, that means no NuGet Package Explorer for me, which isn't bad; I can use Parallels or something like that if it becomes necessary. Note my majority use case is browsing existing packages, not creating or publishing packages.

I noticed some of the [pretty sweet 'NuGet package analysis' features tweeted](https://twitter.com/clairernovotny/status/1244007715778834432) by @clairernovotny and it got me a thinking... it would be really cool to be able to run at least the package analysis part from a command line. That way I could check a built package without having to fire up a VM... but also, I could add something like that as part of my CI build and check the results there, failing if things don't check out.

I understand this is a bit outside the scope of NuGet Package Explorer, but it occurs to me that if the bits that do the analysis were in some consumable package outside the UI it would be easy enough to wrap them in a global `dotnet` tool and call it a day.

The "simplest thing that could possibly work" would be something like writing out a JSON-formatted report of the health parts of the analysis:

```json
{
  "health": {
    "signature": {
      "valid": true
    },
    "sourceLink": {
      "valid": true
    },
    "deterministic": {
      "valid": false,
      "messages": [
        "Package is non-deterministic.",
        "Ensure the following properties are enabled on CI builds..."
      ]
    }
  }
}
```

Admittedly, that may not be the best report schema. Maybe it needs to be something more like what comes out of a Roslyn analyzer with a warning code and a message, such that only issues are reported and successes are omitted.

```json
[
  { "code": "NGPE10003", "message": "Package is non-deterministic." }
]
```

Regardless, the idea is that it'd be really cool to be able to access that analysis bit outside the UI in a .NET Core app so it could be used cross-platform.

**Comment by clairernovotny** [comment]
I agree this would be awesome. This would require some refactoring though as we're currently depending on `PackageFile` in the ViewModel layer as it handles the path/tree parsing and associations. 

I'd be happy for someone to jump in on this. `Core` can probably be used as-is as it's not ViewModel.

Note that I don't know how much of this can be cross-platform. That would need to be investigated as we do support reading/converting Windows PDB's to Portable for use in the analysis. Also, in one place we're checking for Authenticode signatures to see if it's a Microsoft package that symbols should be acquired from the MSDL symbol server. 

To set expectations, I'm not likely to work on this directly but will support a PR for someone who wants to do this.
