### ISSUE TITLE
Determinism health check when built with SDK 3.1.200

### ISSUE THREAD

**Issue by sunahe** [NuGetPackageExplorer/NuGetPackageExplorer#920]
**Type**: Bug

**NPE version**: (e.g. 5.x) 5.6.40

**OS version**: Windows 10 - 1909

**Installed from**: Microsoft Store

NuGet Package Explorer insists that my package is non deterministic and offers to rebuild it with a `Deterministic=true, ContinuousIntegrationBuild=true`. The package is already built using those properties though. In dotPeek the package can be seen to be marked as deterministic.

Similarly, a problem is reported with Source Link. The problem reported is really present, but the recommended solution (setting `EmbedUntrackedSources=true`) has no effect.

The package is built using dotnet SDK 3.1.200. Same results when built on Windows (dev PC) or Ubuntu (Azure Pipelines).

Minimal repro case:
https://github.com/sunahe/SLTest2/blob/master/src/SLTest/SLTest.csproj
https://www.nuget.org/packages/SLTest/1.0.1

![image](https://user-images.githubusercontent.com/11211938/78030458-6b281680-7362-11ea-9f5e-86d134cb4365.png)
![image](https://user-images.githubusercontent.com/11211938/78030713-cf4ada80-7362-11ea-9670-e7ba4ed1ab27.png)

**Comment by clairernovotny** [comment]
It is accurate. Unfortunately there's a bug in the 3.x SDK's that will be fixed in 3.1.300. Until then, there's a workaround here:
https://github.com/dotnet/sourcelink/issues/572

**Comment by sunahe** [comment]
Thanks Claire!
Doesn't seem that the bug is only in 3.x SDK – the determinism check fails when the package is built with 2.1.x SDKs as well (I tried with 2.1.302 to 2.1.800). That makes the help tooltip misleading. Shouldn't it recommend 3.1.300 or higher?

![image](https://user-images.githubusercontent.com/11211938/78048705-6a9b7a00-737a-11ea-89e4-d5ed05e65d4a.png)

**Comment by clairernovotny** [comment]
Those properties exist since 2.1.300 and I recall some versions of the SDK properly working before. It's also possible to get it working with the workaround, so I don't want to tell people to use 3.1.300 yet as it't not available outside of nightlies yet.

**Comment by sunahe** [comment]
It was frustrating to get some advice from a tool and then discover the advice doesn’t work. It was not specified anywhere that the workaround exists – so I’m still convinced the tool lies.

It was nice to get the help from you though. Hopefully others won’t find it ridiculous that the full truth is hidden somewhere in github comments.
