### ISSUE TITLE
Analysis suggests using Summary, but it is being deprecated

### ISSUE THREAD

**Issue by drewnoakes** [NuGetPackageExplorer/NuGetPackageExplorer#924]
**Type**:

- Bug?

**NPE version**: NuGet Package Explorer - Store - X64 - (5.6.40+0baf79cb07)

**OS version**: Windows 10 - 1909

**Installed from**: Microsoft Store

The "Analyze Package" tool suggests adding a `Summary` to the package.

![image](https://user-images.githubusercontent.com/350947/78413798-d0328380-7664-11ea-91f5-663aeb3a7589.png)

However, the `summary` property is being deprecated: https://docs.microsoft.com/en-us/nuget/reference/nuspec#summary

Is this guidance still useful? Perhaps the analyzer could work out whether NuGet uses the first sentence, and warn if that's too long.

**Comment by wenz** [comment]
The NuGet client has removed their version of this check altogether (https://github.com/NuGet/NuGet.Client/commit/41e8bde59e9a9e62e71b049ab52a379574d6f3c2) - so I'd proposed that's the best way to resolve this issue, too.
