### ISSUE TITLE
Opening local .nupkg doesn't pick up sibling .snupkg

### ISSUE THREAD

**Issue by drewnoakes** [NuGetPackageExplorer/NuGetPackageExplorer#925]
**Type**:

- Feature request

**NPE version**: NuGet Package Explorer - Store - X64 - (5.6.40+0baf79cb07)

**OS version**: Windows 10 - 1909

**Installed from**: Microsoft Store

Thanks for this application! It highlighted my package [`MetadataExtractor/2.3.0`](https://www.nuget.org/packages/MetadataExtractor/2.3.0) as not being configured correctly for SourceLink:

![image](https://user-images.githubusercontent.com/350947/78414341-649de580-7667-11ea-9933-466378833677.png)

So I'm now working locally to fix it.  Building produces both nupkg/snupkg files, and when I load the nupkg in NuGet Package Explorer I see:

![image](https://user-images.githubusercontent.com/350947/78414580-7df36180-7668-11ea-8284-b1452bb32ade.png)

I'm confused why my published package (2.3.0) says there's no SourceLink for three of the four targets' DLLs, as I am referencing SourceLink and believe it's configured appropriately. I would like to make changes locally and use NPE to verify correctness before publishing the package, but I seem to be stuck on NPE finding the symbols in the supkg file.

**Comment by clairernovotny** [comment]
The reason for this is that it currently only checks snupkg for packages published to NuGet.org.

**Comment by clairernovotny** [comment]
We need to change this 
https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/master/PackageViewModel/SymbolValidation/SymbolValidator.cs#L261

To check for a local sibling file first before going to NuGet.org. The rest of the logic would be the same.

**Comment by drewnoakes** [comment]
Thanks for the pointer. I'll add support for this.
