### ISSUE TITLE
Bring back the default .nupkg "open with" option

### ISSUE THREAD

**Issue by flyergo** [NuGetPackageExplorer/NuGetPackageExplorer#93]
After the last update (3.14.0.0) **.nupkg** is no longer associated with **NuGet Package Explorer** like it used to before. I'd like to request to bring that feature back. 

Forgot to mention: OS is Windows 7 SP1

**Comment by 304NotModified** [comment]
is this with chocolatey install of clickonce?

**Comment by 304NotModified** [comment]
Please us the template.

**Comment by flyergo** [comment]
Yes. 
I opened the explorer by double-clicking the .nupgk which triggered the ClickOnce update dialog.
After the update the explorer opened without the file argument showing the common tasks background.
So I went back and the file association was gone.

**Comment by 304NotModified** [comment]
That's strange as it is broken in chocolatey but not in clickonce AFAIK

**Comment by Auersberg** [comment]
Same here. After installing the ClickOnce package file associations to .nuspec and .nupkg have not been set.

**Comment by 304NotModified** [comment]
Thanks, we will check this soon!

**Comment by 304NotModified** [comment]
Working on this now
