### ISSUE TITLE
Shell access to NuGet Package won't open in Package Explorer

### ISSUE THREAD

**Issue by RickStrahl** [NuGetPackageExplorer/NuGetPackageExplorer#969]
**Type** (choose one):

- Bug

**NPE version**: (e.g. 5.x) (see Help -> about)
NuGet Package Explorer - Store - X64 - (5.6.70+e3d04185cb)

**OS version**: (Windows 7, 10 - 1803/17134, etc)
Windows 10

**Installed from**: Microsoft Store / Chocolatey.org / Zip on GitHub / CI channel
Originally from Choco, then tried from Store - same issue

Although there appears to be an association between `.nupkg` files and the Package Explorer trying to open the Explorer via double clicking or Open With... fails with the following error:

![image](https://user-images.githubusercontent.com/1374013/80420280-37171700-8876-11ea-9e4c-a0248398634e.png)

If I use Open With... and reassociate package explorer the result stays the same.

If I open the package directly in the Explorer or drag it from Explorer it opens fine and I can perform all my normal package operations, so it doesn't appear that the package is the problem. Same behavior with different packages - several dotnet tools and a number nuget packages.

I'm not sure if the error message is coming from the Package Explorer or something else.  If it is it's probably a good idea for the error message to have some info on it relating to PE.

In the past direct clicks failed but **Open With...** worked but lately even **Open With...** is failing and I can only open by explicitly running PE then opening the package from there.

Version in use above is the Store version I just installed to make sure I'm on latest.

**Comment by clairernovotny** [comment]
Are you able to attach a debugger to the running process when it hits that point and get a stack/dump or other information? 

I can't think of anything in NPE that would show that dialog -- file launching is just a cmd line arg to the exe and hits this code path:

https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/master/PackageExplorer/App.xaml.cs#L85

And that code path is the same as the file open in the file dialog: https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/master/PackageExplorer/MainWindow.xaml.cs#L349

**Comment by RickStrahl** [comment]
Checked to see and sure enough the package explorer is not running when the dialog pops. So looks like this is a shell mapping issue. 

Oddly just now I was able to open with Open With... but double click still doesn't work. I'll check the association and see what I find but it's just odd that sometimes it works and sometimes doesn't.

**Comment by RickStrahl** [comment]
Took a look in the registry and it's all pointing to the crazy Store package ids - no full paths to anything. I think I'll uninstall the store version and try again with the Choco install instead even though that wasn't any better, but at least I'll be able to trace that back to the binaries. :smile:

**Comment by clairernovotny** [comment]
Really strange :/
