### ISSUE TITLE
The process cannot access the file when editing / saving package

### ISSUE THREAD

**Issue by ImGonaRot** [NuGetPackageExplorer/NuGetPackageExplorer#97]
**Type** (Bug)

**NPE version**: (3.15)

**Installed from**: (ClickOnce)

When saving a package after a new edit of a package that has been saved before I get the following.
![image](https://cloud.githubusercontent.com/assets/8114712/14790627/057e29a8-0ae0-11e6-95c3-3a3d91b7ac68.png)
This is working fine in 3.14 and lower.
Computer is Windows 10 x64.

Oh, I also downloaded and compiled the 3.15 solution and still receive the same error when running NuGetPackageExplorer.exe

When I downloaded and compiled the 3.14 solution it works fine.

**Comment by 304NotModified** [comment]
Thanks. This is probably due to https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/pull/87

Strange as I did tested saving a package.

**Comment by ImGonaRot** [comment]
It does work on save. It is when I close, reopen, and then try to save again that I get the error.





On Mon, Apr 25, 2016 at 10:04 AM -0700, "Julian Verdurmen" <notifications@github.com> wrote:





Thanks. This is probably due to https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/pull/87

Strange as I did tested saving a package.

---

**Comment by ImGonaRot** [comment]
Here are the steps I used to produce the problem.

1. Open NuGetPackageExplorer.application
2. Create a new package
3. Added DLL's to the lib\net40
4. Save the package as *.nupkg
5. Exit NuGetPackageExplorer.application
6. Open the *.nupkg file with NuGetPackageExplorer.application
7. Change the version
8. Click File -> Save 
9. Get the Error

**Comment by 304NotModified** [comment]
Thanks!

**Comment by jansenbe** [comment]
+1 on the repro steps from @ImGonaRot

**Comment by zellus** [comment]
After downgrading to 3.14 'save' is back working.

**Comment by 304NotModified** [comment]
This is indeed introduced in 3.15, with https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/pull/87

Too bad I had no time to fix this.
