### ISSUE TITLE
macOS version Please

### ISSUE THREAD

**Issue by TravisEz13** [NuGetPackageExplorer/NuGetPackageExplorer#972]
Hi! Thanks for reporting this feature/bug/question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

**Type** (choose one):

- Feature request

**NPE version**: (e.g. 5.x) (see Help -> about)

**OS version**: macOS

**Installed from**: I propose brew

In case of a BUG:

In case of a FEATURE REQUEST:
 
 - Why do we need it?
It's my primary dev environment.

 - Please provide an use case.
see above.

**Comment by remy90** [comment]
Why not use the dotnet-validate tool?

**Comment by clairernovotny** [comment]
See #1294 

And [NuGet.info](https://nuget.info)
