### ISSUE TITLE
AWSSDK 2.3.55.2 won't validate SourceLink

### ISSUE THREAD

**Issue by JasonRShaver** [NuGetPackageExplorer/NuGetPackageExplorer#976]
- Bug

**NPE version**: 5.6.70

**OS version**: Win10

**Installed from**: Microsoft Store and running code from GitHub

When searching for "AWSSDK" (2.3.55.2 came up) and selecting the top package (the aws sdk), the `Source Link` and `Deterministic` fields hang on 'Pending'.  In running the code, it's seems hung in `PdbConverter.Default.ConvertWindowsToPortable(peStream, pdbStream, _temporaryPdbStream);`

And btw, keep up the great work on this project =)

**Comment by clairernovotny** [comment]
Looks like there's a deeper issue:
https://github.com/dotnet/symreader-converter/issues/173

**Comment by JasonRShaver** [comment]
I let this sit once while I went to eat dinner and it actually ended up returning (same build/versions as my initial report), so closing now that ux hang is addressed.
