### ISSUE TITLE
Windows and antivirus block the installer

### ISSUE THREAD

**Issue by baharestani** [NuGetPackageExplorer/NuGetPackageExplorer#98]
Hi! Thanks for reporting this feature/bug/question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

**Type** (choose one):

- Bug

**NPE version**: 3.15.0.0

**Installed from**: ClickOnce 

In case of a BUG:

Whenever I try to install a new version, Windows smartscreen and then my Symantec antivirus warn me to avoid the installation.

**Comment by 304NotModified** [comment]
This is a known issue. We don't have a paid source signing certificate, which is expensive (lot more than a SSL certificate)
