### ISSUE TITLE
unable to save package

### ISSUE THREAD

**Issue by godrose** [NuGetPackageExplorer/NuGetPackageExplorer#99]
1. Press 'Edit metadata'
2. Edit the description field.
3. Save the package.

Expected: Saved successfully
Actual: The process cannot access the [package name] because it is being used by another process.

Now, seriously. If your CI is screwed please stop releasing new versions until you sort this out.
Thanks a lot.

**Comment by 304NotModified** [comment]
Fixed by #105 . 



> Now, seriously. If your CI is screwed please stop releasing new versions until you sort this out.
> Thanks a lot.

@godrose I prefer more constructive comments. It's open-source, you can also help fixing issues.
