### ISSUE TITLE
nuget package not getting uploaded on successful released build

### ISSUE THREAD

**Issue by AshishPayU** [NuGetPackageExplorer/NuGetPackageExplorer#996]
Hi,

We need to upload a package on NuGet, the build got successful & We have cross-checked everything at our end.

But, still it is not getting uploaded, below is the error:
 Failed to read the package file. Ensure it is a valid NuGet package with a valid manifest.

Below is my VS version:
Visual Studio Community 2019 for Mac
Version 8.6 (build 4520)
Installation UUID: 9dd2c7ff-ef51-46d5-adbe-bfb60909615d
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 610000104

Kindly provide the solution asap, it is very critical for us.

**Comment by clairernovotny** [comment]
How is the package being created?

**Comment by AshishPayU** [comment]
Hi Claire,
It is published now, but added some suffix to package name.
Will remove those suffixes with new release.

And, thank you for your help. :)
